export const HAPPY_BUMP_NARRATION = Object.freeze({
  arrival: "This is a small lift, built one step at a time. There is no need to feel motivated before you begin.",
  baseline: "Take an honest read of your energy. There is no right number.",
  hydrate: "Have some water if it is available. Small care counts.",
  window: "Get to a window or outside for thirty seconds.",
  environment: "Choose the safest practical route for a short walk.",
  move: "Take this at your own pace. You can pause, shorten it, or simply keep moving.",
  connection: "One genuine signal is enough. Skipping connection is also a deliberate choice.",
  win: "Choose one finish small enough to complete or honestly begin.",
  mission: "For this moment, only this one mission matters.",
  proud: "Notice one thing you are proud of. A small thing is still real.",
  grateful: "Notice one thing that is here to appreciate, without forcing a feeling.",
  anticipate: "Name one small thing ahead that has a little pull.",
  lifeArea: "Choose the part of life that could use a little care next.",
  areaAction: "Choose the lowest-effort step that feels realistic, not impressive.",
  nextMode: "Decide what would serve you now: progress, enjoyment, or rest.",
  nextPlan: "Make the next activity easy to enter. Keep it concrete and kind.",
  rerate: "Take another honest read. The actions count whether the number changed or not.",
  reveal: "This is a comparison, not a score. Notice what shifted, stayed, or simply became possible.",
  complete: "You made a sequence of small choices. Keep only what fits from here.",
});
