import { afterEach,describe,expect,it,vi } from 'vitest';
import { createTappingAudio } from './tappingAudio';

function fixture({outputClock=false,resolveNarration=key=>({url:'/audio/narration/'+key+'.mp3'})}={}){
 const contexts=[],sources=[],events=[],fetchAudio=vi.fn(async()=>({ok:true,arrayBuffer:async()=>new ArrayBuffer(16)}));
 const gain=()=>({gain:{value:0,cancelScheduledValues:vi.fn(),setTargetAtTime:vi.fn()},connect:vi.fn()});
 let wallTime=null,outputLag=0;
 const now=()=>wallTime??(contexts[0]?.currentTime-10||0)*1000;
 class Audio {state='suspended';currentTime=10;destination={};listeners={};gains=[];
  constructor(){contexts.push(this);}
  getOutputTimestamp=outputClock?()=>({contextTime:this.currentTime-outputLag,performanceTime:now()}):undefined;
  resume=vi.fn(async()=>{this.state='running';});close=vi.fn(async()=>{this.state='closed';});
  createGain(){const g=gain();this.gains.push(g);return g;}
  decodeAudioData=vi.fn(async()=>({duration:48}));
  addEventListener=(kind,cb)=>{this.listeners[kind]=cb;};removeEventListener=vi.fn();
  createBufferSource(){const source={playbackRate:{value:1},connect:vi.fn(),disconnect:vi.fn(),start:vi.fn(),stop:vi.fn()};sources.push(source);return source;}
 }
 const errors=vi.fn(),interrupted=vi.fn(),mixer=createTappingAudio({AudioContextClass:Audio,fetchAudio,resolveNarration,onError:errors,onInterrupted:interrupted,now,onEvent:(kind,event)=>events.push({kind,...event})});
 return{mixer,contexts,sources,events,fetchAudio,errors,interrupted,setClock:(wall,lag=outputLag)=>{wallTime=wall;outputLag=lag;}};
}
afterEach(()=>vi.useRealTimers());
describe('offline tapping voice/music/contact mixer',()=>{
 it('prefetches without hardware and unlocks directly in the Start gesture',async()=>{const f=fixture();await f.mixer.preload('worry');expect(f.contexts).toHaveLength(0);const enabled=f.mixer.activate('worry');expect(f.contexts[0].resume).toHaveBeenCalledOnce();expect(await enabled).toBe(true);expect(f.sources).toHaveLength(0);f.mixer.run();expect(f.events[0].kind).toBe('music');f.mixer.dispose();});
 it('ducks music under the real spoken clip and accepts the selected cadence contact offset',async()=>{const f=fixture();await f.mixer.activate('worry');f.mixer.run();f.mixer.speak('place-brow');f.mixer.beat(320);expect(f.events.map(e=>e.kind)).toEqual(['music','voice','beat']);expect(f.events[2].at).toBe(10.32);expect(f.sources[0].loop).toBe(true);expect(f.contexts[0].gains[1].gain.setTargetAtTime).toHaveBeenLastCalledWith(.12,10,.16);f.sources[1].onended();expect(f.contexts[0].gains[1].gain.setTargetAtTime).toHaveBeenLastCalledWith(.45,10,.16);f.mixer.dispose();});
 it('pause immediately cancels music, voice and queued contact; Resume continues the sentence',async()=>{const f=fixture();await f.mixer.activate('worry');f.mixer.run();f.mixer.speak('place-hand');f.mixer.beat();f.contexts[0].currentTime=11.5;f.mixer.pause();for(const source of f.sources)expect(source.stop).toHaveBeenCalled();f.mixer.run();expect(f.events.at(-1)).toMatchObject({kind:'voice',key:'place-hand'});expect(f.events.at(-1).offset).toBeCloseTo(1.5);expect(f.sources.at(-1).playbackRate.value).toBe(1);f.mixer.cancel();f.mixer.run();expect(f.events.at(-1).kind).toBe('music');f.mixer.dispose();});
 it.each([600,800])('queues enough %ims contacts to survive a 420ms scheduler delay, then cancels on pause',async beatMs=>{vi.useFakeTimers();const f=fixture();await f.mixer.activate('worry');f.mixer.run();f.mixer.startRhythm({beatMs,contactMs:beatMs*.4,phaseMs:100});const first=f.events.filter(e=>e.kind==='beat').map(e=>e.at);expect(first).toHaveLength(2);expect(first[0]).toBeCloseTo(10+(beatMs*.4-100)/1000);expect(first[1]-first[0]).toBeCloseTo(beatMs/1000);f.contexts[0].currentTime=10.42;vi.advanceTimersByTime(40);f.contexts[0].currentTime=11.25;vi.advanceTimersByTime(40);const times=f.events.filter(e=>e.kind==='beat').map(e=>e.at);for(let i=1;i<times.length;i++)expect(times[i]-times[i-1]).toBeCloseTo(beatMs/1000);f.mixer.pause();const length=f.events.length;f.contexts[0].currentTime=20;vi.advanceTimersByTime(4000);expect(f.events).toHaveLength(length);for(const source of f.sources)expect(source.stop).toHaveBeenCalled();f.mixer.dispose();});
 it('uses the output clock and repositions only future contacts when it drifts',async()=>{vi.useFakeTimers();const f=fixture({outputClock:true});f.setClock(1000,.05);await f.mixer.activate('worry');f.mixer.run();f.mixer.startRhythm({beatMs:600,contactMs:240});expect(f.events.filter(e=>e.kind==='beat').map(e=>e.at)).toEqual([10.19,10.79]);f.setClock(1100,.1);f.contexts[0].currentTime=10.1;vi.advanceTimersByTime(40);expect(f.sources[1].stop).toHaveBeenCalledOnce();expect(f.sources[2].stop).toHaveBeenCalledOnce();expect(f.events.filter(e=>e.kind==='beat').slice(-2).map(e=>e.at)).toEqual([10.14,10.74]);f.mixer.configure({beat:false});const length=f.events.length;f.setClock(2000);vi.advanceTimersByTime(1000);expect(f.events).toHaveLength(length);f.mixer.dispose();});
 it('ignores small output timestamp jitter rather than repeatedly replacing contacts',async()=>{vi.useFakeTimers();const f=fixture({outputClock:true});f.setClock(1000,.05);await f.mixer.activate('worry');f.mixer.run();f.mixer.startRhythm({beatMs:800,contactMs:320});const length=f.events.length;f.setClock(1020,.06);f.contexts[0].currentTime=10.02;vi.advanceTimersByTime(40);expect(f.events).toHaveLength(length);for(const source of f.sources)expect(source.stop).not.toHaveBeenCalled();f.mixer.dispose();});
 it('skips contacts missed during a long stall without playing a catch-up burst',async()=>{vi.useFakeTimers();const f=fixture({outputClock:true});f.setClock(1000,.05);await f.mixer.activate('worry');f.mixer.run();f.mixer.startRhythm({beatMs:600,contactMs:240});const length=f.events.length;f.setClock(3500);f.contexts[0].currentTime=12.5;vi.advanceTimersByTime(40);const future=f.events.slice(length);expect(future).toHaveLength(2);expect(future.every(e=>e.at>12.5)).toBe(true);expect(future[1].at-future[0].at).toBeCloseTo(.6);f.mixer.cancel();f.setClock(5000);vi.advanceTimersByTime(1000);expect(f.events).toHaveLength(length+2);f.mixer.dispose();});
 it('falls back to the visual clock when output timestamps have not started',async()=>{const f=fixture({outputClock:true});await f.mixer.activate('worry');f.contexts[0].getOutputTimestamp=()=>({contextTime:0,performanceTime:0});f.mixer.run();f.mixer.startRhythm({beatMs:600,contactMs:240});expect(f.events.filter(e=>e.kind==='beat').map(e=>e.at)).toEqual([10.24,10.84]);f.mixer.dispose();});
 it('does not drop an imminent contact when a clock update maps it into the past',async()=>{vi.useFakeTimers();const f=fixture({outputClock:true});f.setClock(1000,.05);await f.mixer.activate('worry');f.mixer.run();f.mixer.startRhythm({beatMs:600,contactMs:240});f.setClock(1180,.15);f.contexts[0].currentTime=10.1;vi.advanceTimersByTime(40);expect(f.sources[1].stop).toHaveBeenCalledOnce();const replacement=f.events.filter(e=>e.kind==='beat').slice(-2)[0];expect(replacement.at).toBeCloseTo(10.105);expect(replacement.at).toBeGreaterThan(f.contexts[0].currentTime);f.mixer.dispose();});
 it('rejects transient output timestamps in the future and retains a playable rhythm',async()=>{vi.useFakeTimers();const f=fixture({outputClock:true});f.setClock(1000,.05);await f.mixer.activate('worry');f.mixer.run();f.mixer.startRhythm({beatMs:800,contactMs:320});f.setClock(1100);f.contexts[0].currentTime=10.1;f.contexts[0].getOutputTimestamp=()=>({contextTime:10.09,performanceTime:1150});vi.advanceTimersByTime(40);const replacements=f.events.filter(e=>e.kind==='beat').slice(-2);expect(replacements[0].at).toBeCloseTo(10.32);expect(replacements[1].at).toBeCloseTo(11.12);f.mixer.dispose();});
 it('cancels an expired visual contact while the audio clock is stalled',async()=>{vi.useFakeTimers();const f=fixture({outputClock:true});f.setClock(1000,.05);await f.mixer.activate('worry');f.mixer.run();f.mixer.startRhythm({beatMs:600,contactMs:240});const length=f.events.length;f.setClock(1500);f.contexts[0].currentTime=10.08;vi.advanceTimersByTime(40);expect(f.sources[1].stop).toHaveBeenCalledOnce();const future=f.events.slice(length);expect(future).toHaveLength(2);expect(future[0].at).toBeCloseTo(10.37);expect(future[1].at).toBeCloseTo(10.97);f.mixer.dispose();});
 it('changing one channel stops only that channel and releases ducking',async()=>{const f=fixture();await f.mixer.activate('worry');f.mixer.run();f.mixer.speak('place-collar');f.mixer.beat();f.mixer.configure({voice:false});expect(f.sources[1].stop).toHaveBeenCalledOnce();expect(f.sources[0].stop).not.toHaveBeenCalled();f.mixer.configure({music:false,beat:false});expect(f.sources[0].stop).toHaveBeenCalledOnce();expect(f.sources[2].stop).toHaveBeenCalledOnce();f.mixer.dispose();});
 it('reports a failed voice asset, keeps the available bed/beat and genuinely retries',async()=>{const f=fixture();f.fetchAudio.mockImplementation(async url=>({ok:!url.includes('place-brow'),arrayBuffer:async()=>new ArrayBuffer(16)}));expect(await f.mixer.activate('worry')).toBe(true);expect(f.errors).toHaveBeenCalledWith('voice');f.mixer.run();f.mixer.speak('place-hand');f.mixer.beat();expect(f.events.map(e=>e.kind)).toEqual(['music','beat']);f.mixer.pause();f.fetchAudio.mockImplementation(async()=>({ok:true,arrayBuffer:async()=>new ArrayBuffer(16)}));await f.mixer.activate('worry',{voice:true,music:true,beat:true});f.mixer.run();f.mixer.speak('place-brow');expect(f.events.at(-1).kind).toBe('voice');f.mixer.dispose();});
 it('never falls back to the rejected voice when matching recordings are missing',async()=>{const f=fixture({resolveNarration:()=>null});await f.mixer.activate('worry');expect(f.errors).toHaveBeenCalledWith('voice');expect(f.fetchAudio.mock.calls.map(([url])=>url).sort()).toEqual(['/media/tapping/audio/contact.mp3','/media/tapping/audio/warm-room.mp3']);f.mixer.run();f.mixer.speak('place-brow');f.mixer.beat();expect(f.events.map(e=>e.kind)).toEqual(['music','beat']);f.mixer.dispose();});
 it('never activates late after pause or disposal',async()=>{const f=fixture();let resolve;const pending=new Promise(r=>{resolve=r;});f.fetchAudio.mockImplementation(()=>pending);const activating=f.mixer.activate('worry');await Promise.resolve();f.mixer.dispose();resolve({ok:true,arrayBuffer:async()=>new ArrayBuffer(16)});expect(await activating).toBe(false);expect(f.sources).toHaveLength(0);expect(f.contexts[0].close).toHaveBeenCalledOnce();});
 it('rejects a resolved unlock when the context is still suspended',async()=>{const f=fixture();f.mixer.preload('worry');const activating=f.mixer.activate('worry');f.contexts[0].state='suspended';await expect(activating).rejects.toThrow('Audio unavailable');f.mixer.dispose();});
 it('an actual context interruption stops every source and asks the round to pause',async()=>{const f=fixture();await f.mixer.activate('worry');f.mixer.run();f.mixer.speak('place-arm');f.mixer.beat();f.contexts[0].state='interrupted';f.contexts[0].listeners.statechange();expect(f.interrupted).toHaveBeenCalledOnce();for(const source of f.sources)expect(source.stop).toHaveBeenCalled();f.mixer.dispose();});
});
