import { useEffect, useMemo, useRef, useState } from "react";
import { AnimatePresence, motion } from "framer-motion";
import { BookOpen, Check, ChevronRight, Compass, CupSoda, DoorOpen, Droplets, Ear, Eye, Flower2, Footprints, Hand, Heart, ListChecks, MessageCircle, Mic, Phone, Play, Send, SkipForward, Sparkles, Sprout, Sun, Users, Wallet } from "lucide-react";
import InterventionControlShell from "@/components/InterventionControlShell";
import { useAccessibilityPrefs } from "@/hooks/useAccessibilityPrefs";
import { clearActiveFlagship, getActiveFlagship, rememberFlagshipEvent, saveActiveFlagship } from "@/lib/flagshipMemory";
import { hapticPattern, playComplete, playSelect } from "@/lib/feedback";
import { getBumpsCompletedThisWeek, recordBumpScene, startBumpRun } from "@/lib/happyBumpFunnel";
import { getLastFocus, saveLastFocus } from "@/lib/happyBumpMemory";
import { recordDislike } from "@/lib/preferences";
import { HAPPY_BUMP_NARRATION } from "@/lib/happyBumpNarration";
import { useGuideVoice } from "@/hooks/useGuideVoice";
import { useVoiceDictation } from "@/hooks/useVoiceDictation";
import { voiceFor } from "@/lib/spoken";

const ID = "happyBump";
const DURATION_SECONDS = 300;
const COMBO_KEY = "mentation.happyBump.combination.v1";
const STAGE = { arrival: 1, baseline: 1, hydrate: 2, window: 3, environment: 4, move: 4, connection: 5, win: 6, mission: 6, proud: 7, grateful: 7, anticipate: 7, lifeArea: 8, areaAction: 8, nextMode: 9, nextPlan: 9, rerate: 10, reveal: 10, complete: 11 };
const BACK = { baseline: "arrival", hydrate: "baseline", window: "hydrate", environment: "window", move: "environment", connection: "move", win: "environment", mission: "win", proud: "mission", grateful: "proud", anticipate: "grateful", lifeArea: "anticipate", areaAction: "lifeArea", nextMode: "areaAction", nextPlan: "nextMode", rerate: "nextPlan", reveal: "rerate", complete: "reveal" };
const SKIP = { arrival: "baseline", baseline: "hydrate", hydrate: "window", window: "environment", environment: "win", move: "win", connection: "win", win: "proud", mission: "proud", proud: "grateful", grateful: "anticipate", anticipate: "lifeArea", lifeArea: "nextMode", areaAction: "nextMode", nextMode: "rerate", nextPlan: "rerate", rerate: "reveal", reveal: "complete" };
const INITIAL = { scene: "arrival", baseline: 3, current: 5, hydrated: false, aired: false, environment: null, connection: null, task: null, customTask: "", elapsedBeforePause: 0, startedAt: null, paused: false, proud: "", grateful: "", lookingForward: "", lifeArea: null, areaAction: "", nextMode: null, nextActivity: "", pairing: "", reward: "", senses: [], activeSense: null, comfortIdea: "", customComfortIdea: "", saved: false, runId: null };
const TASKS = ["Put one thing away", "Reply to one message", "Open the curtains", "Clear one small surface"];
const REFLECTIONS = { proud: ["I got out of bed", "I kept going", "I moved my body", "I showed up", "I tried again"], grateful: ["Someone who cares", "A safe place", "A small comfort", "Music I love", "Fresh air"], anticipate: ["A favourite meal", "Seeing someone", "Resting later", "Getting outside", "A quiet evening"] };
const AREAS = [{ id: "relationships", label: "Relationships", Icon: Users, actions: ["Send a thank-you message", "Ask someone how they are", "Plan a short catch-up"] }, { id: "health", label: "Physical health", Icon: Heart, actions: ["Stretch for two minutes", "Step outside for fresh air", "Refill tomorrow's water"] }, { id: "purpose", label: "Purpose & work", Icon: Compass, actions: ["Write the first tiny step", "Open the document", "Choose tomorrow's priority"] }, { id: "growth", label: "Learning & growth", Icon: BookOpen, actions: ["Read two pages", "Practise for five minutes", "Choose a book to start"] }, { id: "financial", label: "Financial wellbeing", Icon: Wallet, actions: ["Check one account balance", "Set one bill reminder", "File one receipt"] }, { id: "community", label: "Community", Icon: Sprout, actions: ["Thank someone who helps", "Offer one small favour", "Choose one cause to learn about"] }];
const PLANS = { productive: ["Clear one surface", "Start the first five minutes", "Write tomorrow's top task"], enjoyable: ["Listen to an album", "Watch something funny", "Read for pleasure"], relaxing: ["Take a warm shower", "Make a warm drink", "Sit outside"] };
export const SENSE_COMFORT = Object.freeze({
  Sight: { Icon: Eye, ideas: ["Lower one bright light or close a distracting tab", "Look at a favourite photo or a calm view", "Step to a window and notice the light outside", "Put on a familiar, low-key visual you enjoy"] },
  Sound: { Icon: Ear, ideas: ["Play one familiar, gentle song", "Put on soft rain or a quiet room tone", "Take a minute somewhere with less noise", "Listen for one steady sound already nearby"] },
  Touch: { Icon: Hand, ideas: ["Wrap up in a soft layer or hold a warm mug", "Change into the most comfortable thing available", "Run warm water over your hands", "Rest a hand over your chest or on a soft surface"] },
  Smell: { Icon: Flower2, ideas: ["Light a candle if it is safe to do so", "Spray a favourite fragrance", "Open a window for fresh air", "Make a comforting tea and notice its scent"] },
  Taste: { Icon: CupSoda, ideas: ["Make a comforting tea or cold drink", "Have one small favourite snack slowly", "Add a familiar flavour to water", "Choose something warm or cool that feels pleasant"] },
});
const MODE_CHOICES = [
  { id: "productive", label: "Productive", detail: "Make one next step easier", Icon: Compass },
  { id: "enjoyable", label: "Enjoyable", detail: "Choose a little pleasure", Icon: Heart },
  { id: "relaxing", label: "Relaxing", detail: "Settle into comfort", Icon: Sun },
];
export const selectComfortIdea = (state, idea) => ({ ...state, comfortIdea: idea });

const readCombination = () => { try { return JSON.parse(localStorage.getItem(COMBO_KEY) || "null"); } catch { return null; } };
const saveCombination = (value) => { try { localStorage.setItem(COMBO_KEY, JSON.stringify(value)); } catch { /* private mode */ } };
function useBumpState() {
  const restored = useMemo(() => {
    const active = getActiveFlagship();
    return active?.interventionId === ID ? { ...INITIAL, ...active.experience } : null;
  }, []);
  const [state, setState] = useState(restored || INITIAL);
  useEffect(() => {
    const { proud, grateful, lookingForward, customTask, task, areaAction, nextActivity, pairing, reward, comfortIdea, customComfortIdea, ...safeState } = state;
    saveActiveFlagship({ interventionId: ID, experience: safeState, away: ["connection", "mission", "areaAction", "nextPlan"].includes(state.scene) });
  }, [state]);
  return [state, setState];
}
function Engine({ level, progress, pulse, stage }) {
  const peak = 132 - level * 70;
  const path = `M -20 150 C 80 150, 100 ${peak}, 190 ${peak} S 300 150, 420 150`;
  return <div className="happy-bump-engine" aria-hidden="true"><svg viewBox="0 0 400 210" preserveAspectRatio="none"><defs><linearGradient id="bump-line"><stop stopColor="var(--bump-mint)" /><stop offset=".55" stopColor="var(--bump-light)" /><stop offset="1" stopColor="var(--bump-gold)" /></linearGradient></defs><motion.path className="happy-bump-line" d={path} initial={{ pathLength: .08 }} animate={{ pathLength: progress }} transition={{ duration: 1.1 }} />{Array.from({ length: 12 }, (_, i) => <circle key={i} className={`happy-bump-node ${i < stage ? "is-lit" : ""}`} cx={22 + i * 32} cy={peak} r={i < stage ? 3 : 1.8} />)}<motion.circle className="happy-bump-spark" cx="190" cy={peak} r="5" animate={pulse ? { scale: [1, 1.5, 1] } : { scale: 1 }} transition={{ duration: 2.2, repeat: Infinity }} /></svg></div>;
}
function Copy({ title, body, step, children, compact = false, className = "" }) { return <motion.section key={title} initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -8 }} className={`happy-bump-copy ${compact ? "happy-bump-copy--compact" : ""} ${className}`}>{step && <p className="happy-bump-step">Step {step} of 11</p>}<h1 tabIndex="-1">{title}</h1>{body && <p className="happy-bump-body">{body}</p>}{children}</motion.section>; }
function Primary({ children, ...props }) { return <button className="happy-bump-primary" data-sfx="select" {...props}>{children}</button>; }
function Option({ children, selected, ...props }) { return <button className={`happy-bump-option ${selected ? "is-selected" : ""}`} aria-pressed={selected} {...props}>{children}</button>; }
function Suggestions({ items, value, onSelect, label }) { return <div className="happy-bump-suggestion-rail" role="group" aria-label={label}>{items.map((item) => <button type="button" className={value === item ? "is-selected" : ""} key={item} onClick={() => { hapticPattern([6]); onSelect(item); }}>{value === item && <Check className="h-3.5 w-3.5" />}{item}</button>)}</div>; }
function TextChoice({ label, value, onChange, suggestions, onFocus, voice = false }) {
  const dictation = useVoiceDictation({ onResult: onChange });
  const showMic = voice && dictation.supported;
  return <label className="happy-bump-text-choice"><span>{label}</span><div className={showMic ? "happy-bump-text-input-row" : undefined}><input maxLength="140" value={value} onFocus={onFocus} onChange={(event) => onChange(event.target.value)} />{showMic && <button type="button" className={`happy-bump-mic ${dictation.listening ? "is-listening" : ""}`} aria-pressed={dictation.listening} aria-label={dictation.listening ? "Listening, release to stop" : "Hold to speak"} onPointerDown={(event) => { event.preventDefault(); onFocus?.(); dictation.start(); }} onPointerUp={dictation.stop} onPointerLeave={dictation.stop} onPointerCancel={dictation.stop}><Mic aria-hidden="true" /></button>}</div><Suggestions items={suggestions} value={value} onSelect={onChange} label={`${label} suggestions`} /></label>;
}

export default function HappyBumpExperience({ intervention, answers, onComplete, onAttemptEvent, onExit }) {
  const { prefs } = useAccessibilityPrefs(); const [s, set] = useBumpState(); const [now, setNow] = useState(Date.now()); const saved = useMemo(readCombination, []); const lastFocus = useMemo(getLastFocus, []); const runStarted = useRef(false);
  const { speak, stop: stopVoice, preload } = useGuideVoice();
  const narrationAvailable = !answers?.noAudio && !answers?.discreet;
  const [narrationOn, setNarrationOn] = useState(() => narrationAvailable && answers?.audio === "yes");
  const voice = useMemo(() => ({ ...voiceFor("lift"), rate: 1, leadMs: 0 }), []);
  const stage = STAGE[s.scene] || 1; const elapsed = s.startedAt && !s.paused ? s.elapsedBeforePause + (now - s.startedAt) / 1000 : s.elapsedBeforePause; const progress = Math.min(1, elapsed / DURATION_SECONDS); const area = AREAS.find((item) => item.id === s.lifeArea); const lastFocusArea = lastFocus ? AREAS.find((item) => item.id === lastFocus.lifeArea) : null;
  useEffect(() => { if (!s.runId && !runStarted.current) { runStarted.current = true; set((value) => ({ ...value, runId: startBumpRun() })); } else if (s.runId) recordBumpScene(s.runId, s.scene); }, [s.runId, s.scene]);
  useEffect(() => { if (!["move", "connection"].includes(s.scene) || s.paused) return undefined; setNow(Date.now()); const timer = window.setInterval(() => setNow(Date.now()), 500); return () => window.clearInterval(timer); }, [s.scene, s.paused]);
  useEffect(() => {
    if (!narrationOn) return;
    Object.values(HAPPY_BUMP_NARRATION).forEach((line) => preload(line, voice));
  }, [narrationOn, preload, voice]);
  useEffect(() => {
    if (!narrationOn || s.paused) { stopVoice(); return undefined; }
    const line = HAPPY_BUMP_NARRATION[s.scene];
    if (line) speak(line, voice);
    return stopVoice;
  }, [narrationOn, s.paused, s.scene, speak, stopVoice, voice]);
  useEffect(() => () => stopVoice(), [stopVoice]);
  const go = (scene, values = {}) => set((value) => ({ ...value, ...values, scene }));
  const pauseNarrationForInput = () => stopVoice();
  const pause = () => set((value) => value.paused ? { ...value, paused: false, startedAt: Date.now() } : { ...value, paused: true, elapsedBeforePause: elapsed, startedAt: null });
  const open = (href, connection) => { stopVoice(); set((value) => ({ ...value, connection })); if (typeof window !== "undefined") window.location.assign(href); };
  const messenger = () => { set((value) => ({ ...value, connection: "messenger" })); const app = "fb-messenger://"; if (window.Capacitor?.isNativePlatform?.()) window.open(app, "_system"); else { const fallback = window.setTimeout(() => { if (document.visibilityState === "visible") window.open("https://www.messenger.com/", "_blank", "noopener,noreferrer"); }, 900); window.addEventListener("pagehide", () => window.clearTimeout(fallback), { once: true }); window.location.assign(app); } };
  const complete = () => { playComplete(); hapticPattern([10, 50, 14, 65, 20]); rememberFlagshipEvent({ interventionId: ID, completed: true, worthwhile: s.current >= s.baseline, options: { context: s.environment, contactLevel: s.connection, actionSize: "micro", lifeArea: s.lifeArea, nextMode: s.nextMode, shift: s.current - s.baseline } }); clearActiveFlagship(ID); onAttemptEvent?.({ interventionId: ID, mechanism: intervention.mechanism, action: "completed", completedPercentage: 1, timestamp: Date.now() }); onComplete?.({ interventionId: ID, skipReflection: true, outcome: { start: s.baseline, end: s.current, shift: s.current - s.baseline } }); };
  const nextPlanReady = s.nextMode === "productive" ? s.nextActivity.trim() && s.pairing.trim() && s.reward.trim() : s.nextActivity.trim() && s.senses.length;
  const toggleSense = (sense) => set((value) => ({ ...value, activeSense: sense, senses: value.senses.includes(sense) ? value.senses.filter((item) => item !== sense) : [...value.senses, sense] }));
  const shift = s.current - s.baseline;
  const bumpsThisWeek = useMemo(() => (s.scene === "complete" ? getBumpsCompletedThisWeek() : 0), [s.scene]);
  const walkProgress = Math.min(1, elapsed / DURATION_SECONDS);
  const backTarget = s.scene === "win" ? (s.environment === "stretch" ? "environment" : "connection") : (BACK[s.scene] || "arrival");
  const moved = s.environment === "door" || s.environment === "block" || s.environment === "stretch";
  const completedItems = useMemo(() => {
    if (s.scene !== "complete") return [];
    const items = [];
    if (s.hydrated) items.push({ Icon: Droplets, text: "Had some water" });
    if (s.aired) items.push({ Icon: Sun, text: "Got some air or light" });
    if (s.environment === "door" || s.environment === "block") items.push({ Icon: Footprints, text: "Went for a walk" });
    else if (s.environment === "stretch") items.push({ Icon: Sun, text: "Stretched instead of staying still" });
    if (s.connection && s.connection !== "skipped") items.push({ Icon: MessageCircle, text: "Reached out to someone" });
    if (s.task) items.push({ Icon: Check, text: `Finished: ${s.task}` });
    if (s.areaAction) items.push({ Icon: Sparkles, text: `Planned: ${s.areaAction}` });
    const mode = MODE_CHOICES.find((item) => item.id === s.nextMode);
    if (mode) items.push({ Icon: mode.Icon, text: `Chose ${mode.label.toLowerCase()} time next` });
    return items.length ? items : [{ Icon: Check, text: "Showed up for yourself" }];
  }, [s.scene, s.hydrated, s.aired, s.environment, s.connection, s.task, s.areaAction, s.nextMode]);
  return <InterventionControlShell id={ID} goal="Lift" title="The Happy Bump" stage={stage} stages={11} onBack={s.scene === "arrival" ? onExit : () => go(backTarget)} onExit={() => { stopVoice(); onExit(); }} active={["move", "connection"].includes(s.scene)} paused={s.paused} onPause={pause} audioOn={narrationOn} onAudio={narrationAvailable ? () => setNarrationOn((value) => !value) : undefined} onDifferent={() => { recordDislike(ID, intervention.mechanism); stopVoice(); onExit(); }} bottomActionLabel={s.scene === "complete" ? undefined : "Skip ahead"} onBottomAction={() => go(SKIP[s.scene] || s.scene)} dark accent="var(--bump-light)" className={`happy-bump happy-bump-stage-${stage}`} field={<><div className="happy-bump-ambient" /><div className="happy-bump-grain" /><Engine level={(stage - 1) / 10} stage={stage} progress={["move", "connection"].includes(s.scene) ? Math.max(.45, progress) : Math.min(1, stage / 11 + .12)} pulse={!prefs.reducedMotion && stage > 1 && stage < 11} /></>}>
    <div className="happy-bump-content"><AnimatePresence mode="wait">
      {s.scene === "arrival" && <Copy title="Shift your state." body="Eleven short steps, about 10–15 minutes. No motivation required.">{saved && <button className="happy-bump-saved" onClick={() => go("baseline", saved)}>Run my saved bump <Play className="h-4 w-4" /></button>}<Primary onClick={() => go("baseline")}>Start</Primary></Copy>}
      {s.scene === "baseline" && <Copy step={1} title="Where are you at right now?" body="Move the curve until it feels about right."><input aria-label="Starting energy from flat to more alive" className="happy-bump-slider" type="range" min="0" max="10" value={s.baseline} onChange={(event) => set((value) => ({ ...value, baseline: Number(event.target.value) }))} /><div className="happy-bump-scale"><span>Flat</span><span>More alive</span></div><Primary onClick={() => go("hydrate")}>That's where I am</Primary></Copy>}
      {s.scene === "hydrate" && <Copy step={2} title="Drink a glass of water." body="Take a moment and finish what feels comfortable."><Droplets className="happy-bump-feature-icon" /><Primary onClick={() => go("window", { hydrated: true })}>I've had some water</Primary></Copy>}
      {s.scene === "window" && <Copy step={3} title="Open a window or step into some light." body="Thirty seconds. Feel the air, notice the light, take a slow breath."><Sun className="happy-bump-feature-icon" /><Primary onClick={() => go("environment", { aired: true })}>I did that</Primary></Copy>}
      {s.scene === "environment" && <Copy step={4} title="Okay, we're going for a walk." body="You've done two small things already. Step outside for a couple of minutes."><div className="happy-bump-grid"><Option selected={s.environment === "door"} onClick={() => go("move", { environment: "door", elapsedBeforePause: 0, startedAt: Date.now(), paused: false })}><DoorOpen />Walk to the door and back</Option><Option selected={s.environment === "block"} onClick={() => go("move", { environment: "block", elapsedBeforePause: 0, startedAt: Date.now(), paused: false })}><Footprints />Walk around the block</Option></div><button className="happy-bump-quiet" onClick={() => go("win", { environment: "stretch" })}>I'll walk inside instead</button></Copy>}
      {s.scene === "move" && <Copy step={4} title={s.paused ? "Paused." : "Take a short walk."} body={s.paused ? "Continue when it fits." : "You can connect with someone while you walk."}><div className="happy-bump-walk-ring" style={{ "--walk-progress": `${walkProgress * 360}deg` }}><strong>{Math.floor(elapsed / 60)}:{String(Math.floor(elapsed % 60)).padStart(2, "0")}</strong><span>of 5:00</span></div><Primary onClick={() => go("connection")}>Connect while I walk</Primary></Copy>}
      {s.scene === "connection" && <Copy step={5} compact title="Reach out to someone." body="One genuine signal is enough."><div className="happy-bump-grid happy-bump-grid--connection"><Option selected={s.connection === "message"} onClick={() => open("sms:", "message")}><MessageCircle />Text message</Option><Option selected={s.connection === "messenger"} onClick={messenger}><Send />Facebook Messenger</Option><Option selected={s.connection === "voice-note"} onClick={() => open("sms:", "voice-note")}><Mic />Voice note</Option><Option selected={s.connection === "call"} onClick={() => open("tel:", "call")}><Phone />Phone call</Option><Option selected={s.connection === "skipped"} onClick={() => set((value) => ({ ...value, connection: "skipped" }))}><SkipForward />Skip connecting</Option></div>{s.connection && <Primary onClick={() => go("win", { elapsedBeforePause: elapsed, startedAt: null, paused: false })}>I'm back from my walk</Primary>}</Copy>}
      {s.scene === "win" && <Copy step={6} compact title="One small win." body="Pick something small enough to finish now."><div className="happy-bump-task-list">{TASKS.map((task) => <Option selected={s.task === task} key={task} onClick={() => set((value) => ({ ...value, task, customTask: "" }))}>{task}</Option>)}</div><TextChoice label="Or name a tiny finish" value={s.customTask} onFocus={pauseNarrationForInput} onChange={(customTask) => set((value) => ({ ...value, customTask, task: null }))} suggestions={[]} /><Primary disabled={!s.task && !s.customTask.trim()} onClick={() => go("mission", { task: s.task || s.customTask.trim() })}>Make it my one mission</Primary></Copy>}
      {s.scene === "mission" && <Copy step={6} title={s.task} body="Nothing else belongs in this moment."><div className="happy-bump-mission-orbit"><strong>NOW</strong></div><Primary onClick={() => { playSelect(); hapticPattern([10, 45, 14]); go("proud"); }}><Check />Done</Primary><button className="happy-bump-quiet" onClick={() => go("proud")}>I made an honest start</button></Copy>}
      {["proud", "grateful", "anticipate"].includes(s.scene) && <Copy step={7} compact title={s.scene === "proud" ? "What are you proud of?" : s.scene === "grateful" ? "What are you grateful for?" : "What are you looking forward to?"} body="Choose whatever feels true right now. Skipping is okay."><TextChoice label="Your words" value={s.scene === "anticipate" ? s.lookingForward : s[s.scene]} onFocus={pauseNarrationForInput} onChange={(value) => set((current) => ({ ...current, [s.scene === "anticipate" ? "lookingForward" : s.scene]: value }))} suggestions={REFLECTIONS[s.scene]} voice /><Primary onClick={() => go(s.scene === "proud" ? "grateful" : s.scene === "grateful" ? "anticipate" : "lifeArea")}>Continue</Primary></Copy>}
      {s.scene === "lifeArea" && <Copy step={8} compact title="What deserves a little attention next?" body="Six parts of wellbeing.">{lastFocusArea && <div className="happy-bump-callback" role="note"><Sparkles aria-hidden="true" /><p>Last time you focused on <strong>{lastFocusArea.label}</strong>{lastFocus.areaAction ? ` — ${lastFocus.areaAction}` : ""}.</p><button type="button" onClick={() => { hapticPattern([6]); set((value) => ({ ...value, lifeArea: lastFocusArea.id, areaAction: lastFocus.areaAction || "" })); go(lastFocus.areaAction ? "nextMode" : "areaAction"); }}>Try that again</button></div>}<div className="happy-bump-life-grid">{AREAS.map(({ id, label, Icon }) => <Option key={id} selected={s.lifeArea === id} onClick={() => set((value) => ({ ...value, lifeArea: id, areaAction: "" }))}><Icon />{label}</Option>)}</div><Primary disabled={!s.lifeArea} onClick={() => go("areaAction")}>Choose a small step</Primary><p className="happy-bump-low-effort-label">Low-effort path</p><button type="button" className="happy-bump-low-effort" onClick={() => { const lowArea = AREAS[0]; const lowAction = lowArea.actions[0]; hapticPattern([6]); saveLastFocus({ lifeArea: lowArea.id, areaAction: lowAction }); set((value) => ({ ...value, lifeArea: lowArea.id, areaAction: lowAction })); go("nextMode"); }}><ListChecks aria-hidden="true" /><span>{AREAS[0].actions[0]}</span><ChevronRight aria-hidden="true" /></button></Copy>}
      {s.scene === "areaAction" && area && <Copy step={8} compact title="Pick one low-effort step." body="Tap one that feels realistic, not impressive."><Suggestions items={area.actions} value={s.areaAction} onSelect={(areaAction) => set((value) => ({ ...value, areaAction }))} label={`${area.label} suggestions`} /><TextChoice label="Or name your own" value={s.areaAction} onFocus={pauseNarrationForInput} onChange={(areaAction) => set((value) => ({ ...value, areaAction }))} suggestions={[]} /><Primary disabled={!s.areaAction.trim()} onClick={() => { saveLastFocus({ lifeArea: s.lifeArea, areaAction: area.actions.includes(s.areaAction) ? s.areaAction : null }); go("nextMode"); }}>Carry it forward</Primary></Copy>}
      {s.scene === "nextMode" && <Copy step={9} compact title="What would serve you now?" body="Choose one more thing to carry this momentum into."><div className="happy-bump-mode-grid">{MODE_CHOICES.map(({ id, label, detail, Icon }) => <Option key={id} selected={s.nextMode === id} onClick={() => go("nextPlan", { nextMode: id, pairing: "", reward: "", senses: [], activeSense: null, comfortIdea: "", customComfortIdea: "" })}><Icon aria-hidden="true" /><span><strong>{label}</strong><small>{detail}</small></span></Option>)}</div></Copy>}
      {s.scene === "nextPlan" && <Copy step={9} compact className="happy-bump-copy--nextplan" title={s.nextMode === "productive" ? "Make effort easier to enter." : "Make the experience easy to feel."} body="Choose an activity that fits this moment."><TextChoice label="The activity" value={s.nextActivity} onFocus={pauseNarrationForInput} onChange={(nextActivity) => set((value) => ({ ...value, nextActivity }))} suggestions={PLANS[s.nextMode]} />{s.nextMode === "productive" ? <><TextChoice label="Pair it with" value={s.pairing} onFocus={pauseNarrationForInput} onChange={(pairing) => set((value) => ({ ...value, pairing }))} suggestions={["Favourite playlist", "A good coffee", "Ten-minute timer"]} /><TextChoice label="Reward after" value={s.reward} onFocus={pauseNarrationForInput} onChange={(reward) => set((value) => ({ ...value, reward }))} suggestions={["A favourite snack", "A guilt-free break", "Make a good drink"]} />{(s.nextActivity.trim() || s.pairing.trim() || s.reward.trim()) && <p className="happy-bump-contract" aria-live="polite">I'll <strong>{s.nextActivity.trim() || "___"}</strong> while I <strong>{s.pairing.trim() || "___"}</strong>, then I'll <strong>{s.reward.trim() || "___"}</strong>.</p>}</> : <div className="happy-bump-comfort"><div className="happy-bump-senses" role="group" aria-label="Choose a sense for a little comfort">{Object.entries(SENSE_COMFORT).map(([sense, { Icon }]) => <Option key={sense} selected={s.senses.includes(sense)} onClick={() => toggleSense(sense)} aria-describedby={s.activeSense === sense ? "happy-bump-sense-ideas" : undefined}><Icon aria-hidden="true" />{sense}</Option>)}</div><AnimatePresence mode="wait">{s.activeSense && <motion.section key={s.activeSense} id="happy-bump-sense-ideas" className="happy-bump-sense-ideas" aria-live="polite" aria-labelledby="happy-bump-sense-ideas-title" initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -4 }}><h2 id="happy-bump-sense-ideas-title">{s.activeSense} comfort ideas</h2><p>Choose one that feels gentle and available.</p><div>{SENSE_COMFORT[s.activeSense].ideas.map((idea) => <button type="button" key={idea} aria-pressed={s.comfortIdea === idea} className={s.comfortIdea === idea ? "is-selected" : ""} onClick={() => { hapticPattern([6]); set((value) => selectComfortIdea(value, idea)); }}>{s.comfortIdea === idea && <Check aria-hidden="true" />}{idea}</button>)}</div></motion.section>}</AnimatePresence><label className="happy-bump-comfort-field"><span>Your own soothing idea</span><input maxLength="140" value={s.customComfortIdea} onFocus={pauseNarrationForInput} onChange={(event) => set((value) => ({ ...value, customComfortIdea: event.target.value }))} placeholder="For example, sit with a soft blanket" /><small>{s.customComfortIdea.length}/140</small></label></div>}<Primary disabled={!nextPlanReady} onClick={() => go("rerate")}>That's my next move</Primary></Copy>}
      {s.scene === "rerate" && <Copy step={10} title="Where are you now?" body="No result is the right result. Take an honest read."><div className="happy-bump-rerate-track"><div className="happy-bump-then-now"><span className="happy-bump-then-now-then" style={{ left: `${Math.min(100, Math.max(0, s.baseline * 10))}%` }}>Then {s.baseline}</span><span className="happy-bump-then-now-now" style={{ left: `${Math.min(100, Math.max(0, s.current * 10))}%` }}>Now {s.current}</span></div><input aria-label="Current energy from flat to more alive" className="happy-bump-slider" type="range" min="0" max="10" value={s.current} onChange={(event) => set((value) => ({ ...value, current: Number(event.target.value) }))} /></div><div className="happy-bump-scale"><span>Flat</span><span>More alive</span></div><Primary onClick={() => { hapticPattern([8, 55, 12]); go("reveal"); }}>Show me the bump</Primary></Copy>}
      {s.scene === "reveal" && <Copy step={10} title={shift > 0 ? `A ${shift}-step bump.` : shift === 0 ? "The line held." : "You still moved."} body={shift > 0 ? "Not a whole new day. A real change in this moment." : "The outcome did not need to change for the actions to count."}><div className="happy-bump-shift"><span style={{ width: `${Math.max(4, s.current * 10)}%` }} /><strong>Then {s.baseline} · Now {s.current}</strong></div><Primary onClick={() => go("complete")}>See what you built</Primary></Copy>}
      {s.scene === "complete" && <Copy compact title="That's the bump." body="Small inputs. Real movement. A direction to keep."><div className="happy-bump-reveal-card"><p className="happy-bump-reveal-shift"><span>{s.baseline}</span><span aria-hidden="true"> → </span><strong>Now {s.current}</strong></p><ul className="happy-bump-verbs">{completedItems.map(({ Icon, text }) => <li key={text}><Icon />{text}</li>)}</ul><p className="happy-bump-reveal-quote">{moved ? "\"You moved when you felt flat. That's the win.\"" : "\"You showed up, even when it was hard. That's the win.\""}</p></div>{bumpsThisWeek > 0 && <p className="happy-bump-reveal-streak">{bumpsThisWeek} bump{bumpsThisWeek === 1 ? "" : "s"} completed this week</p>}{s.saved ? <p className="happy-bump-saved-confirmation"><Check />Your combination is saved.</p> : <button className="happy-bump-saved" onClick={() => { saveCombination({ environment: s.environment, connection: s.connection, lifeArea: s.lifeArea, nextMode: s.nextMode }); set((value) => ({ ...value, saved: true })); }}>Save my bump</button>}<Primary onClick={complete}>Done</Primary></Copy>}
    </AnimatePresence></div>
  </InterventionControlShell>;
}
