import { useProgressGate } from '@/hooks/useProgressGate';
import { clearPracticeDraft } from '@/lib/practiceInteraction';
import PracticeIllustration from '@/components/journey/PracticeIllustration';
import '@/styles/practice-editorial.css';
import PracticeCheckpoint from '@/components/journey/PracticeCheckpoint';
import { practiceEvent as earned } from '@/lib/practiceCheckpoints';
import { useJourneyScreenHistory } from '@/hooks/useJourneyScreenHistory';
import JourneyTakeaway from '@/components/journey/JourneyTakeaway';
import {happyBumpTakeaway} from '@/lib/confirmedJourneyTakeaway';
import { useEffect, useMemo, useRef, useState } from "react";
import { AnimatePresence, motion, MotionConfig } from "framer-motion";
import { BookOpen, Check, ChevronRight, Compass, CupSoda, DoorOpen, Ear, Eye, Flower2, Footprints, Hand, Heart, ListChecks, MessageCircle, Mic, Phone, Play, Send, Sparkles, Sprout, Sun, Users, Wallet } from "lucide-react";
import InterventionControlShell from "@/components/InterventionControlShell";
import { useAccessibilityPrefs } from "@/hooks/useAccessibilityPrefs";
import { getActiveFlagship, rememberFlagshipEvent, saveActiveFlagship } from "@/lib/flagshipMemory";
import { hapticPattern, playComplete, playSelect } from "@/lib/feedback";
import { recordBumpScene, startBumpRun } from "@/lib/happyBumpFunnel";
import { getLastFocus, saveLastFocus } from "@/lib/happyBumpMemory";
import { recordDislike } from "@/lib/preferences";
import { HAPPY_BUMP_NARRATION } from "@/lib/happyBumpNarration";
import { useGuideVoice } from "@/hooks/useGuideVoice";
import { useVoiceDictation } from "@/hooks/useVoiceDictation";
import { voiceFor } from "@/lib/spoken";
import { WALK_MINUTES, HELPFULNESS, energyOutcome, walkSeconds, walkElapsed, toggleWalkPause, leaveWalk, restoreBumpState, bumpRecap } from "@/lib/happyBumpState";
import "@/styles/happy-bump.css";

const ID = "happyBump";
const COMBO_KEY = "mentation.happyBump.combination.v1";
const STAGE = { arrival: 1, baseline: 1, hydrate: 2, window: 3, walkDuration: 4, environment: 4, move: 4, connection: 5, contactResult: 5, win: 6, mission: 6, proud: 7, reflection: 7, grateful: 7, anticipate: 7, lifeArea: 8, areaAction: 8, nextMode: 9, nextPlan: 9, pairing: 9, reward: 9, comfortSense: 9, comfortIdea: 9, rerate: 10, reveal: 10, helpfulness: 11, complete: 11 };
const BACK = { baseline: "arrival", hydrate: "baseline", window: "hydrate", walkDuration: "window", environment: "walkDuration", move: "environment", connection: "move", contactResult: "connection", win: "environment", mission: "win", proud: "mission", grateful: "proud", anticipate: "grateful", reflection: "mission", lifeArea: "reflection", areaAction: "lifeArea", nextMode: "areaAction", nextPlan: "nextMode", pairing: "nextPlan", reward: "pairing", comfortSense: "nextPlan", comfortIdea: "comfortSense", rerate: "nextPlan", helpfulness: "rerate", reveal: "rerate", complete: "reveal" };
const SKIP = { arrival: "baseline", baseline: "hydrate", hydrate: "window", window: "walkDuration", walkDuration: "connection", environment: "connection", move: "win", connection: "win", contactResult: "win", win: "proud", mission: "proud", proud: "lifeArea", reflection: "lifeArea", grateful: "anticipate", anticipate: "lifeArea", lifeArea: "nextMode", areaAction: "nextMode", nextMode: "rerate", nextPlan: "rerate", pairing: "rerate", reward: "rerate", comfortSense: "rerate", comfortIdea: "rerate", rerate: "helpfulness", helpfulness: "complete", reveal: "complete" };
const INITIAL = { scene: "arrival", version: 2, baseline: null, current: null, helpfulness: null, walkMinutes: 3, walkStatus: null, taskStatus: null, contactStatus: null, reflectionKind: "proud", hydrated: false, aired: false, environment: null, connection: null, task: null, customTask: "", elapsedBeforePause: 0, startedAt: null, paused: false, proud: "", grateful: "", lookingForward: "", lifeArea: null, areaAction: "", nextMode: null, nextActivity: "", pairing: "", reward: "", senses: [], activeSense: null, comfortIdea: "", customComfortIdea: "", saved: false, runId: null };
const TASKS = ["Put one thing away", "Reply to one message", "Open the curtains", "Clear one small surface"];
const REFLECTIONS = { proud: ["I got out of bed", "I kept going", "I moved my body", "I showed up", "I tried again"], grateful: ["Someone who cares", "A safe place", "A small comfort", "Music I love", "Fresh air"], anticipate: ["A favourite meal", "Seeing someone", "Resting later", "Getting outside", "A quiet evening"] };
const AREAS = [{ id: "relationships", label: "Relationships", Icon: Users, actions: ["Send a thank-you message", "Ask someone how they are", "Plan a short catch-up"] }, { id: "health", label: "Physical health", Icon: Heart, actions: ["Stretch for two minutes", "Step outside for fresh air", "Refill tomorrow's water"] }, { id: "purpose", label: "Purpose & work", Icon: Compass, actions: ["Write the first tiny step", "Open the document", "Choose tomorrow's priority"] }, { id: "growth", label: "Learning & growth", Icon: BookOpen, actions: ["Read two pages", "Practise for five minutes", "Choose a book to start"] }, { id: "financial", label: "Financial wellbeing", Icon: Wallet, actions: ["Check one account balance", "Set one bill reminder", "File one receipt"] }, { id: "community", label: "Community", Icon: Sprout, actions: ["Thank someone who helps", "Offer one small favour", "Choose one cause to learn about"] }];
const PLANS = { productive: ["Clear one surface", "Start the first five minutes", "Write tomorrow's top task"], enjoyable: ["Listen to an album", "Watch something funny", "Read for pleasure"], relaxing: ["Take a warm shower", "Make a warm drink", "Sit outside"] };
export const SENSE_COMFORT = Object.freeze({
  Sight: { Icon: Eye, ideas: ["Lower one bright light or close a distracting tab", "Look at a favourite photo or a calm view", "Step to a window and notice the light outside", "Put on a familiar, low-key visual you enjoy"] },
  Sound: { Icon: Ear, ideas: ["Play one familiar, gentle song", "Put on soft rain or a quiet room tone", "Take a minute somewhere with less noise", "Listen for one steady sound already nearby"] },
  Touch: { Icon: Hand, ideas: ["Wrap up in a soft layer or hold a warm mug", "Change into the most comfortable thing available", "Run warm water over your hands", "Rest a hand over your chest or on a soft surface"] },
  Smell: { Icon: Flower2, ideas: ["Light a candle if it is safe to do so", "Spray a favourite fragrance", "Open a window for fresh air", "Make a comforting tea and notice its scent"] },
  Taste: { Icon: CupSoda, ideas: ["Make a comforting tea or cold drink", "Have one small favourite snack slowly", "Add a familiar flavour to water", "Choose something warm or cool that feels pleasant"] },
});
const MODE_CHOICES = [
  { id: "productive", label: "Productive", detail: "Make one next step easier", Icon: Compass },
  { id: "enjoyable", label: "Enjoyable", detail: "Choose a little pleasure", Icon: Heart },
  { id: "relaxing", label: "Relaxing", detail: "Settle into comfort", Icon: Sun },
];
export const selectComfortIdea = (state, idea) => ({ ...state, comfortIdea: idea });

const readCombination = () => { try { return JSON.parse(localStorage.getItem(COMBO_KEY) || "null"); } catch { return null; } };
const saveCombination = (value) => { try { localStorage.setItem(COMBO_KEY, JSON.stringify(value)); return true; } catch { return false; } };
function useBumpState() {
  const restored = useMemo(() => {
    const active = getActiveFlagship();
    return active?.interventionId === ID ? restoreBumpState(INITIAL, active.experience) : null;
  }, []);
  const [state, setState] = useState(restored || INITIAL);
  const [draftOk,setDraftOk] = useState(true);
  useEffect(() => {
    setDraftOk(saveActiveFlagship({ interventionId: ID, experience: state, away: ["connection", "mission", "areaAction", "nextPlan"].includes(state.scene) }));
  }, [state]);
  return [state, setState, draftOk];
}
function Engine({ level, progress, pulse, stage }) {
  const peak = 132 - level * 70;
  const path = `M -20 150 C 80 150, 100 ${peak}, 190 ${peak} S 300 150, 420 150`;
  return <div className="happy-bump-engine" aria-hidden="true"><svg viewBox="0 0 400 210" preserveAspectRatio="none"><defs><linearGradient id="bump-line"><stop stopColor="var(--bump-mint)" /><stop offset=".55" stopColor="var(--bump-light)" /><stop offset="1" stopColor="var(--bump-gold)" /></linearGradient></defs><motion.path className="happy-bump-line" d={path} initial={{ pathLength: .08 }} animate={{ pathLength: progress }} transition={{ duration: 1.1 }} />{Array.from({ length: 12 }, (_, i) => <circle key={i} className={`happy-bump-node ${i < stage ? "is-lit" : ""}`} cx={22 + i * 32} cy={peak} r={i < stage ? 3 : 1.8} />)}<motion.circle className="happy-bump-spark" cx="190" cy={peak} r="5" animate={pulse ? { scale: [1, 1.5, 1] } : { scale: 1 }} transition={{ duration: 2.2, repeat: Infinity }} /></svg></div>;
}
function Copy({ title, body, step, children, compact = false, className = "" }) { return <motion.section key={title} initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -8 }} className={`happy-bump-copy ${compact ? "happy-bump-copy--compact" : ""} ${className}`}>{step && <p className="happy-bump-step">{({1:"Check in",2:"Water",3:"Light",4:"Movement",5:"Connection",6:"One small action",7:"Notice",8:"A direction",9:"Next move",10:"Check in",11:"Carry forward"})[step]}</p>}<h1 tabIndex="-1">{title}</h1>{body && <p className="happy-bump-body">{body}</p>}{children}</motion.section>; }
function Primary({ children, ...props }) { return <button className="happy-bump-primary" data-sfx="select" {...props}>{children}</button>; }
function Option({ children, selected, ...props }) { return <button className={`happy-bump-option ${selected ? "is-selected" : ""}`} aria-pressed={selected} {...props}>{children}</button>; }
function Suggestions({ items, value, onSelect, label }) { return <div className="happy-bump-suggestion-rail" role="group" aria-label={label}>{items.map((item) => <button type="button" className={value === item ? "is-selected" : ""} key={item} onClick={() => { hapticPattern([6]); onSelect(item); }}>{value === item && <Check className="h-3.5 w-3.5" />}{item}</button>)}</div>; }
function TextChoice({ label, value, onChange, suggestions, onFocus, voice = false }) {
  const dictation = useVoiceDictation({ onResult: onChange });
  const showMic = voice && dictation.supported;
  return <label className="happy-bump-text-choice"><span>{label}</span><div className={showMic ? "happy-bump-text-input-row" : undefined}><input aria-label={label} maxLength="140" value={value} onFocus={onFocus} onChange={(event) => onChange(event.target.value)} />{showMic && <button type="button" className={`happy-bump-mic ${dictation.listening ? "is-listening" : ""}`} aria-pressed={dictation.listening} aria-label={dictation.listening ? "Listening, release to stop" : "Hold to speak"} onPointerDown={(event) => { event.preventDefault(); onFocus?.(); dictation.start(); }} onPointerUp={dictation.stop} onPointerLeave={dictation.stop} onPointerCancel={dictation.stop}><Mic aria-hidden="true" /></button>}</div><Suggestions items={suggestions} value={value} onSelect={onChange} label={`${label} suggestions`} /></label>;
}

export default function HappyBumpExperience({ intervention, answers, onComplete, onAttemptEvent, onExit }) {
  const acceptProgress = useProgressGate();
  const [finishError,setFinishError] = useState(false);
  const { prefs } = useAccessibilityPrefs(); const [s, set, draftOk] = useBumpState(); const [now, setNow] = useState(Date.now()); const saved = useMemo(readCombination, []); const lastFocus = useMemo(getLastFocus, []); const runStarted = useRef(false); const completionSent = useRef(false);
  useJourneyScreenHistory(ID,s.scene,scene => {if (STAGE[scene]) set(value=>({...value,scene,...(value.scene === 'move' ? {elapsedBeforePause:walkElapsed(value),startedAt:null,paused:true} : {}),...(scene === 'move' ? {paused:true,startedAt:null} : {})}));});
  const { speak, stop: stopVoice, preload } = useGuideVoice();
  const narrationAvailable = !answers?.noAudio && !answers?.discreet;
  const [narrationOn, setNarrationOn] = useState(() => narrationAvailable && answers?.audio === "yes");
  const voice = useMemo(() => ({ ...voiceFor("lift"), rate: 1, leadMs: 0 }), []);
  const stage = STAGE[s.scene] || 1; const elapsed = walkElapsed(s, now); const progress = Math.min(1, elapsed / walkSeconds(s)); const area = AREAS.find((item) => item.id === s.lifeArea); const lastFocusArea = lastFocus ? AREAS.find((item) => item.id === lastFocus.lifeArea) : null;
  useEffect(() => { if (!s.runId && !runStarted.current) { runStarted.current = true; set((value) => ({ ...value, runId: startBumpRun() })); } else if (s.runId) recordBumpScene(s.runId, s.scene); }, [s.runId, s.scene]);
  useEffect(() => { if (s.scene !== "move" || s.paused) return undefined; setNow(Date.now()); const timer = window.setInterval(() => setNow(Date.now()), 500); return () => window.clearInterval(timer); }, [s.scene, s.paused]);
  useEffect(() => {
    if (!narrationOn) return;
    Object.values(HAPPY_BUMP_NARRATION).forEach((line) => preload(line, voice));
  }, [narrationOn, preload, voice]);
  useEffect(() => {
    if (!narrationOn || s.paused) { stopVoice(); return undefined; }
    const line = HAPPY_BUMP_NARRATION[s.scene === "reflection" ? s.reflectionKind : s.scene];
    if (line) speak(line, voice);
    return stopVoice;
  }, [narrationOn, s.paused, s.scene, s.reflectionKind, speak, stopVoice, voice]);
  useEffect(() => () => stopVoice(), [stopVoice]);
  const go = (scene, values = {}) => { if (!acceptProgress()) return; set((value) => ({ ...value, ...(value.scene === "move" && scene !== "move" ? { elapsedBeforePause: walkElapsed(value), startedAt: null, paused: false } : {}), ...values, scene })); };
  const skip = () => {
    if (["move", "environment", "walkDuration"].includes(s.scene)) { set((value) => leaveWalk(value, "skipped")); return; }
    if (s.scene === "mission" || s.scene === "win") { go("proud", { taskStatus: "skipped" }); return; }
    if (s.scene === "baseline") { go("hydrate", { baseline:null }); return; }
    if (s.scene === "proud") { go("lifeArea"); return; }
    if (s.scene === "rerate") { go("helpfulness", { current: null }); return; }
    go(SKIP[s.scene] || s.scene);
  };
  const pauseNarrationForInput = () => stopVoice();
  const pause = () => set((value) => toggleWalkPause(value));
  const open = (href, connection) => { stopVoice(); set((value) => ({ ...value, connection, scene:"contactResult" })); if (typeof window !== "undefined") window.location.assign(href); };
  const messenger = () => { set((value) => ({ ...value, connection: "messenger", scene:"contactResult" })); const app = "fb-messenger://"; if (window.Capacitor?.isNativePlatform?.()) window.open(app, "_system"); else { const fallback = window.setTimeout(() => { if (document.visibilityState === "visible") window.open("https://www.messenger.com/", "_blank", "noopener,noreferrer"); }, 900); window.addEventListener("pagehide", () => window.clearTimeout(fallback), { once: true }); window.location.assign(app); } };
  const complete = () => {
    if (completionSent.current) return;
    if (!clearPracticeDraft(undefined,ID)) {setFinishError(true);return;}
    completionSent.current = true;
    const outcome = energyOutcome(s);
    playComplete(); hapticPattern([10, 50, 14, 65, 20]);
    rememberFlagshipEvent({ interventionId: ID, completed: true,
      ...(s.helpfulness === "helpful" ? { worthwhile: true } : ["same", "worse"].includes(s.helpfulness) ? { worthwhile: false } : {}),
      options: { context: s.environment, contactLevel: s.contactStatus || "not_confirmed", actionSize: s.taskStatus || "not_confirmed", lifeArea: s.lifeArea, nextMode: s.nextMode, ...(outcome.shift == null ? {} : { energyShift: outcome.shift }), helpfulness: s.helpfulness || "not_answered" } });
    onAttemptEvent?.({ interventionId: ID, mechanism: intervention.mechanism, action: "completed", completedPercentage: 1, helpfulness:s.helpfulness, timestamp: Date.now() });
    onComplete?.({ interventionId: ID, skipReflection: true, outcome });
  };
  const nextPlanReady = s.nextActivity.trim();
  const toggleSense = (sense) => set((value) => ({ ...value, activeSense: sense, senses: value.senses.includes(sense) ? value.senses.filter((item) => item !== sense) : [...value.senses, sense] }));
  const outcome = energyOutcome(s);
  const walkProgress = progress;
  const backTarget = s.scene === "win" ? "connection"
    : s.scene === "connection" && !s.environment ? "environment"
    : s.scene === "proud" && !s.task ? "win"
    : s.scene === "lifeArea" ? "reflection"
    : s.scene === "nextMode" && !s.lifeArea ? "lifeArea"
    : s.scene === "rerate" && s.rerateOrigin ? s.rerateOrigin : s.scene === "rerate" && !s.nextMode ? "nextMode"
    : s.scene === "complete" ? "helpfulness" : (BACK[s.scene] || "arrival");
  const completedItems = bumpRecap(s);
  return <MotionConfig reducedMotion={prefs.reducedMotion ? "always" : "user"}><InterventionControlShell id={ID} goal="Lift" title="The Happy Bump" stage={stage} stages={11} onBack={s.scene === "arrival" ? onExit : () => go(backTarget, backTarget === "move" ? { paused:true, startedAt:null } : {})} onExit={() => { stopVoice(); onExit(); }} active={s.scene === "move"} paused={s.paused} onPause={s.scene === "move" ? pause : undefined} audioOn={narrationOn} onAudio={narrationAvailable ? () => setNarrationOn((value) => !value) : undefined} onDifferent={() => { recordDislike(ID, intervention.mechanism); stopVoice(); onExit(); }} bottomActionLabel={s.scene === "complete" ? undefined : "Skip ahead"} onBottomAction={skip} dark accent="var(--bump-light)" className={`happy-bump happy-bump-stage-${stage}`} field={<><div className="happy-bump-ambient" /><div className="happy-bump-grain" /><Engine level={(stage - 1) / 10} stage={stage} progress={s.scene === "move" ? Math.max(.45, progress) : Math.min(1, stage / 11 + .12)} pulse={!prefs.reducedMotion && stage > 1 && stage < 11} /></>}>
    <div className="happy-bump-content">{finishError && <p role="alert">Your draft could not be cleared. Your words are still here. Try Done again.</p>}{!draftOk && <p role="alert" className="happy-bump-body">Your draft could not be saved. Keep this page open; refreshing may lose your choices.</p>}<AnimatePresence mode="wait">
      {s.scene === "arrival" && <Copy title="Start with one small thing." body="Water, light, a short walk. Follow what feels useful and skip the rest.">{saved && <button className="happy-bump-saved" onClick={() => go("baseline", { ...saved, connection: null })}>Run my saved bump <Play className="h-4 w-4" /></button>}<Primary onClick={() => go("baseline")}>Start</Primary><details className="happy-bump-privacy"><summary>Your private draft</summary><p>Your words and choices stay on this device for 24 hours after your last change. Finish clears the draft.</p></details></Copy>}
      {s.scene === "baseline" && <Copy step={1} title="How is your energy?" body="Energy means how activated or tired you feel. Mood and distress are separate check-ins after this reset."><input aria-label="Energy from flat to more alive" className="happy-bump-slider" type="range" min="0" max="10" value={s.baseline ?? 5} onChange={(event) => set((value) => ({ ...value, baseline: Number(event.target.value), baselineConfirmed:false }))} /><div className="happy-bump-scale"><span>Flat</span><span>More alive</span></div><p className="happy-bump-body">{s.baseline == null ? "Not answered · confirm the displayed rating or skip" : `Energy: ${s.baseline}/10`}</p><Primary onClick={() => go("hydrate", { baseline:s.baseline ?? 5, baselineConfirmed:true })}>Confirm energy: {s.baseline ?? 5}</Primary></Copy>}
      {s.scene === "hydrate" && <Copy step={2} title="Drink a glass of water." body="Take a moment and finish what feels comfortable."><PracticeIllustration kind="water"/><Primary onClick={() => go("window", { hydrated: true })}>I've had some water</Primary></Copy>}
      {s.scene === "window" && <Copy step={3} title="Open a window or step into some light." body="Thirty seconds. Feel the air, notice the light, take a slow breath."><PracticeIllustration kind="light"/><Primary onClick={() => go("walkDuration", { aired: true })}>I did that</Primary></Copy>}
      {s.scene === "walkDuration" && <Copy step={4} title="How long would you like to walk?" body="A minute counts. You can finish early."><div className="happy-bump-task-list">{WALK_MINUTES.map((minutes) => <Option key={minutes} selected={s.walkMinutes === minutes} onClick={() => go("environment", { walkMinutes: minutes, walkChosen:true })}>{minutes} min<ChevronRight aria-hidden="true" /></Option>)}</div></Copy>}
      {s.scene === "environment" && <Copy step={4} title="Where feels safe to walk?" body={`${s.walkMinutes} minutes, at your pace. Indoors counts.`}><div className="happy-bump-task-list">{[{id:"door", label:"To the door and back", Icon:DoorOpen}, {id:"block", label:"Around the block", Icon:Footprints}, {id:"inside", label:"Walk indoors", Icon:Footprints}].map(({id,label,Icon}) => <Option key={id} selected={s.environment === id} onClick={() => go("move", { environment:id, walkStatus:null, elapsedBeforePause:0, startedAt:Date.now(), paused:false })}><Icon />{label}<ChevronRight aria-hidden="true" /></Option>)}</div></Copy>}
      {s.scene === "move" && <Copy step={4} title={s.paused ? "Paused." : "Take your walk at your pace."} body="You can finish early. Pause before using your phone."><div className="happy-bump-walk-ring" style={{ "--walk-progress": `${walkProgress * 360}deg` }}><strong aria-label="Walk elapsed">{Math.floor(elapsed / 60)}:{String(Math.floor(elapsed % 60)).padStart(2, "0")}</strong><span>of {s.walkMinutes}:00</span></div><Primary onClick={() => set((value) => leaveWalk(value, "completed"))}>I finished my walk</Primary><button className="happy-bump-quiet" onClick={() => set((value) => leaveWalk(value, "started"))}>I took a shorter walk</button></Copy>}
      {s.scene === "connection" && <Copy step={5} title="How would you like to reach out?" body="Optional. Opening an app does not mark a conversation complete."><div className="happy-bump-task-list"><Option selected={s.connection === "message"} onClick={() => open("sms:", "message")}><MessageCircle />Text message<ChevronRight aria-hidden="true" /></Option><Option selected={s.connection === "messenger"} onClick={messenger}><Send />Facebook Messenger<ChevronRight aria-hidden="true" /></Option><Option selected={s.connection === "voice-note"} onClick={() => open("sms:", "voice-note")}><Mic />Voice note<ChevronRight aria-hidden="true" /></Option><Option selected={s.connection === "call"} onClick={() => open("tel:", "call")}><Phone />Phone call<ChevronRight aria-hidden="true" /></Option></div><button className="happy-bump-quiet" onClick={() => go("contactResult")}>I already reached out</button></Copy>}
      {s.scene === "contactResult" && <Copy step={5} title="Did you connect with someone?" body="Only record what actually happened."><div className="happy-bump-task-list"><Option selected={s.contactStatus === 'contacted'} onClick={() => go("win", { contactStatus:"contacted" })}>I sent a message or spoke to someone<ChevronRight aria-hidden="true" /></Option><Option selected={s.contactStatus === 'attempted'} onClick={() => go("win", { contactStatus:"attempted" })}>I tried, but didn't connect<ChevronRight aria-hidden="true" /></Option><Option selected={!s.contactStatus} onClick={() => go("win", { contactStatus:null })}>I did not reach out<ChevronRight aria-hidden="true" /></Option></div></Copy>}
      {s.scene === "win" && <Copy step={6} compact title="One small win." body="Pick something small enough to finish now."><div className="happy-bump-task-list">{TASKS.map((task) => <Option selected={s.task === task} key={task} onClick={() => go("mission", { task, taskStatus: null, customTask: "" })}>{task}</Option>)}</div><TextChoice label="Or name a tiny finish" value={s.customTask} onFocus={pauseNarrationForInput} onChange={(customTask) => set((value) => ({ ...value, customTask, task: null, taskStatus: null }))} suggestions={[]} /><Primary disabled={!s.task && !s.customTask.trim()} onClick={() => go("mission", { task: s.task || s.customTask.trim() })}>Make it my one mission</Primary></Copy>}
      {s.scene === "mission" && <Copy step={6} title={s.task} body="Nothing else belongs in this moment."><div className="happy-bump-mission-object"><PracticeIllustration kind="path"/><span>One action. At your pace.</span></div><Primary onClick={() => { playSelect(); hapticPattern([10, 45, 14]); go("reflection", { taskStatus: "completed", reflectionKind:"proud" }); }}><Check />Done</Primary><button className="happy-bump-quiet" onClick={() => go("reflection", { taskStatus: "started", reflectionKind:"proud" })}>I made an honest start</button></Copy>}
      {s.scene === "proud" && <Copy step={7} title="What would you like to notice?" body="Optional. There is no need to force a positive feeling."><div className="happy-bump-task-list">{[{id:"proud",label:"Something I am proud of"},{id:"grateful",label:"Something I am grateful for"},{id:"anticipate",label:"Something to look forward to"}].map(({id,label}) => <Option key={id} selected={s.reflectionKind === id} onClick={() => go("reflection", {reflectionKind:id})}>{label}<ChevronRight aria-hidden="true" /></Option>)}</div></Copy>}
      {s.scene === "reflection" && <Copy step={7} title={{proud:"What would you like to acknowledge?",grateful:"What are you grateful for?",anticipate:"What are you looking forward to?"}[s.reflectionKind]} body="Only choose words that fit. No positive feeling is required."><div className="happy-bump-task-list">{REFLECTIONS[s.reflectionKind].slice(0,3).map(words=><Option key={words} onClick={()=>go("rerate",{[s.reflectionKind === "anticipate" ? "lookingForward" : s.reflectionKind]:words,reflectionConfirmed:true,rerateOrigin:"reflection"})}>{words}<ChevronRight aria-hidden="true"/></Option>)}</div><details className="happy-bump-privacy"><summary>Use my own words</summary><TextChoice label="Your words" value={s.reflectionKind === "anticipate" ? s.lookingForward : s[s.reflectionKind]} onFocus={pauseNarrationForInput} onChange={value=>set(current=>({...current,[s.reflectionKind === "anticipate" ? "lookingForward" : s.reflectionKind]:value,reflectionConfirmed:false}))} suggestions={[]} voice/><Primary disabled={!(s.reflectionKind === "anticipate" ? s.lookingForward : s[s.reflectionKind]).trim()} onClick={()=>go("rerate",{reflectionConfirmed:true,rerateOrigin:"reflection"})}>Keep these words</Primary></details><button className="happy-bump-quiet" onClick={()=>go("proud")}>Notice gratitude or anticipation</button><button className="happy-bump-quiet" onClick={()=>go("lifeArea")}>Choose a next move · optional</button><button className="happy-bump-quiet" onClick={()=>go("rerate",{reflectionConfirmed:false,rerateOrigin:"reflection"})}>Leave this blank</button></Copy>}
      {s.scene === "lifeArea" && <Copy step={8} compact title="What deserves a little attention next?" body="Six parts of wellbeing.">{lastFocusArea && <div className="happy-bump-callback" role="note"><Sparkles aria-hidden="true" /><p>Last time you focused on <strong>{lastFocusArea.label}</strong>{lastFocus.areaAction ? ` — ${lastFocus.areaAction}` : ""}.</p><button type="button" onClick={() => { hapticPattern([6]); set((value) => ({ ...value, lifeArea: lastFocusArea.id, areaAction: lastFocus.areaAction || "" })); go(lastFocus.areaAction ? "nextMode" : "areaAction"); }}>Try that again</button></div>}<div className="happy-bump-life-grid">{AREAS.map(({ id, label, Icon }) => <Option key={id} selected={s.lifeArea === id} onClick={() => go("areaAction", {lifeArea:id,areaAction:""})}><Icon />{label}</Option>)}</div><Primary disabled={!s.lifeArea} onClick={() => go("areaAction")}>Choose a small step</Primary><p className="happy-bump-low-effort-label">Low-effort path</p><button type="button" className="happy-bump-low-effort" onClick={() => { const lowArea = AREAS[0]; const lowAction = lowArea.actions[0]; hapticPattern([6]); saveLastFocus({ lifeArea: lowArea.id, areaAction: lowAction }); set((value) => ({ ...value, lifeArea: lowArea.id, areaAction: lowAction })); go("nextMode"); }}><ListChecks aria-hidden="true" /><span>{AREAS[0].actions[0]}</span><ChevronRight aria-hidden="true" /></button></Copy>}
      {s.scene === "areaAction" && area && <Copy step={8} compact title="Pick one low-effort step." body="Tap one that feels realistic, not impressive."><Suggestions items={area.actions} value={s.areaAction} onSelect={(areaAction) => set((value) => ({ ...value, areaAction }))} label={`${area.label} suggestions`} /><TextChoice label="Or name your own" value={s.areaAction} onFocus={pauseNarrationForInput} onChange={(areaAction) => set((value) => ({ ...value, areaAction }))} suggestions={[]} /><Primary disabled={!s.areaAction.trim()} onClick={() => { saveLastFocus({ lifeArea: s.lifeArea, areaAction: area.actions.includes(s.areaAction) ? s.areaAction : null }); go("nextMode"); }}>Carry it forward</Primary></Copy>}
      {s.scene === "nextMode" && <Copy step={9} compact title="What would serve you now?" body="Choose one next action, or skip and finish here."><div className="happy-bump-mode-grid">{MODE_CHOICES.map(({ id, label, detail, Icon }) => <Option key={id} selected={s.nextMode === id} onClick={() => go("nextPlan", { nextMode: id, nextActivity: s.nextActivity || s.areaAction || "", ...(s.nextMode === id ? {} : { pairing: "", reward: "", senses: [], activeSense: null, comfortIdea: "", customComfortIdea: "" }) })}><Icon aria-hidden="true" /><span><strong>{label}</strong><small>{detail}</small></span></Option>)}</div></Copy>}
      {s.scene === "nextPlan" && <Copy step={9} className="happy-bump-copy--nextplan" title="What is your next small action?" body="Choose an idea or use your own words."><TextChoice label="The activity" value={s.nextActivity} onFocus={pauseNarrationForInput} onChange={(nextActivity) => set((value) => ({ ...value, nextActivity, nextConfirmed:false }))} suggestions={PLANS[s.nextMode]} /><Primary disabled={!nextPlanReady} onClick={() => go("rerate",{nextConfirmed:true})}>That's my next move</Primary><button className="happy-bump-quiet" disabled={!nextPlanReady} onClick={() => go(s.nextMode === "productive" ? "pairing" : "comfortSense",{nextConfirmed:true})}>{s.nextMode === "productive" ? "Optional: make it easier" : "Optional: add a little comfort"}</button><p className="happy-bump-draft-note">Your draft stays on this device for 24 hours after your last change. Save a note at the end to keep it longer.</p></Copy>}
      {s.scene === "pairing" && <Copy step={9} title="What could make this easier?" body="Optional. Something alongside your activity."><TextChoice label="Pair it with" value={s.pairing} onFocus={pauseNarrationForInput} onChange={(pairing) => set((value) => ({ ...value, pairing, pairingConfirmed:false }))} suggestions={["Favourite playlist", "A good coffee", "Ten-minute timer"]} /><Primary onClick={() => go("rerate",{pairingConfirmed:!!s.pairing.trim(),rewardConfirmed:!!s.reward.trim(),comfortConfirmed:!!(s.customComfortIdea || s.comfortIdea).trim()})}>Keep my next move</Primary><button className="happy-bump-quiet" onClick={() => go("reward", {pairingConfirmed:!!s.pairing.trim()})}>Optional: choose something afterward</button></Copy>}
      {s.scene === "reward" && <Copy step={9} title="What would you enjoy afterward?" body="Optional. A small reward or a break."><TextChoice label="Reward after" value={s.reward} onFocus={pauseNarrationForInput} onChange={(reward) => set((value) => ({ ...value, reward, rewardConfirmed:false }))} suggestions={["A favourite snack", "A guilt-free break", "Make a good drink"]} /><Primary onClick={() => go("rerate",{pairingConfirmed:!!s.pairing.trim(),rewardConfirmed:!!s.reward.trim(),comfortConfirmed:!!(s.customComfortIdea || s.comfortIdea).trim()})}>Keep my next move</Primary></Copy>}
      {s.scene === "comfortSense" && <Copy step={9} title="What kind of comfort appeals?" body="Optional. Choose one to see a few gentle ideas."><div className="happy-bump-task-list">{Object.entries(SENSE_COMFORT).map(([sense, { Icon }]) => <Option key={sense} selected={s.activeSense === sense} onClick={() => { toggleSense(sense); go("comfortIdea"); }}><Icon aria-hidden="true" />{sense}<ChevronRight aria-hidden="true" /></Option>)}</div></Copy>}
      {s.scene === "comfortIdea" && s.activeSense && <Copy step={9} title="What comfort would you choose?" body="One gentle idea that is available to you."><TextChoice label="Your soothing idea" value={s.customComfortIdea || s.comfortIdea} onFocus={pauseNarrationForInput} onChange={(idea) => set((value) => ({ ...selectComfortIdea(value, idea), customComfortIdea:"" }))} suggestions={SENSE_COMFORT[s.activeSense].ideas} /><Primary onClick={() => go("rerate",{pairingConfirmed:!!s.pairing.trim(),rewardConfirmed:!!s.reward.trim(),comfortConfirmed:!!(s.customComfortIdea || s.comfortIdea).trim()})}>Keep my next move</Primary></Copy>}
      {s.scene === "rerate" && <Copy step={10} title="How is your energy?" body="This is energy, not mood or distress. An unchanged or lower number is okay."><input aria-label="Energy from flat to more alive" className="happy-bump-slider" type="range" min="0" max="10" value={s.current ?? 5} onChange={(event) => set((value) => ({ ...value, current: Number(event.target.value), currentConfirmed:false }))} /><div className="happy-bump-scale"><span>Flat</span><span>More alive</span></div><p className="happy-bump-body">{s.current == null ? "Not answered · confirm the displayed rating or skip" : `Energy: ${s.current}/10`}</p><Primary onClick={() => go("helpfulness", { current:s.current ?? 5, currentConfirmed:true })}>Confirm energy: {s.current ?? 5}</Primary></Copy>}
      {s.scene === "helpfulness" && <Copy title="Was this helpful?" body="Optional. You do not need to feel better to finish."><div className="happy-bump-task-list">{HELPFULNESS.map((item) => <Option key={item.id} selected={s.helpfulness === item.id} onClick={() => go("complete",{helpfulness:item.id})}>{item.label}</Option>)}</div><Primary onClick={() => go("complete",{helpfulness:null})}>Skip this check-in</Primary></Copy>}
      {s.scene === "complete" && <Copy compact title="A moment to check in." body="You do not need to feel better to finish. Keep only what helps."><div className="happy-bump-reveal-card"><p className="happy-bump-reveal-shift">{outcome.shift == null ? "Energy change not measured" : `Energy ${outcome.start} → ${outcome.end} · ${outcome.shift > 0 ? "+" : ""}${outcome.shift} points`}</p><ul className="happy-bump-verbs">{completedItems.map((text) => <li key={text}><Check />{text}</li>)}</ul></div>{s.helpfulness === "worse" ? <p className="happy-bump-body">You can stop here. Try somewhere comfortable or contact someone you trust if you want support.</p> : <p className="happy-bump-body">{s.nextActivity ? `Your next action: ${s.nextActivity}.` : "Resting here is an option. You can also choose one small comfort when you are ready."}</p>}{s.saved ? <p className="happy-bump-saved-confirmation"><Check />Your preferences are saved.</p> : <button className="happy-bump-saved" onClick={() => { const saved = saveCombination({ environment:s.environment, walkMinutes:s.walkMinutes, lifeArea:s.lifeArea, nextMode:s.nextMode }); set((value) => ({...value, saved, saveError: !saved})); }}>Save these preferences</button>}{s.saveError && <p role="alert">Could not save preferences. Please try again.</p>}<JourneyTakeaway id={ID} initialText={happyBumpTakeaway(s)} /><Primary onClick={complete}>Done</Primary></Copy>}
    </AnimatePresence><PracticeCheckpoint variant="bump" title="Your combination, taking shape" compact events={[
      earned('energy','Starting energy',`${s.baseline} / 10`,s.baselineConfirmed === true),
      earned('water','You tried','Some water',s.hydrated), earned('light','You tried','A change of light or air',s.aired),
      earned('duration','Time you chose',`${s.walkMinutes} minute${s.walkMinutes === 1 ? '' : 's'}`,s.walkChosen),
      earned('route','Your walk route', {door:'To the door and back',block:'Around the block',inside:'Indoors'}[s.environment]),
      earned('walk','You reported',s.walkStatus === 'completed' ? 'A finished walk' : 'A shorter walk',['completed','started'].includes(s.walkStatus)),
      earned('connection','You reported',s.contactStatus === 'contacted' ? 'You reached out' : 'You tried to connect',['contacted','attempted'].includes(s.contactStatus)),
      earned('task','Your small action',s.task),
      earned('task-tried','You reported',s.taskStatus === 'completed' ? 'Action done' : 'An honest start',['completed','started'].includes(s.taskStatus)),
      earned('reflection','Something you chose to notice',s.reflectionKind === 'anticipate' ? s.lookingForward : s[s.reflectionKind],s.reflectionConfirmed),
      earned('area','A direction to explore',AREAS.find(item=>item.id === s.lifeArea)?.label),
      earned('plan','A step you chose',s.areaAction,!!s.areaAction && !['areaAction','lifeArea'].includes(s.scene)),
      earned('mode','What serves you next',MODE_CHOICES.find(item=>item.id === s.nextMode)?.label),
      earned('next','Your next move',s.nextActivity,s.nextConfirmed),
      earned('pairing','Make it easier',s.pairing,s.pairingConfirmed),
      earned('reward','Something afterward',s.reward,s.rewardConfirmed),
      earned('sense','Comfort to explore',s.activeSense),
      earned('comfort','Your comfort idea',s.customComfortIdea || s.comfortIdea,s.comfortConfirmed),
      earned('now','Energy now',`${s.current} / 10`,s.currentConfirmed === true),
      earned('helpfulness','Your own assessment',HELPFULNESS.find(item=>item.id === s.helpfulness)?.label),
    ]}/></div>
  </InterventionControlShell></MotionConfig>;
}
