import React, { useEffect, useMemo, useState } from "react";
import { Check, ChevronRight, ExternalLink, Focus, Headphones, Pause, Play, Plus, Radio } from "lucide-react";
import { useNavigate } from "react-router-dom";
import { FLAGSHIP_REGISTRY } from "@/lib/flagshipRegistry";
import { clearActiveFlagship, getActiveFlagship, getFlagshipPreferences, recordHandoffDecision, rememberFlagshipEvent, saveActiveFlagship, saveNightChannelFeedbackPrompt } from "@/lib/flagshipMemory";
import { recommendHandoff } from "@/lib/flagshipHandoffs";
import { useAccessibilityPrefs } from "@/hooks/useAccessibilityPrefs";
import InterventionControlShell from "@/components/InterventionControlShell";
import { getInterventionAtmosphere } from "@/lib/interventionExperience";

const optionClass = "min-h-14 rounded-2xl border border-white/15 bg-white/[0.06] p-4 text-left transition hover:border-[var(--nf-accent)] focus:outline-none focus:ring-2 focus:ring-[var(--nf-accent)]";
const primaryClass = "min-h-12 w-full rounded-full bg-[var(--nf-accent)] px-5 font-semibold text-slate-950 disabled:opacity-40";

function usePersistedExperience(id, initial) {
  const restored = useMemo(() => {
    const active = getActiveFlagship();
    return active?.interventionId === id ? active : null;
  }, [id]);
  const [state, setState] = useState(() => restored?.experience || initial);
  useEffect(() => {
    const payload = { interventionId: id, experience: state, away: !!state.away, updatedAt: new Date().toISOString() };
    saveActiveFlagship(payload);
    const persist = () => saveActiveFlagship(payload);
    const visibility = () => { if (document.hidden) persist(); };
    document.addEventListener("visibilitychange", visibility);
    window.addEventListener("pagehide", persist);
    return () => { document.removeEventListener("visibilitychange", visibility); window.removeEventListener("pagehide", persist); };
  }, [id, state]);
  return [state, setState];
}

function Shell({ id, stage, children, onBack, onExit, dark = false, active = false, paused = false, onPause, onSimplify }) {
  const meta = FLAGSHIP_REGISTRY[id];
  const accent = id === "reroute" ? "#9ef0d0" : id === "signalLock" ? "#ffd36b" : "#9eb6ff";
  const experienceMeta = getInterventionAtmosphere({ id, why: meta?.primaryMechanism, category: meta?.primaryGoal === "sleep" ? "sleep" : undefined }, meta?.primaryGoal);
  return <InterventionControlShell id={id} goal={meta.primaryGoal} title={meta.displayName} stage={stage} onBack={onBack} onExit={onExit} active={active} paused={paused} onPause={onPause} onSimplify={onSimplify || onBack} simplifyLabel={id === "signalLock" ? "Reduce the target" : "Make this route simpler"} onDifferent={onExit} dark={dark} accent={accent} className={`new-flagship nf-${id} ${dark ? "nf-dark" : ""}`} field={<div className="nf-field" aria-hidden="true"/>}>
    <div className="mx-auto flex min-h-[calc(100dvh-170px)] w-full max-w-3xl flex-col justify-center px-5 py-6">
      <div className="mb-5 rounded-[1.75rem] border border-white/12 bg-black/25 px-5 py-4 shadow-2xl backdrop-blur-xl">
        <p className="text-[0.68rem] font-semibold uppercase tracking-[0.18em] text-[var(--nf-accent)]">{experienceMeta.purpose}</p>
        <p className="mt-2 text-sm font-medium text-white">{meta?.interactionSignature}</p>
        <p className="mt-2 text-sm leading-relaxed text-white/65">{meta?.bestWhen}</p>
      </div>
      {children}
    </div>
  </InterventionControlShell>;
}

function Panel({ eyebrow, title, body, children }) {
  return <section aria-live="polite" className="rounded-[2rem] border border-white/15 bg-[rgba(5,15,29,.76)] p-6 shadow-2xl backdrop-blur-xl sm:p-8"><p className="text-xs font-semibold uppercase tracking-[0.2em] text-[var(--nf-accent)]">{eyebrow}</p><h1 className="mt-3 font-heading text-3xl leading-tight sm:text-4xl">{title}</h1>{body&&<p className="mt-4 leading-relaxed text-white/68">{body}</p>}{children}</section>;
}

function Handoff({ from, context, launch }) {
  const [dismissed, setDismissed] = useState(false);
  const rule = dismissed ? null : recommendHandoff(from, context);
  if (!rule) return null;
  return <div className="mt-5 rounded-2xl border border-white/15 bg-white/[.06] p-4"><p className="text-xs uppercase tracking-[.16em] text-[var(--nf-accent)]">Optional next route</p><p className="mt-2 font-heading text-xl">{FLAGSHIP_REGISTRY[rule.to]?.displayName}</p><p className="mt-2 text-sm text-white/65">{rule.reason}</p><div className="mt-4 flex gap-2"><button onClick={()=>{recordHandoffDecision(from,rule.to,"accepted");launch(rule.to)}} className="min-h-11 flex-1 rounded-full bg-[var(--nf-accent)] text-sm font-semibold text-slate-950">Begin with my consent</button><button onClick={()=>{recordHandoffDecision(from,rule.to,"dismissed");setDismissed(true)}} className="min-h-11 rounded-full border border-white/20 px-4 text-sm">Not now</button></div></div>;
}

function launchIntervention(navigate, from, id, answers) {
  clearActiveFlagship(from);
  const meta = FLAGSHIP_REGISTRY[id];
  navigate("/reset", { replace: true, state: { prebuilt: true, pathway: [id], direction: meta.primaryGoal, directionLabel: meta.displayName, intensity: answers?.intensity || 5, whereFelt: "both", timeMin: 8, audio: answers?.audio || "yes" } });
}

export function RerouteExperience({ intervention, answers, onComplete, onAttemptEvent, onExit }) {
  const navigate = useNavigate();
  const [s, set] = usePersistedExperience("reroute", { stage: "safety", qualities: [] });
  const saved = getFlagshipPreferences().events?.filter(e=>e.interventionId==="reroute" && e.options?.activity).slice(-1)[0]?.options?.activity;
  const suggestions = saved ? [saved, "Continue a familiar episode or game", "Use a five-minute tactile or creative activity"] : ["Continue something familiar already in progress", "Use one saved piece of music or audio", "Choose a five-minute tactile or creative activity"];
  const launch = (id) => launchIntervention(navigate, "reroute", id, answers);
  const back = () => set(v=>({...v,stage:{foothold:"safety",qualities:"foothold",activity:"qualities",friction:"activity",away:"friction",return:"away",later:"return"}[v.stage]||"safety"}));
  const finish = () => { rememberFlagshipEvent({interventionId:"reroute", completed:true, options:{activity:s.custom?"custom-activity":s.activity||"private-choice",qualities:s.qualities}}); clearActiveFlagship("reroute"); onAttemptEvent?.({interventionId:"reroute",mechanism:intervention.mechanism,action:"completed",completedPercentage:s.outcome==="couldnt"?.35:1,timestamp:Date.now()}); onComplete?.({interventionId:"reroute",data:s}); };
  if (s.stage === "safety") return <Shell id="reroute" stage={1} onBack={onExit} onExit={onExit}><Panel eyebrow="Safety first" title="You don’t have to process everything right now." body="Reroute is short-term regulation. It does not make the underlying problem disappear."><div className="mt-6 grid gap-2">{[["safe","Redirection is safe right now"],["urgent","Urgent practical action is needed"],["danger","I may be in immediate danger"],["support","I need professional or crisis support"]].map(([v,l])=><button key={v} className={optionClass} onClick={()=>v==="safe"?set({...s,stage:"foothold"}):navigate("/support")}>{l}</button>)}</div></Panel></Shell>;
  if (s.stage === "foothold") return <Shell id="reroute" stage={1} onBack={back} onExit={onExit}><Panel eyebrow="10-second foothold" title="Stabilise one point." body="Choose one physical fact. No timer, controlled breathing or full grounding sequence."><div className="mt-6 grid gap-2 sm:grid-cols-2">{["Press both feet into the floor","Feel the surface supporting you","Hold one solid object","Look at one stable feature","Press one hand into a safe surface"].map(x=><button key={x} className={optionClass} onClick={()=>set({...s,foothold:x,stage:"qualities"})}>{x}</button>)}</div></Panel></Shell>;
  if (s.stage === "qualities") return <Shell id="reroute" stage={2} onBack={back} onExit={onExit}><Panel eyebrow="Choose the destination" title="Where should attention go instead?" body="Select every quality that would help right now."><div className="mt-6 flex flex-wrap gap-2">{["Familiar","Absorbing","Comforting","Active","Social","Funny","Creative"].map(q=><button aria-pressed={s.qualities.includes(q.toLowerCase())} key={q} onClick={()=>set({...s,qualities:s.qualities.includes(q.toLowerCase())?s.qualities.filter(x=>x!==q.toLowerCase()):[...s.qualities,q.toLowerCase()]})} className={`min-h-11 rounded-full border px-4 ${s.qualities.includes(q.toLowerCase())?"border-[var(--nf-accent)] bg-[var(--nf-accent)] text-slate-950":"border-white/15"}`}>{q}</button>)}</div><button disabled={!s.qualities.length} onClick={()=>set({...s,stage:"activity"})} className={`${primaryClass} mt-6`}>Show three routes</button></Panel></Shell>;
  if (s.stage === "activity") return <Shell id="reroute" stage={2} onBack={back} onExit={onExit}><Panel eyebrow="Preferred routes" title="Choose a real destination." body="Mentication cannot open external services here, so it will only prepare the first action."><div className="mt-6 grid gap-2">{suggestions.map(x=><button key={x} className={optionClass} onClick={()=>set({...s,activity:x,destination:s.qualities.includes("social")?"social":"activity",stage:"friction"})}>{x}</button>)}</div><label className="mt-5 block text-sm text-white/60">Or name a deliberately chosen activity<input aria-label="Preferred activity" className="mt-2 min-h-12 w-full rounded-2xl border border-white/15 bg-black/20 px-4 text-white" value={s.custom||""} onChange={e=>set({...s,custom:e.target.value})}/></label><button disabled={!s.custom?.trim()} onClick={()=>set({...s,activity:s.custom.trim(),stage:"friction"})} className={`${primaryClass} mt-3`}>Use this activity</button></Panel></Shell>;
  if (s.stage === "friction") return <Shell id="reroute" stage={3} onBack={back} onExit={onExit}><Panel eyebrow="Open the route" title={s.activity} body="Remove only the first piece of friction."><div className="mt-6 grid gap-2 sm:grid-cols-2">{["Put the needed item within reach","Open to the exact starting place","Make the first action take under 30 seconds","Prepare one editable message","Choose another route"].map(x=><button key={x} className={optionClass} onClick={()=>x==="Choose another route"?set({...s,stage:"activity"}):set({...s,friction:x,stage:"away",away:true})}>{x}</button>)}</div></Panel></Shell>;
  if (s.stage === "away") return <Shell id="reroute" stage={3} onBack={back} onExit={onExit}><Panel eyebrow="Route open" title="Leave Mentication for the activity." body="There is no timer and no required return. Your place is saved if you come back."><button onClick={()=>set({...s,stage:"return",away:false})} className={`${primaryClass} mt-6`}>I came back</button><button onClick={onExit} className="mt-3 min-h-11 w-full text-sm text-white/55">Leave the app now</button></Panel></Shell>;
  if (s.stage === "return") return <Shell id="reroute" stage={3} onBack={back} onExit={onExit}><Panel eyebrow="Optional return" title="What happened?" body="We are checking whether attention gained a usable destination—not whether distress disappeared."><div className="mt-6 grid gap-2">{[["settled","Attention settled elsewhere"],["weak","The activity was not absorbing enough"],["couldnt","Could not begin"],["support","Distress still needs support"]].map(([v,l])=><button key={v} className={optionClass} onClick={()=>v==="support"?navigate("/support"):v==="weak"?set({...s,qualities:[],stage:"qualities"}):set({...s,outcome:v,stage:"later"})}>{l}</button>)}</div></Panel></Shell>;
  return <Shell id="reroute" stage={3} onBack={back} onExit={onExit}><Panel eyebrow="Choice restored" title="Does this still need attention later?" body="Only decide this now if the immediate state is manageable."><div className="mt-6 grid gap-2 sm:grid-cols-2">{["No","Return to it later","Take one practical action","Seek support"].map(x=><button key={x} className={optionClass} onClick={()=>set({...s,later:x})}>{x}</button>)}</div>{s.later&&<><Handoff from="reroute" context={{couldNotBegin:s.outcome==="couldnt",firstActionUnclear:s.outcome==="couldnt",destination:s.destination,safeContact:s.destination==="social"}} launch={launch}/><button onClick={finish} className={`${primaryClass} mt-5`}>Finish <Check className="ml-2 inline h-4 w-4"/></button></>}</Panel></Shell>;
}

const vagueTarget = (value="") => /^(study|do admin|work on (the )?project|clean the house|work)$/i.test(value.trim()) || value.trim().split(/\s+/).length < 3;

export function SignalLockExperience({ intervention, answers, onComplete, onAttemptEvent, onExit }) {
  const navigate = useNavigate();
  const [s,set] = usePersistedExperience("signalLock",{stage:"target",duration:8,distractions:[],perimeter:[],running:false,paused:false});
  const [now,setNow] = useState(Date.now());
  const [capture,setCapture] = useState("");
  const a11y = useAccessibilityPrefs();
  const launch = id=>launchIntervention(navigate,"signalLock",id,answers);
  useEffect(()=>{ if(!s.running||s.paused)return; const t=setInterval(()=>setNow(Date.now()),250); return()=>clearInterval(t); },[s.running,s.paused]);
  const remaining = s.running ? Math.max(0,Math.ceil(((s.endAt||now)-now)/1000)) : s.duration*60;
  const elapsedMinutes = s.startedAt ? Math.max(0, Math.round((Date.now() - s.startedAt) / 6000) / 10) : 0;
  useEffect(()=>{ if(s.running&&!s.paused&&remaining===0)set(v=>({...v,running:false,stage:"expired"})); },[remaining,s.running,s.paused,set]);
  useEffect(()=>{ if(!navigator.mediaSession)return; try{navigator.mediaSession.metadata=new MediaMetadata({title:s.target||"Signal Lock",artist:"Mentication",album:"Focus sprint"});navigator.mediaSession.setActionHandler("play",()=>set(v=>({...v,paused:false,endAt:Date.now()+(v.remainingMs||60000)})));navigator.mediaSession.setActionHandler("pause",()=>set(v=>({...v,paused:true,remainingMs:Math.max(0,(v.endAt||Date.now())-Date.now())})));}catch{/* unsupported */} },[s.target,set]);
  const start=()=>set({...s,stage:"sprint",running:true,paused:false,endAt:Date.now()+s.duration*60000,startedAt:Date.now()});
  const pause=()=>set({...s,paused:true,remainingMs:Math.max(0,s.endAt-Date.now())});
  const resume=()=>set({...s,paused:false,endAt:Date.now()+(s.remainingMs||60000)});
  const finish=(outcome)=>{rememberFlagshipEvent({interventionId:"signalLock",completed:["beat","after","progress"].includes(outcome),partial:outcome==="progress",options:{duration:s.duration,actualMinutes:elapsedMinutes,distractions:s.distractions.length,outcome,timePressure:s.timePressure||"not-answered"}});clearActiveFlagship("signalLock");onAttemptEvent?.({interventionId:"signalLock",mechanism:intervention.mechanism,action:"completed",completedPercentage:outcome==="large"?.35:outcome==="progress"?.7:1,timestamp:Date.now()});onComplete?.({interventionId:"signalLock",data:{...s,outcome,actualMinutes:elapsedMinutes}})};
  const back=()=>s.stage==="target"?onExit():set(v=>({...v,stage:{scaffold:"target",sprintChoice:"scaffold",perimeter:"sprintChoice",lock:"perimeter",sprint:"lock",expired:"sprint",outcome:"lock"}[v.stage]||"target",running:false}));
  if(s.stage==="target")return <Shell id="signalLock" stage={1} onBack={back} onExit={onExit}><Panel eyebrow="Scaffold → Lock → Sprint" title="What are you working on?" body="Name a concrete target—not a whole category of work."><textarea aria-label="Sprint target" value={s.target||""} onChange={e=>set({...s,target:e.target.value})} rows={3} className="mt-6 w-full rounded-2xl border border-white/15 bg-black/20 p-4" placeholder="Open the report and complete..."/><button disabled={!s.target?.trim()} onClick={()=>set({...s,stage:"scaffold",needsScaffold:vagueTarget(s.target),precise:s.target})} className={`${primaryClass} mt-4`}>Test the signal</button></Panel></Shell>;
  if(s.stage==="scaffold")return <Shell id="signalLock" stage={1} onBack={back} onExit={onExit}><Panel eyebrow="Scaffold" title={s.needsScaffold?"This target is not lockable yet.":"Could this begin within 20 seconds?"} body="The first physical action, materials and finish line must be obvious."><div className="nf-target-cloud mt-6"><span>{s.target}</span><ChevronRight/><strong>{s.precise}</strong></div><label className="mt-5 block text-sm text-white/60">Lockable version<input aria-label="Precise lockable target" value={s.precise||""} onChange={e=>set({...s,precise:e.target.value,needsScaffold:vagueTarget(e.target.value)})} className="mt-2 min-h-12 w-full rounded-2xl border border-white/15 bg-black/20 px-4"/></label><div className="mt-4 grid gap-2 sm:grid-cols-2"><button disabled={vagueTarget(s.precise)} onClick={()=>set({...s,target:s.precise,stage:"sprintChoice",targetUnstartable:false})} className={optionClass}>Lock it</button><button onClick={()=>set({...s,precise:`Open the relevant material and complete one visible part of: ${s.target}`})} className={optionClass}>Make it smaller</button><button onClick={()=>set({...s,targetUnstartable:true})} className={optionClass}>Something is still missing</button><button onClick={()=>set({...s,target:"",stage:"target"})} className={optionClass}>Different target</button></div>{s.targetUnstartable&&<Handoff from="signalLock" context={{targetUnstartable:true}} launch={launch}/>}</Panel></Shell>;
  if(s.stage==="sprintChoice")return <Shell id="signalLock" stage={2} onBack={back} onExit={onExit}><Panel eyebrow="Choose the sprint" title="How should the lock finish?" body="Use time, visible output, or both. Stop deliberately if pressure becomes counterproductive."><div className="mt-5 grid grid-cols-3 gap-2">{["Time","Output","Time + output"].map(x=><button aria-pressed={(s.finishMode||"Time")===x} key={x} onClick={()=>set({...s,finishMode:x})} className={`${optionClass} ${(s.finishMode||"Time")===x?"border-[var(--nf-accent)]":""}`}>{x}</button>)}</div><div className="mt-4 grid grid-cols-3 gap-2">{[[3,"Flash"],[8,"Lock"],[15,"Run"]].map(([m,l])=><button key={m} onClick={()=>set({...s,duration:m,stage:"perimeter"})} className={optionClass}><strong>{m} min</strong><span className="block text-xs text-white/50">{l}</span></button>)}</div><div className="mt-4 grid gap-3 sm:grid-cols-2"><label className="block text-sm text-white/60">Custom minutes<input aria-label="Custom sprint minutes" type="number" min="1" max="90" value={s.custom||""} onChange={e=>set({...s,custom:e.target.value})} className="mt-2 min-h-12 w-full rounded-2xl border border-white/15 bg-black/20 px-4"/></label><label className="block text-sm text-white/60">Clock-time deadline<input aria-label="Sprint deadline" type="time" value={s.deadline||""} onChange={e=>set({...s,deadline:e.target.value})} className="mt-2 min-h-12 w-full rounded-2xl border border-white/15 bg-black/20 px-4"/></label></div><div className="mt-3 grid grid-cols-2 gap-2"><button disabled={!Number(s.custom)} onClick={()=>set({...s,duration:Math.min(90,Math.max(1,Number(s.custom))),stage:"perimeter"})} className={optionClass}>Use custom minutes</button><button disabled={!s.deadline} onClick={()=>{const [h,m]=s.deadline.split(":").map(Number);const end=new Date();end.setHours(h,m,0,0);if(end<=new Date())end.setDate(end.getDate()+1);set({...s,duration:Math.min(90,Math.max(1,Math.ceil((end-Date.now())/60000))),finishMode:"Clock deadline",stage:"perimeter"})}} className={optionClass}>Use deadline</button></div></Panel></Shell>;
  if(s.stage==="perimeter")return <Shell id="signalLock" stage={2} onBack={back} onExit={onExit}><Panel eyebrow="Clear the perimeter" title="What could interfere?" body="Select only what needs attention. Mentication cannot block applications or enable device Focus mode here."><div className="mt-6 flex flex-wrap gap-2">{["Notifications","Extra tabs","Missing material","Noise","Visible task","Competing thoughts","Urge to escape","Uncertainty"].map(x=><button aria-pressed={s.perimeter.includes(x)} key={x} onClick={()=>set({...s,perimeter:s.perimeter.includes(x)?s.perimeter.filter(y=>y!==x):[...s.perimeter,x]})} className={`min-h-11 rounded-full border px-4 ${s.perimeter.includes(x)?"border-[var(--nf-accent)] bg-[var(--nf-accent)] text-slate-950":"border-white/15"}`}>{x}</button>)}</div><button onClick={()=>set({...s,stage:"lock"})} className={`${primaryClass} mt-6`}>Perimeter ready</button></Panel></Shell>;
  if(s.stage==="lock")return <Shell id="signalLock" stage={2} onBack={back} onExit={onExit}><Panel eyebrow="Target acquired" title={s.target} body={`${s.duration} minutes · Finish when the defined target is visibly complete.`}><div className="nf-reticle my-8" aria-hidden="true"><Focus/></div><button onClick={start} className={primaryClass}>LOCK AND START</button></Panel></Shell>;
  if(s.stage==="sprint")return <Shell id="signalLock" stage={3} onBack={back} onExit={onExit} active paused={s.paused} onPause={s.paused?resume:pause} onSimplify={()=>set({...s,running:false,stage:"scaffold"})}><Panel eyebrow="Signal locked" title={`${String(Math.floor(remaining/60)).padStart(2,"0")}:${String(remaining%60).padStart(2,"0")}`} body={s.target}><div className="nf-radar my-6" aria-hidden="true">{s.distractions.map((_,i)=><i key={i} style={{transform:`rotate(${i*47}deg) translateX(${45+i*6}px)`}}/>)}</div><div className="flex gap-2"><button onClick={s.paused?resume:pause} className="min-h-12 flex-1 rounded-full border border-white/20">{s.paused?<Play className="mr-2 inline h-4 w-4"/>:<Pause className="mr-2 inline h-4 w-4"/>}{s.paused?"Resume":"Pause"}</button><button onClick={()=>set({...s,running:false,stage:"outcome"})} className="min-h-12 flex-1 rounded-full border border-white/20">Stop deliberately</button></div><div className="mt-4 flex gap-2"><input aria-label="Capture a competing thought" value={capture} onChange={e=>setCapture(e.target.value)} className="min-h-11 min-w-0 flex-1 rounded-full border border-white/15 bg-black/20 px-4" placeholder="Park a distraction..."/><button aria-label="Capture distraction" onClick={()=>{if(capture.trim()){set({...s,distractions:[...s.distractions,"captured"]});setCapture("")}}} className="grid min-h-11 min-w-11 place-items-center rounded-full bg-[var(--nf-accent)] text-slate-950"><Plus/></button></div><button onClick={()=>set({...s,running:false,stage:"outcome"})} className={`${primaryClass} mt-5`}>Target reached</button>{a11y.prefs.reducedMotion&&<p className="mt-3 text-xs text-white/45">Static timer view is active because reduced motion is enabled.</p>}</Panel></Shell>;
  if(s.stage==="expired")return <Shell id="signalLock" stage={3} onBack={back} onExit={onExit}><Panel eyebrow="Time reached" title="Choose the next deliberate move." body="There is no failure state."><div className="mt-6 grid gap-2 sm:grid-cols-2"><button onClick={()=>set({...s,running:true,stage:"sprint",endAt:Date.now()+120000})} className={optionClass}>Add two minutes</button><button onClick={()=>set({...s,stage:"scaffold"})} className={optionClass}>Lock remaining piece</button><button onClick={()=>set({...s,stage:"outcome"})} className={optionClass}>Save progress</button><button onClick={()=>set({...s,stage:"outcome"})} className={optionClass}>Finish deliberately</button></div></Panel></Shell>;
  return <Shell id="signalLock" stage={3} onBack={back} onExit={onExit}><Panel eyebrow="Calibration" title="What happened?" body={`Estimated ${s.duration} min · active for ${elapsedMinutes} min · ${s.distractions.length} distraction${s.distractions.length===1?"":"s"} captured. No productivity score is created.`}><p className="mt-5 text-sm text-white/60">Did time pressure help?</p><div className="mt-2 grid grid-cols-3 gap-2">{["Helped","Neutral","Hindered"].map(x=><button aria-pressed={s.timePressure===x} key={x} onClick={()=>set({...s,timePressure:x})} className={`${optionClass} ${s.timePressure===x?"border-[var(--nf-accent)]":""}`}>{x}</button>)}</div><div className="mt-5 grid gap-2">{[["beat","Beat the clock"],["after","Reached the finish line after time"],["progress","Made meaningful progress"],["large","Target was still too large"],["captured","Attention was captured elsewhere"],["stopped","Stopped deliberately"]].map(([v,l])=><button key={v} onClick={()=>finish(v)} className={optionClass}>{l}</button>)}</div></Panel></Shell>;
}

export function NightChannelExperience({ intervention, onAttemptEvent, onExit }) {
  const [s,set] = usePersistedExperience("nightChannel",{stage:"channel"});
  const [now,setNow]=useState(Date.now());
  useEffect(()=>{if(s.stage!=="playing"||!s.fadeEnd)return;const t=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(t)},[s.stage,s.fadeEnd]);
  const remaining=s.fadeEnd?Math.max(0,s.fadeEnd-now):null;
  useEffect(()=>{if(s.stage==="playing"&&remaining===0&&s.fadeEnd)set(v=>({...v,fadeEnd:null}))},[remaining,s.stage,s.fadeEnd,set]);
  const back=()=>s.stage==="channel"?onExit():set(v=>({...v,stage:{engagement:"channel",source:"engagement",fade:"source",playing:"fade"}[v.stage]||"channel"}));
  const begin=()=>{const startedAt=Date.now();setNow(startedAt);set({...s,stage:"playing",away:true,fadeEnd:Number(s.fade)?startedAt+Number(s.fade)*60000:null});rememberFlagshipEvent({interventionId:"nightChannel",options:{channel:s.channel,engagement:s.engagement,source:s.source,fade:s.fade}});};
  const stop=()=>{saveNightChannelFeedbackPrompt({channel:s.channel,engagement:s.engagement,source:s.source,fade:s.fade});clearActiveFlagship("nightChannel");onAttemptEvent?.({interventionId:"nightChannel",mechanism:intervention.mechanism,action:"stopped-deliberately",completedPercentage:.8,timestamp:Date.now()});onExit?.();};
  if(s.stage==="channel")return <Shell id="nightChannel" stage={1} onBack={back} onExit={onExit}><Panel eyebrow="Tune the channel" title="What would be easiest to drift into tonight?" body="Something worth listening to. Nothing that needs to be finished."><div className="mt-6 grid gap-2 sm:grid-cols-2">{["Familiar Replay","A continuing story","Gentle Curiosity","Gentle conversation","A fictional world"].map(x=><button key={x} className={optionClass} onClick={()=>set({...s,channel:x,stage:"engagement"})}>{x}</button>)}</div><p className="mt-4 text-xs leading-relaxed text-white/45">Familiar Replay can be a known song, show, video, podcast or audiobook. It never means voice cloning.</p></Panel></Shell>;
  if(s.stage==="engagement")return <Shell id="nightChannel" stage={1} onBack={back} onExit={onExit}><Panel eyebrow="Engagement level" title="How much capture is useful tonight?" body="Boring is not automatically better."><div className="mt-6 grid gap-2">{[["Familiar Replay","Predictable content already heard"],["Gentle Curiosity","Interesting without close attention"],["Fuller Capture","Absorbing enough to compete with persistent thoughts"]].map(([x,b])=><button key={x} className={optionClass} onClick={()=>set({...s,engagement:x,stage:"source"})}><strong>{x}</strong><span className="mt-1 block text-xs text-white/50">{b}</span></button>)}</div></Panel></Shell>;
  if(s.stage==="source")return <Shell id="nightChannel" stage={2} onBack={back} onExit={onExit}><Panel eyebrow="Select the source" title="Choose an honest route to audio." body="No audiobook or podcast integration is connected in this build. Mentication will not pretend to control an external service."><div className="mt-6 grid gap-2"><button className={optionClass} onClick={()=>set({...s,source:"external",stage:"fade"})}><ExternalLink className="mr-2 inline h-4 w-4"/>Use my audio app</button><button disabled className={`${optionClass} opacity-45`}><Radio className="mr-2 inline h-4 w-4"/>Original Mentication narrative — content not installed</button></div><label className="mt-5 block text-sm text-white/60">Optional topic or title<input aria-label="Audio title or topic" value={s.topic||""} onChange={e=>set({...s,topic:e.target.value})} className="mt-2 min-h-12 w-full rounded-2xl border border-white/15 bg-black/20 px-4" placeholder="Your audiobook, episode or replay..."/></label></Panel></Shell>;
  if(s.stage==="fade")return <Shell id="nightChannel" stage={2} onBack={back} onExit={onExit}><Panel eyebrow="Interface fade" title="When should Mentication disappear?" body="This is not a sleep countdown. Playback and audio fading remain under the external app’s controls."><div className="mt-6 grid grid-cols-2 gap-2">{[[15,"15 minutes"],[30,"30 minutes"],[45,"45 minutes"],[0,"Stay near-black"]].map(([v,l])=><button key={v} onClick={()=>set({...s,fade:v})} className={`${optionClass} ${s.fade===v?"border-[var(--nf-accent)]":""}`}>{l}</button>)}</div><button disabled={s.fade===undefined} onClick={begin} className={`${primaryClass} mt-6`}>Enter Night Channel</button></Panel></Shell>;
  return <Shell id="nightChannel" stage={3} dark active onBack={back} onExit={stop} onSimplify={()=>set({...s,fade:15})}><div className="nf-channel-player text-center"><div className="nf-frequency" aria-hidden="true"><i/><i/><i/><i/><i/></div><Headphones className="mx-auto h-7 w-7 text-[var(--nf-accent)]"/><h1 className="mt-5 font-heading text-2xl">{s.topic||s.channel}</h1><p className="mx-auto mt-3 max-w-sm text-sm text-white/45">Continue playback and use pause, volume or stop in your selected audio app. Mentication will not ask for completion tonight.</p>{remaining!==null&&<p className="mt-5 text-xs text-white/35">Near-black interface · {Math.ceil(remaining/60000)} min preference remaining</p>}<button onClick={stop} className="mt-8 min-h-11 px-5 text-sm text-white/45">Leave Night Channel</button></div></Shell>;
}

export default function NewFlagshipExperience(props) {
  if(props.intervention.id==="reroute")return <RerouteExperience {...props}/>;
  if(props.intervention.id==="signalLock")return <SignalLockExperience {...props}/>;
  return <NightChannelExperience {...props}/>;
}
