import { useState } from 'react';
import useCarePractice from './care-practices/useCarePractice';
import { CareFrame, Primary, Quiet, Scene, SharedScene, WordChoices } from './care-practices/CarePracticeFrame';
import { ThoughtVisual } from './care-practices/CareVisuals';
import { EXTERNAL_ANCHORS, noticingPhrase } from '@/lib/carePracticeDesign';

export default function UnhookExperience(props) {
  const flow=useCarePractice('unhook',props); const {s}=flow; const [namingAnchor, setNamingAnchor] = useState(false);
  return <CareFrame flow={flow}>
    {s.stage==='notice' ? <Scene flow={flow} eyebrow="The thought in the foreground" title="Which words keep pulling you in?" body="We will practise noticing them without deciding if they are true."><ThoughtVisual s={s}/><WordChoices label="The sticky thought" value={s.notice} choices={['Something will go wrong.','I cannot do this.','They will judge me.']} onChange={notice=>flow.patch({notice,perspective:'',defusionStep:0,distance:'near',anchorNoticed:false})}/><Primary disabled={!s.notice.trim()} onClick={()=>flow.go('perspective')}>Work with this thought</Primary><Quiet onClick={()=>flow.go('perspective',{notice:''})}>Keep the words in my mind</Quiet></Scene>
    : s.stage==='perspective' ? <Scene flow={flow} eyebrow="Change how you hold the words" title={s.defusionStep?'Notice it. Let it sit beside you.':'Give the thought a little distance.'} body={s.defusionStep?'The words can remain. You do not have to follow where they lead.':'Try adding a few words before the thought.'}><ThoughtVisual s={s}/>{!s.defusionStep ? <Primary onClick={()=>flow.patch({defusionStep:1,perspective:noticingPhrase(s.notice),practiceTaken:true})}>Add “I am noticing the thought…”</Primary> : <Primary onClick={()=>flow.go('practice',{defusionStep:2,distance:'beside',perspective:noticingPhrase(s.notice),practiceTaken:true})}>Let it sit beside my attention</Primary>}<Quiet onClick={()=>flow.go('action')}>Go straight to a useful action</Quiet></Scene>
    : s.stage==='practice' ? <Scene flow={flow} eyebrow="Attention comes back" title="The thought is here. What else is here?" body="Choose one thing to notice in the room."><ThoughtVisual s={s} mode="anchor"/>{s.notice.length>100 && <details className="unhook-full-thought"><summary>Read the whole thought</summary><p>{s.notice}</p></details>}<div className="care-anchor-choices unhook-anchor-tabs" role="group" aria-label="An anchor in the room">{Object.entries(EXTERNAL_ANCHORS).map(([key,a])=><button type="button" key={key} aria-label={a.label} aria-pressed={s.anchorType===key} onClick={()=>flow.patch({anchorType:key,anchorNoticed:false,anchorText:''})}>{({object:'See',sound:'Hear',support:'Feel support'})[key]}</button>)}</div>{s.anchorType && <div className="care-anchor-instruction"><p>{EXTERNAL_ANCHORS[s.anchorType].instruction}</p><button type="button" className="care-edit" aria-expanded={namingAnchor} onClick={()=>setNamingAnchor(!namingAnchor)}>{namingAnchor ? 'Close anchor name' : s.anchorText ? 'Edit my anchor' : 'Name what I notice'}</button>{namingAnchor && <label className="care-input-label">{EXTERNAL_ANCHORS[s.anchorType].prompt}<input maxLength={140} placeholder={`${EXTERNAL_ANCHORS[s.anchorType].example} · optional`} value={s.anchorText} onChange={e=>flow.patch({anchorText:e.target.value,anchorNoticed:false})}/></label>}<button type="button" className="care-experience-action" aria-pressed={s.anchorNoticed} onClick={()=>{flow.patch({anchorNoticed:!s.anchorNoticed});setNamingAnchor(false);}}>{s.anchorNoticed?'I have brought my attention here':'I have noticed this in the room'}</button></div>}<Primary onClick={()=>flow.go('action')}>Choose where I go next</Primary><Quiet onClick={()=>flow.go('orient')}>Stop and look around</Quiet></Scene>
    : <SharedScene flow={flow} visual={<ThoughtVisual s={s} />}/>}
  </CareFrame>;
}
