"""Original sensory and visual attention practices; actual interruption and feedback."""
import argparse,json
from pathlib import Path
from playwright.sync_api import sync_playwright,expect
p=argparse.ArgumentParser();p.add_argument('--url',default='http://127.0.0.1:5191');p.add_argument('--out',required=True);args=p.parse_args();out=Path(args.out);out.mkdir(parents=True,exist_ok=True)
with sync_playwright() as pw:
 b=pw.chromium.launch(executable_path='/usr/bin/chromium',args=['--mute-audio']);errors=[]
 def open(width,name):
  c=b.new_context(viewport={'width':width,'height':844},reduced_motion='reduce');a=c.new_page();a.on('pageerror',lambda e:errors.append(str(e)));a.goto(args.url+'/start');a.evaluate("localStorage.setItem('haven_onboarded','1')");a.goto(args.url+'/library');a.get_by_placeholder('Search practices…').fill(name);a.get_by_role('button',name=name).first.click();a.get_by_role('button',name='0',exact=True).click();a.get_by_role('button',name='Start '+name,exact=True).click();return c,a
 def click(a,name):
  if name=='Try an easier option' and not a.get_by_role('button',name=name,exact=True).is_visible():return
  a.get_by_role('button',name=name,exact=True).click()
 for width in [320,390]:
  c,a=open(width,'5-4-3-2-1 Grounding');expect(a.get_by_role('heading',name='Five things you can see',exact=True)).to_be_visible();a.get_by_text('How to practise · optional',exact=True).click();expect(a.get_by_text('The time is a suggestion.',exact=False)).to_be_visible();a.screenshot(path=str(out/f'grounding-useful-instructions-{width}.png'),full_page=True);click(a,'Next sense');expect(a.get_by_role('heading',name='Four things you can feel')).to_be_visible();click(a,'Try another sense instead');expect(a.get_by_text('If touch is unavailable or uncomfortable',exact=False)).to_be_visible();click(a,'Pause');pos=a.evaluate('history.state.usr.reset_grounding');sid=a.evaluate('history.state.usr.reset_session_id');a.reload();expect(a.get_by_role('heading',name='Four things you can feel')).to_be_visible();expect(a.get_by_role('button',name='Play',exact=True)).to_be_visible();assert a.evaluate('history.state.usr.reset_grounding.elapsed')==pos['elapsed'];a.screenshot(path=str(out/f'grounding-paused-touch-return-{width}.png'),full_page=True);click(a,'Another way');expect(a.get_by_role('dialog')).to_be_visible();a.keyboard.press('Escape');expect(a.get_by_role('button',name='Play',exact=True)).to_be_visible();a.go_back();a.go_forward();expect(a.get_by_role('heading',name='Four things you can feel')).to_be_visible();assert a.evaluate('history.state.usr.reset_session_id')==sid;click(a,'Play');click(a,'Finish grounding early');expect(a.get_by_role('heading',name='How did grounding feel?')).to_be_visible();click(a,'More unsettled');click(a,'Made things worse');expect(a.get_by_text('You said this made things worse.',exact=False)).to_be_visible();a.reload();expect(a.get_by_role('heading',name='How did grounding feel?')).to_be_visible();expect(a.get_by_role('button',name='More unsettled')).to_have_attribute('aria-pressed','true');expect(a.get_by_role('button',name='Made things worse')).to_have_attribute('aria-pressed','true');a.evaluate("document.documentElement.classList.add('large-text')");assert a.evaluate('document.documentElement.scrollWidth<=innerWidth');a.screenshot(path=str(out/f'grounding-honest-feedback-{width}.png'),full_page=True);click(a,'Continue to final rating');expect(a.get_by_text('Not answered yet.',exact=True)).to_be_visible();click(a,'Skip and finish');a.wait_for_url(args.url+'/',timeout=20000);history=a.evaluate("JSON.parse(localStorage.getItem('mentation.sessions.v1'))");assert history[0]['intensity_end'] is None;assert history[0]['attempts'][0]['completed_percentage']<1;assert history[0]['intervention_outcome']['presence']=='more_unsettled';c.close();print('PASS',width,'original senses/optional teaching/accessibility alternative, exact chosen-sense paused refresh/Back/forward, actual independent worse feedback survives refresh, honest partial history and blank endpoint.')
 # Every authored sense, manual recenter, skipped feedback and a device-local optional actual cue.
 c,a=open(390,'5-4-3-2-1 Grounding')
 for heading in ['Five things you can see','Four things you can feel','Three things you can hear','Two things you can smell','One thing you can taste']:
  expect(a.get_by_role('heading',name=heading,exact=True)).to_be_visible();click(a,'Try another sense instead');expect(a.get_by_role('status').filter(has_text='If looking' if heading.startswith('Five') else 'If touch' if heading.startswith('Four') else 'If listening' if heading.startswith('Three') else 'No clear')).to_be_visible();click(a,'Next sense' if not heading.startswith('One') else 'Recenter when ready')
 click(a,'Finish grounding');click(a,'Skip feedback');expect(a.get_by_text('Not answered yet.',exact=True)).to_be_visible();a.locator('details.journey-takeaway > summary').click();a.get_by_label('Which accessible sense or ordinary detail would you return to?').fill('Synthetic chosen cue: the blue cup');click(a,'Save on this device');click(a,'Skip and finish');a.wait_for_url(args.url+'/',timeout=20000);a.goto(args.url+'/return-points');expect(a.get_by_text('Synthetic chosen cue: the blue cup',exact=True)).to_be_visible();click(a,'Delete this note');a.reload();expect(a.get_by_text('Synthetic chosen cue: the blue cup',exact=True)).to_have_count(0);c.close();print('PASS all original six grounding stages and accessible alternatives, manual recenter, explicit skipped feedback, actual optional cue/read/delete with no invented outcome.')
 for width in [320,390]:
  c,a=open(width,'Vector Shift');f=a.frame_locator('iframe');click(f,'Tap here to begin');click(f,'Skip step');expect(f.get_by_role('heading',name='Serpent',exact=True)).to_be_visible();f.locator('body').evaluate("()=>{window.realSet=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){if(k.startsWith('vector-shift:v2:'))return;window.realSet.call(this,k,v)}}");click(f,'Pause');expect(f.get_by_role('dialog')).to_contain_text('could not be saved');a.screenshot(path=str(out/f'vector-honest-save-recovery-{width}.png'));f.locator('body').evaluate('()=>{Storage.prototype.setItem=window.realSet}');click(f.get_by_role('dialog'),'Retry saving place');expect(f.get_by_role('dialog')).to_contain_text('Your place is saved');a.reload();expect(f.get_by_role('dialog',name='Paused')).to_be_visible();click(f,'Resume');expect(f.get_by_role('heading',name='Serpent',exact=True)).to_be_visible();click(f,'Try an easier option');a.screenshot(path=str(out/f'vector-original-easier-serpent-{width}.png'));click(f,'Skip step');click(f,'Try an easier option');click(f,'Reveal a letter');click(f,'Pause');a.reload();expect(f.get_by_role('dialog',name='Paused')).to_be_visible();click(f,'Resume');expect(f.get_by_role('heading',name='Word match',exact=True)).to_be_visible();click(f,'Skip step');click(f,'Try an easier option');f.get_by_role('button',name='Notice LUNA',exact=False).click();click(f,'Skip step');click(f,'Skip step');expect(f.get_by_role('heading',name='Check in',exact=True)).to_be_visible();click(f,'Felt worse');click(f,'Continue to check-in');expect(a.get_by_text('Not answered yet.',exact=True)).to_be_visible();click(a,'Skip and finish');a.wait_for_url(args.url+'/',timeout=20000);history=a.evaluate("JSON.parse(localStorage.getItem('mentation.sessions.v1'))");assert history[0]['intensity_end'] is None;assert history[0]['intervention_outcome']['gameplayOnly'] is True;c.close();print('PASS',width,'original visual challenges/easier modes, verified save failure/retry, exact paused stage refresh, actual negative feedback and blank endpoint without a recovery claim.')
 assert not errors,errors;b.close()
