"""Original care practices: useful instructions and actual saved-card content."""
import argparse,json
from pathlib import Path
from playwright.sync_api import sync_playwright,expect
p=argparse.ArgumentParser();p.add_argument('--url',default='http://127.0.0.1:5191');p.add_argument('--out',required=True);args=p.parse_args();out=Path(args.out);out.mkdir(parents=True,exist_ok=True)
with sync_playwright() as pw:
 b=pw.chromium.launch(executable_path='/usr/bin/chromium');errors=[]
 def setup(width):
  c=b.new_context(viewport={'width':width,'height':844},reduced_motion='reduce');a=c.new_page();a.on('pageerror',lambda e:errors.append(str(e)));a.goto(args.url+'/start');a.evaluate("localStorage.setItem('haven_onboarded','1')");return c,a
 def click(a,name):a.get_by_role('button',name=name,exact=True).click()
 def launch(a,name):
  a.goto(args.url+'/library');a.get_by_placeholder('Search practices…').fill(name);a.get_by_role('button',name=name).click();click(a,'Begin');click(a,'0 of 10');click(a,'Continue')
 def resume_after_history(a,cue):
  # Allow the authored host transition to settle before distinguishing a kept
  # BFCache practice from a freshly mounted Resume screen. The exiting screen
  # can briefly contain the same cue.
  a.wait_for_timeout(800)
  # Chromium may restore the already-mounted practice through its back/forward cache.
  resume=a.get_by_role('button',name='Resume practice',exact=True)
  expect(resume.or_(a.get_by_text(cue,exact=True)).first).to_be_visible()
  if resume.is_visible():resume.click()
  expect(a.get_by_text(cue,exact=True)).to_be_visible()
 def finish(a):
  click(a,'Skip rating');click(a,'Save this card on my device');click(a,'Finish');expect(a.get_by_text('Not answered yet.',exact=True)).to_be_visible();click(a,'Skip and finish');a.wait_for_url(args.url+'/',timeout=20000);a.goto(args.url+'/return-points')
 for width in [320,390]:
  c,a=setup(width);launch(a,'Make Room for the Feeling');click(a,'Worry');click(a,'Find a steady point nearby');click(a,'Something I can see');click(a,'Name it');a.get_by_label('An object or colour nearby',exact=True).fill('Synthetic anchor: the blue cup');expect(a.get_by_text('Look at one ordinary object. Notice its colour and edges. Stay with your surroundings for now.',exact=True)).to_be_visible();a.get_by_text('What am I practising?',exact=True).click();expect(a.get_by_role('heading',name='What making room means here',exact=True)).to_be_visible();a.screenshot(path=str(out/f'room-only-learning-{width}.png'),full_page=True)
  # Educational reading does not select an allowance or count as trying the practice.
  assert a.evaluate("JSON.parse(localStorage.getItem('mentation.flagship.active.v1')).experience.practiceTaken") is False;expect(a.get_by_role('button',name='Room only',exact=True)).to_have_attribute('aria-pressed','true');a.get_by_role('button',name='I stayed with my surroundings',exact=False).click();click(a,'No next step for now');finish(a)
  expect(a.get_by_text('Synthetic anchor: the blue cup',exact=True)).to_be_visible();expect(a.get_by_text('An anchor I chose',exact=True)).to_be_visible();expect(a.get_by_text('The feeling I noticed',exact=True)).to_be_visible();expect(a.get_by_text('A phrase to make room',exact=True)).to_have_count(0);article=a.locator('article');assert article.locator('header').evaluate("el=>getComputedStyle(el).backgroundColor")=='rgb(19, 44, 41)';a.get_by_role('searchbox',name='Find saved work',exact=True).fill('blue cup');expect(article).to_be_visible();a.get_by_role('searchbox',name='Find saved work',exact=True).fill('untried');expect(article).to_have_count(0);click(a,'Clear saved-work search');a.evaluate("document.documentElement.classList.add('large-text')");assert a.evaluate('document.documentElement.scrollWidth<=innerWidth');a.screenshot(path=str(out/f'actual-anchor-return-{width}.png'),full_page=True)
  history=a.evaluate("JSON.parse(localStorage.getItem('mentation.sessions.v1'))");outcome=history[0]['intervention_outcome'];assert outcome['assessment']['before']==0 and outcome['assessment']['after'] is None and outcome['change'] is None;assert not outcome['practiceTaken'];assert 'Synthetic anchor' not in json.dumps(history)
  # Review the same native saved card, not a duplicated note, then delete it.
  a.locator('article').get_by_role('link',name='Open practice and saved card',exact=True).click();click(a,'Open my saved card');expect(a.locator('.care-takeaway').get_by_text('Synthetic anchor: the blue cup',exact=True)).to_be_visible();click(a,'Close card');a.wait_for_url(args.url+'/',timeout=20000);a.goto(args.url+'/return-points');click(a,'Delete saved card');a.reload();expect(a.get_by_text('Synthetic anchor: the blue cup',exact=True)).to_have_count(0);c.close();print('PASS',width,'original room-only choice, concrete external cue, optional teaching, actual anchor saved/read/search/native review/delete, exact zero-vs-blank ratings, no fake feeling practice or score gain.')
 # Make Room: a phrase selected before stopping is not an actual tried-phrase takeaway.
 c,a=setup(390);launch(a,'Make Room for the Feeling');click(a,'Frustration');click(a,'Find a steady point nearby');click(a,'A sound in the room');click(a,'Name it');a.get_by_label('A sound already here',exact=True).fill('Synthetic fan');click(a,'A little');phrase=a.evaluate("JSON.parse(localStorage.getItem('mentation.flagship.active.v1')).experience.perspective");a.reload();click(a,'Resume practice');expect(a.get_by_role('button',name='A little',exact=True)).to_have_attribute('aria-pressed','true');expect(a.get_by_text('Synthetic fan',exact=True)).to_be_visible();click(a,'Another way');expect(a.get_by_role('dialog')).to_be_visible();a.keyboard.press('Escape');click(a,'Too much? Return to the room');click(a,'End practice');finish(a);expect(a.get_by_text('Synthetic fan',exact=True)).to_be_visible();expect(a.get_by_text(phrase,exact=True)).to_have_count(0);a.get_by_role('searchbox',name='Find saved work',exact=True).fill(phrase);expect(a.locator('article')).to_have_count(0);click(a,'Clear saved-work search');click(a,'Delete saved card');c.close();print('PASS stopped Make Room preserves its chosen cue across refresh/alternative, excludes untried phrase from native and return/search content.')
 # Unhook: original thought/anchor/action practice with teaching and interruption.
 c,a=setup(320);launch(a,'Unhook from the Thought');click(a,'Something will go wrong.');click(a,'Work with this thought');click(a,'Notice this as a thought');click(a,'A sound in the room');click(a,'Name what I notice');a.get_by_label('A sound already here',exact=True).fill('Synthetic fan anchor');a.get_by_text('What am I practising?',exact=True).click();expect(a.get_by_role('heading',name='How to notice a thought and return',exact=True)).to_be_visible();a.evaluate("document.documentElement.classList.add('large-text')");assert a.evaluate('document.documentElement.scrollWidth<=innerWidth');a.screenshot(path=str(out/'unhook-learning-320-large.png'),full_page=True);a.reload();click(a,'Resume practice');expect(a.get_by_text('Synthetic fan anchor',exact=True)).to_be_visible();click(a,'Another way');expect(a.get_by_role('dialog')).to_be_visible();a.keyboard.press('Escape');a.go_back();a.go_forward();resume_after_history(a,'Synthetic fan anchor');a.get_by_role('button',name='I tried noticing and returning attention',exact=False).click();a.get_by_label('Or choose my own step',exact=True).fill('Synthetic next action: read a paragraph');click(a,'Keep this as my next step');finish(a);expect(a.get_by_text('Synthetic fan anchor',exact=True)).to_be_visible();expect(a.get_by_text('Your chosen action: Synthetic next action: read a paragraph',exact=True)).to_be_visible();expect(a.get_by_text('Where I return my attention · Planned',exact=True)).to_be_visible();assert a.locator('article header').evaluate("el=>getComputedStyle(el).backgroundColor")=='rgb(11, 24, 43)';a.screenshot(path=str(out/'unhook-actual-return-320.png'),full_page=True);click(a,'Delete saved card');c.close();print('PASS original Unhook thought/noticing/anchor/next-action, useful learning, 320px large text, refresh/alternative/Back/forward, truthful planned return and deletion.')
 # Self-Compassion: selected words, tone, and useful optional teaching remain a practice.
 c,a=setup(390);launch(a,'Self-Compassion');click(a,'I messed everything up.');click(a,'Try a voice on my side');click(a,'I made a mistake. I can care for myself and repair what I can.');click(a,'Gentle');a.get_by_text('What am I practising?',exact=True).click();expect(a.get_by_role('heading',name='How to try a caring response',exact=True)).to_be_visible();expect(a.get_by_role('button',name='Gentle',exact=True)).to_have_attribute('aria-pressed','true');a.evaluate("document.documentElement.classList.add('large-text')");assert a.evaluate('document.documentElement.scrollWidth<=innerWidth');a.screenshot(path=str(out/'compassion-learning-390-large.png'),full_page=True);assert a.evaluate("JSON.parse(localStorage.getItem('mentation.flagship.active.v1')).experience.practiceTaken") is False;a.reload();click(a,'Resume practice');expect(a.get_by_role('button',name='Gentle',exact=True)).to_have_attribute('aria-pressed','true');expect(a.get_by_role('heading',name='I made a mistake. I can care for myself and repair what I can.',exact=True)).to_be_visible();c.close();print('PASS original Self-Compassion selected response/gentle tone, useful optional teaching, large text, refresh, no practice credit from reading instructions.')
 assert not errors,errors;b.close()
