"""Actual original journeys, explicit note consent and consistent cross-tab return."""
import argparse,json
from pathlib import Path
from playwright.sync_api import sync_playwright,expect
p=argparse.ArgumentParser();p.add_argument('--url',default='http://127.0.0.1:5191');p.add_argument('--out',required=True);a=p.parse_args();out=Path(a.out);out.mkdir(parents=True,exist_ok=True)
with sync_playwright() as pw:
 b=pw.chromium.launch(executable_path='/usr/bin/chromium');errors=[]
 def setup(width=390):
  c=b.new_context(viewport={'width':width,'height':844},reduced_motion='reduce');page=c.new_page();page.on('pageerror',lambda e:errors.append(str(e)));page.goto(a.url+'/start');page.evaluate("localStorage.setItem('haven_onboarded','1')");return c,page
 def launch(page,name):
  page.goto(a.url+'/library');page.get_by_placeholder('Search practices…').fill(name);page.get_by_role('button',name=name).click();page.get_by_role('slider').fill('4')
  distress=page.get_by_role('combobox',name='Current distress',exact=True)
  if distress.count():distress.select_option('4')
 def notes(page):return page.evaluate("JSON.parse(localStorage.getItem('mentation.takeaways.v1')||'[]')")
 c,page=setup();launch(page,'The Happy Bump');page.get_by_role('button',name='Build my reset',exact=True).click();page.get_by_role('button',name='Begin',exact=True).click(timeout=20000);page.locator('.happy-bump').get_by_role('button',name='Start',exact=True).click()
 # Use original skip choices; do not fabricate completion of an activity.
 for _ in range(14):
  if page.get_by_role('button',name='Relaxing',exact=False).count():break
  old=page.locator('.happy-bump-copy h1').inner_text();page.get_by_role('button',name='Skip ahead',exact=True).click();page.wait_for_function("old => {const h=document.querySelector('.happy-bump-copy h1');return h&&h.innerText!==old;}",arg=old)
 page.get_by_role('button',name='Relaxing',exact=False).click();page.get_by_role('textbox',name='The activity').fill('Synthetic choice: read one page');page.get_by_role('button',name="That's my next move",exact=True).click()
 for _ in range(3):
  if page.locator('.happy-bump-copy').get_by_role('heading',name='A moment to check in.',exact=True).count():break
  old=page.locator('.happy-bump-copy h1').inner_text();page.get_by_role('button',name='Skip ahead',exact=True).click();page.wait_for_function("old => {const h=document.querySelector('.happy-bump-copy h1');return h&&h.innerText!==old;}",arg=old)
 card=page.locator('.happy-bump-copy .journey-takeaway');card.locator('summary').click();expect(card.get_by_role('textbox')).to_have_value('My chosen next activity: Synthetic choice: read one page');assert notes(page)==[]
 page.screenshot(path=str(out/'happy-actual-choice-before-save-390.png'),full_page=True)
 hub=c.new_page();hub.goto(a.url+'/return-points');expect(hub.get_by_text('No saved notes yet. Saving a takeaway is always optional.',exact=True)).to_be_visible()
 card.get_by_role('button',name='Save on this device',exact=True).click();expect(card.get_by_role('status')).to_have_text('Saved on this device.');assert len(notes(page))==1;expect(hub.get_by_text('My chosen next activity: Synthetic choice: read one page',exact=True)).to_be_visible()
 # Cross-tab deletion clears the saved status and unchanged text; no resurrection.
 hub.get_by_role('button',name='Delete this note',exact=True).click();expect(card.get_by_role('button',name='Delete saved note',exact=True)).to_have_count(0);expect(card.get_by_role('textbox')).to_have_value('');assert notes(page)==[]
 # Unsaved edits remain actual drafts when an external deletion occurs.
 card.get_by_role('textbox').fill('Synthetic saved choice');card.get_by_role('button',name='Save on this device',exact=True).click();expect(hub.get_by_text('Synthetic saved choice',exact=True)).to_be_visible();card.get_by_role('textbox').fill('Synthetic unsaved adjustment');hub.get_by_role('button',name='Delete this note',exact=True).click();expect(card.get_by_role('textbox')).to_have_value('Synthetic unsaved adjustment');expect(card.get_by_role('button',name='Delete saved note',exact=True)).to_have_count(0);assert notes(page)==[]
 # Failed writes keep actual draft, no saved item or false status.
 page.evaluate("() => {window.realWrite=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){if(k==='mentation.takeaways.v1')return;window.realWrite.call(this,k,v);};}");card.get_by_role('button',name='Save on this device',exact=True).click();expect(card.get_by_role('alert')).to_contain_text('Could not save');expect(card.get_by_role('textbox')).to_have_value('Synthetic unsaved adjustment');assert notes(page)==[];page.evaluate('() => {Storage.prototype.setItem=window.realWrite;}')
 card.get_by_role('button',name='Save on this device',exact=True).click();expect(hub.get_by_text('Synthetic unsaved adjustment',exact=True)).to_be_visible();page.locator('.happy-bump-copy').get_by_role('button',name='Done',exact=True).click();page.wait_for_url(a.url+'/lift-followup',timeout=20000);assert len(notes(page))==1;page.screenshot(path=str(out/'happy-original-lift-followup-390.png'),full_page=True);hub.get_by_role('button',name='Delete this note',exact=True).click();c.close();print('PASS original Happy Bump, actual editable candidate, explicit consent, live return/save/delete, dirty draft preservation, silent write failure and original Lift followup.')
 c,page=setup(320);launch(page,'Change the Scene');page.get_by_role('button',name='Start Change the Scene',exact=True).click();page.get_by_role('button',name='Begin Change the Scene',exact=False).click()
 page.get_by_role('button',name='Another way',exact=True).click();dialog=page.get_by_role('dialog');dialog.locator('summary').click();dialog.get_by_role('textbox').fill('Synthetic custom Scene return cue');dialog.get_by_role('button',name='Save on this device',exact=True).click();page.keyboard.press('Escape')
 page.get_by_role('button',name='I moved',exact=True).click();page.get_by_role('button',name='Continue',exact=True).click()
 for _ in range(5):page.get_by_role('button',name='Skip this action',exact=True).click()
 page.get_by_role('button',name='No difference',exact=True).click();page.get_by_role('button',name='Continue to final rating',exact=True).click();expect(page.get_by_role('heading',name='Change the Scene',exact=True)).to_be_visible();page.locator('summary').click();expect(page.get_by_role('textbox')).to_have_value('Synthetic custom Scene return cue');assert len(notes(page))==1
 identity=notes(page)[0]['id'];assert identity.startswith('reset:');page.get_by_role('textbox').fill('Synthetic revised Scene return cue');page.get_by_role('button',name='Save changes on this device',exact=True).click();assert len(notes(page))==1 and notes(page)[0]['id']==identity;page.reload();page.locator('summary').click();expect(page.get_by_role('textbox')).to_have_value('Synthetic revised Scene return cue');expect(page.get_by_role('status')).to_have_text('Saved on this device.')
 # A mounted note does not present unreadable storage as a confirmed save.
 raw=page.evaluate("localStorage.getItem('mentation.takeaways.v1')");other=c.new_page();other.goto(a.url+'/return-points');other.evaluate("localStorage.setItem('mentation.takeaways.v1','{broken')");expect(page.get_by_role('alert')).to_contain_text('Could not read');expect(page.get_by_role('status')).to_have_count(0);expect(page.get_by_role('textbox')).to_have_value('Synthetic revised Scene return cue');page.get_by_role('button',name='Try reading saved note again',exact=True).click();expect(page.get_by_role('alert')).to_contain_text('Could not read');assert page.evaluate("localStorage.getItem('mentation.takeaways.v1')")=='{broken';other.evaluate("raw => localStorage.setItem('mentation.takeaways.v1',raw)",raw);expect(page.get_by_role('alert')).to_have_count(0);expect(page.get_by_role('status')).to_have_text('Saved on this device.');other.close()
 page.evaluate("document.documentElement.style.fontSize='150%'");assert page.evaluate('document.documentElement.scrollWidth<=innerWidth');page.screenshot(path=str(out/'scene-reused-note-final-checkin-320-large.png'),full_page=True);page.get_by_role('button',name='Delete saved note',exact=True).click();assert notes(page)==[];page.reload();page.locator('summary').click();expect(page.get_by_role('textbox')).to_have_value('Changes I marked as tried:\n• I moved');assert notes(page)==[]
 page.get_by_role('button',name='Skip and finish',exact=True).click();page.wait_for_url(a.url+'/',timeout=20000);page.goto(a.url+'/return-points');expect(page.get_by_text('No saved notes yet. Saving a takeaway is always optional.',exact=True)).to_be_visible();c.close();print('PASS Scene actual confirmed actions, custom note reuse/update across phases and refresh, delete without autosave, honest branded final question, 320px/150% text and original Home return.');
 c,page=setup();launch(page,'Progressive Muscle Relaxation');page.get_by_role('button',name='Start Progressive Muscle Relaxation',exact=True).click();page.get_by_role('button',name='Begin release only',exact=True).click();page.get_by_role('button',name='Stop and check in',exact=True).click();page.get_by_role('button',name='More uncomfortable',exact=False).click();page.get_by_role('button',name='Continue to check-in',exact=True).click();page.locator('.journey-takeaway summary').click();expect(page.get_by_role('textbox')).to_have_value('My PMR setup: release only · short session.\nMy tension check-in: More uncomfortable.');assert notes(page)==[];page.screenshot(path=str(out/'pmr-actual-uncomfortable-candidate-390.png'),full_page=True);page.get_by_role('button',name='Save on this device',exact=True).click();assert len(notes(page))==1;page.get_by_role('button',name='Skip and finish',exact=True).click();page.wait_for_url(a.url+'/',timeout=20000);history=page.evaluate("JSON.parse(localStorage.getItem('mentation.sessions.v1'))");assert history[0]['intensity_end'] is None;page.goto(a.url+'/return-points');expect(page.get_by_text('My PMR setup: release only · short session.\nMy tension check-in: More uncomfortable.',exact=True)).to_be_visible();page.get_by_role('button',name='Delete this note',exact=True).click();assert notes(page)==[];c.close();assert not errors,errors;print('PASS original PMR stopped release-only choice, actual worse feedback, independent skipped goal, optional return/delete.');b.close()
