from playwright.sync_api import sync_playwright,expect
from pathlib import Path
import os
OUT=Path(os.environ.get('FOUNDATIONS_EVIDENCE_DIR','/tmp/foundations-one-question'));OUT.mkdir(parents=True,exist_ok=True);BASE=os.environ.get('BASE_URL','http://127.0.0.1:5194');errors=[]
with sync_playwright() as p:
 b=p.chromium.launch(executable_path='/usr/bin/chromium')
 for width in [320,390]:
  ctx=b.new_context(viewport={'width':width,'height':640},reduced_motion='reduce');pg=ctx.new_page();pg.set_default_timeout(7000);pg.on('pageerror',lambda e:errors.append(str(e)));pg.goto(BASE+'/interventions/foundations/index.html')
  def click(text):
   if text=='← Previous':pg.locator('#back').click()
   else:pg.locator('.screen.active button').filter(has_text=text.replace(' →','')).first.click()
  def screen(name):expect(pg.locator('.screen.active')).to_have_attribute('data-screen',name);assert pg.evaluate('document.documentElement.scrollWidth<=innerWidth')
  click('Start my check-in');screen('scan')
  for i in range(17):pg.locator('.scale-point').nth(2).click();pg.locator('#questionContinue').click()
  screen('snapshot');pg.locator('.model-node').first.click();click('See 4 small options');screen('choices');pg.locator('#actionChoices button').first.click();screen('dose');pg.locator('#doseList button').first.click();screen('plan');click('Add a cue or time (optional) →');screen('cue');assert pg.locator('.screen.active select').count()==1;pg.locator('#planCue').select_option('After a meal');click('Continue →');screen('time');pg.go_back();screen('cue');click('Continue →');screen('time');assert pg.locator('.screen.active input').count()==1;pg.locator('#planTime').fill('19:30');pg.reload();screen('time');expect(pg.locator('#planTime')).to_have_value('19:30');click('← Previous');screen('cue');expect(pg.locator('#planCue')).to_have_value('After a meal');click('Continue →');click('Return to my plan →');screen('plan');click('Save my weekly plan');screen('saved');click('Review what happened');screen('review');assert pg.locator('.screen.active .review-scale').count()==1;pg.screenshot(path=str(OUT/f'foundations-review-{width}.png'),full_page=True);pg.locator('[data-review="tried"] button').nth(0).click();click('Continue →');screen('learned');click('Keep my plan and save review');screen('saved');click('Review what happened');pg.locator('[data-review="tried"] button').nth(2).click();click('Continue →');screen('review-effort');assert pg.locator('.screen.active .review-scale').count()==1;pg.locator('[data-review="effort"] button').nth(2).click();click('Continue →');screen('review-help');pg.locator('[data-review="help"] button').nth(3).click();pg.reload();screen('review-help');expect(pg.locator('[data-review="help"] button').nth(3)).to_have_attribute('aria-pressed','true');click('← Previous');screen('review-effort');expect(pg.locator('[data-review="effort"] button').nth(2)).to_have_attribute('aria-pressed','true');click('Continue →');click('Use what happened →');screen('learned');click('Keep my plan and save review');screen('saved');plan=pg.evaluate('JSON.parse(localStorage.getItem("mentication.foundations.weekly-plan.v2"))');assert len(plan['reviews'])==2;assert plan['reviews'][0]['ratings']=={'tried':1};assert plan['reviews'][1]['ratings']=={'tried':3,'effort':3,'help':4};assert plan['cue']=='After a meal' and plan['time']=='19:30';(OUT/f'foundations-draft-{width}.json').write_text(pg.evaluate('localStorage.getItem("mentication.foundations.draft.v2")'));print('PASS Foundations',width,'17 ratings, cue/time split, Not yet skip, review split, back/refresh/saved truthful review',flush=True);ctx.close()
 assert not errors,errors
 b.close()
