"""Original complete Good Map pathway; actual chosen plan and independent reported check-in."""
import argparse,json
from pathlib import Path
from playwright.sync_api import sync_playwright,expect
p=argparse.ArgumentParser();p.add_argument('--url',default='http://127.0.0.1:5191/good-map/index.html');p.add_argument('--out',required=True);args=p.parse_args();out=Path(args.out);out.mkdir(parents=True,exist_ok=True)
with sync_playwright() as pw:
 b=pw.chromium.launch(executable_path='/usr/bin/chromium');errors=[]
 for width in [320,390]:
  c=b.new_context(viewport={'width':width,'height':844},reduced_motion='reduce',accept_downloads=True);a=c.new_page();a.on('pageerror',lambda e:errors.append(str(e)));a.goto(args.url);a.locator('#gmStart').click()
  for i in range(16):
   a.locator('.tray[data-v="'+('3' if i==0 else '0')+'"]').click();a.wait_for_function('!busy')
  a.locator('#torate').click();a.locator('[data-rating="8"]').click();a.locator('#rnext').click();a.locator('#mapok').click();a.locator('#gmInterpretation').fill('Synthetic meaning: a manageable connection');a.reload();expect(a.locator('#gmInterpretation')).to_have_value('Synthetic meaning: a manageable connection');a.locator('#jnext').click();a.locator('[data-rating="3"]').click();a.locator('#jnext').click();a.locator('[data-focus]').first.click();a.locator('#jnext').click();a.locator('[data-i]').first.click();a.locator('#jnext').click();a.locator('[data-b]').first.click();a.locator('#jnext').click();a.locator('[data-u]').first.click();a.locator('#jnext').click();a.locator('#jmine').click();step='Synthetic next step: walk to the door <b>slowly</b> & return';a.locator('#gmOwnStep').fill(step);a.reload();expect(a.locator('#gmOwnStep')).to_have_value(step);a.locator('#gmUseStep').click();expect(a.locator('.jc1-t')).to_have_text(step);assert a.locator('.jc1-t b').count()==0;a.screenshot(path=str(out/f'good-map-actual-small-step-{width}.png'),full_page=True);a.locator('#jnext').click();a.locator('#gmDate').fill('2027-02-01');a.locator('#gmTime').fill('09:30');a.locator('#jnext').click();expect(a.get_by_text('No notification is scheduled by Mentication.',exact=False)).to_be_visible()
  with a.expect_download() as d:a.locator('#jcal').click()
  download=d.value;path=out/f'good-map-calendar-{width}.ics';download.save_as(str(path));content=path.read_text();assert 'BEGIN:VEVENT' in content and 'BEGIN:VALARM' in content and 'Synthetic' not in content and '<b>' not in content;a.locator('#jnext').click();expect(a.get_by_text(step,exact=True)).to_be_visible();a.reload();expect(a.get_by_text(step,exact=True)).to_be_visible();a.locator('#jnext').click();a.get_by_role('button',name='Partly',exact=True).click();expect(a.get_by_text('Before this attempt: 3',exact=False)).to_be_visible()
  if width==320:a.locator('[data-rating="0"]').click();a.locator('#jnext').click()
  else:a.locator('#gmSkipFollowup').click()
  a.get_by_role('button',name='Unhelpful',exact=True).click();a.locator('#jnext').evaluate('(button)=>{button.click();button.click()}');expect(a.get_by_text('Your satisfaction rating fell by 3.' if width==320 else 'No change score: one or both ratings were unanswered.',exact=True)).to_be_visible();data=a.evaluate("JSON.parse(localStorage.getItem('goodmap-journey-v4'))");log=data['state']['JST']['log'];assert len(log)==1 and log[0]['baseline']==3 and log[0]['endpoint']==(0 if width==320 else None);assert log[0]['helpfulness']=='worse';a.screenshot(path=str(out/f'good-map-honest-check-in-{width}.png'),full_page=True);a.get_by_role('button',name='Keep this plan',exact=True).click();a.locator('#gmMenu').click();a.get_by_role('button',name='Preview a private export',exact=True).click();expect(a.locator('#gmPreviewExport')).to_be_disabled();a.locator('#gmRecipient').fill('Synthetic reviewer');a.locator('#gmPreviewExport').click();a.locator('#gmConsent').check();preview=a.locator('#gmExportPreview').inner_text();assert 'Synthetic next step' not in preview and 'Synthetic meaning' not in preview
  with a.expect_download() as d:a.locator('#gmExport').click()
  download=d.value;path=out/f'good-map-summary-{width}.txt';download.save_as(str(path));assert path.read_text()==preview;expect(a.locator('#gmRecipient')).to_have_value('');expect(a.locator('#gmConsent')).to_have_count(0);expect(a.locator('#gmPreviewExport')).to_be_disabled();a.locator('#gmCancelShare').click();a.get_by_role('button',name='Use larger text',exact=True).click();assert a.evaluate('document.documentElement.scrollWidth<=innerWidth');a.screenshot(path=str(out/f'good-map-return-menu-large-{width}.png'),full_page=True);a.get_by_role('button',name='Dated map history',exact=True).click();expect(a.get_by_text('Synthetic meaning: a manageable connection',exact=True)).to_be_visible();a.locator('[data-delete-map]').click();a.locator('#gmDeleteConfirm').click();a.reload();data=a.evaluate("JSON.parse(localStorage.getItem('goodmap-journey-v4'))");assert not data['maps'];assert 'Synthetic next step' not in json.dumps(data);c.close();print('PASS',width,'original 16-card sort/importance/map/interpretation/satisfaction/focus/support/barrier/aim/custom-step/date/check-in, draft/plan refresh, true zero-or-blank negative report, actual calendar and consented summary downloads with privacy, larger text, dated return and deletion.')
 assert not errors,errors;b.close()
