"""Shared experience checks against a running Vite server; synthetic content only.
python3 qa/journey-experience-browser.py --url http://127.0.0.1:5177
"""
import argparse
import re
from pathlib import Path
from playwright.sync_api import sync_playwright, expect
parser = argparse.ArgumentParser()
parser.add_argument('--url', default='http://127.0.0.1:5177')
parser.add_argument('--out', default='/tmp/journey-experience-evidence')
args = parser.parse_args()
out = Path(args.out); out.mkdir(parents=True, exist_ok=True)
with sync_playwright() as p:
    browser = p.chromium.launch(headless=True, executable_path='/usr/bin/chromium')
    context = browser.new_context(viewport={'width':390,'height':844}, is_mobile=True, reduced_motion='reduce')
    page = context.new_page()
    errors=[]
    page.on('pageerror', lambda error: errors.append(str(error)))
    page.goto(args.url+'/start')
    page.evaluate("localStorage.setItem('haven_onboarded','1')")
    expect(page.get_by_role('heading',name='What would help you begin?')).to_be_visible()
    page.screenshot(path=str(out/'need-entry-mobile.png'),full_page=True)
    page.get_by_role('button',name='My body feels tense',exact=True).click()
    expect(page.get_by_role('heading',name='You could try Progressive Muscle Relaxation')).to_be_visible()
    page.get_by_role('button',name='Explore this practice').click()
    expect(page.get_by_role('button',name='Build my reset',exact=True)).to_be_disabled()
    page.get_by_role('slider').fill('4')
    page.get_by_role('button',name='Build my reset',exact=True).click()
    page.get_by_role('button',name='Begin',exact=True).click()
    page.get_by_role('button',name='Begin release only',exact=True).click(timeout=10000)
    expect(page.get_by_role('button',name='Pause PMR',exact=True)).to_be_visible()
    page.get_by_role('button',name='Another way',exact=True).click()
    dialog=page.get_by_role('dialog',name='Another way · Progressive Muscle Relaxation')
    expect(dialog).to_be_visible()
    dialog.locator('summary').click()
    field=dialog.get_by_role('textbox')
    field.fill('Synthetic note: release only for my shoulders.')
    dialog.get_by_role('button',name='Save on this device',exact=True).click()
    expect(dialog.get_by_role('status')).to_have_text('Saved on this device.')
    # Modal focus stays inside; Escape returns to the original control.
    page.keyboard.press('Tab')
    assert page.evaluate("document.querySelector('dialog[open]').contains(document.activeElement)")
    page.screenshot(path=str(out/'alternative-save-mobile.png'),full_page=True)
    page.keyboard.press('Escape')
    expect(dialog).not_to_be_visible()
    expect(page.get_by_role('button',name='Resume PMR',exact=True)).to_be_visible()
    page.get_by_role('button',name='Resume PMR',exact=True).click()
    page.get_by_role('button',name='Stop and check in',exact=True).click()
    page.get_by_role('button',name='Skip tension check',exact=True).click()
    expect(page.get_by_role('heading',name='How intense is it right now?')).to_be_visible()
    # The host restores the final check-in across refresh, without inventing a rating.
    page.reload()
    expect(page.get_by_text('Not answered yet.',exact=True)).to_be_visible()
    page.locator('summary').click()
    page.get_by_role('textbox').fill('Synthetic unsaved text')
    # Block writes and prove neither save nor deletion success is fabricated.
    page.evaluate("() => { window.originalSetItem=Storage.prototype.setItem; Storage.prototype.setItem=function(){throw new Error('Test quota')}; }")
    page.get_by_role('button',name='Save on this device',exact=True).click()
    expect(page.get_by_role('alert')).to_contain_text('Could not save')
    expect(page.get_by_role('textbox')).to_have_value('Synthetic unsaved text')
    page.evaluate('() => { Storage.prototype.setItem=window.originalSetItem; }')
    page.get_by_role('button',name='Skip and finish',exact=True).click()
    page.wait_for_url(args.url+'/', timeout=15000)
    page.goto(args.url+'/return-points')
    expect(page.get_by_text('Synthetic note: release only for my shoulders.',exact=True)).to_be_visible()
    expect(page.get_by_text('Synthetic unsaved text',exact=True)).to_have_count(0)
    page.reload()
    expect(page.get_by_text('Synthetic note: release only for my shoulders.',exact=True)).to_be_visible()
    page.evaluate("() => { window.originalSetItem=Storage.prototype.setItem; Storage.prototype.setItem=function(){throw new Error('Test quota')}; }")
    page.get_by_role('button',name='Delete this note',exact=True).click()
    expect(page.get_by_role('alert')).to_contain_text('Could not delete')
    expect(page.get_by_text('Synthetic note: release only for my shoulders.',exact=True)).to_be_visible()
    page.evaluate('() => { Storage.prototype.setItem=window.originalSetItem; }')
    page.get_by_role('button',name='Delete this note',exact=True).click()
    page.reload()
    expect(page.get_by_text('No saved notes yet. Saving a takeaway is always optional.',exact=True)).to_be_visible()
    # Existing Thought or Fact records are read in place, not copied into notes.
    page.evaluate("localStorage.setItem('mentation.thought-or-fact.records.v1', JSON.stringify([{id:'synthetic-tof', thought:'Synthetic thought',balancedConfirmed:true,ruling:'Synthetic confirmed perspective',returnPhrase:'Synthetic return phrase'}]))")
    page.reload()
    expect(page.get_by_text('Your confirmed perspective: Synthetic confirmed perspective',exact=True)).to_be_visible()
    page.get_by_role('button',name='Delete this perspective',exact=True).click()
    assert page.evaluate("JSON.parse(localStorage.getItem('mentation.thought-or-fact.records.v1')).length") == 0
    assert page.evaluate("document.documentElement.scrollWidth <= window.innerWidth")
    page.screenshot(path=str(out/'return-points-mobile.png'),full_page=True)
    # Both links are carried through the isolated Home document's validated bridge.
    page.goto(args.url+'/')
    expect(page.locator('iframe')).to_have_css('opacity', '1')
    home=page.frame_locator('iframe').first
    home.get_by_role('button',name='Return points · your saved work',exact=True).click()
    expect(page.get_by_role('heading',name='Return points',exact=True)).to_be_visible()
    page.goto(args.url+'/')
    expect(page.locator('iframe')).to_have_css('opacity', '1')
    page.frame_locator('iframe').first.get_by_role('button',name='Guide me',exact=True).click()
    expect(page.get_by_role('heading',name='What would help you begin?')).to_be_visible()
    # Browser Back returns from saved-work hub to the route that opened it.
    page.goto(args.url+'/start')
    page.get_by_role('link',name='Return to something I saved',exact=True).click()
    page.go_back()
    expect(page.get_by_role('heading',name='What would help you begin?')).to_be_visible()
    assert not errors, errors
    print('PASS: mobile entry, explicit baseline, alternative pause/return/focus, optional save, quota errors, host refresh, return/read/delete, existing-record reuse, back routing, no horizontal overflow or page errors.')
    browser.close()
