"""Original task practice, useful return and new-visit completion honesty."""
import argparse,json
from pathlib import Path
from playwright.sync_api import sync_playwright,expect
p=argparse.ArgumentParser();p.add_argument('--url',default='http://127.0.0.1:5191');p.add_argument('--out',required=True);args=p.parse_args();out=Path(args.out);out.mkdir(parents=True,exist_ok=True)
with sync_playwright() as pw:
 b=pw.chromium.launch(executable_path='/usr/bin/chromium');errors=[]
 def launch(page):
  page.goto(args.url+'/library');page.get_by_placeholder('Search practices…').fill('Next Easiest Step');page.get_by_role('button',name='Next Easiest Step').click();page.get_by_role('slider').fill('4');page.get_by_role('button',name='Start Next Easiest Step',exact=True).click()
 def saved(page):return page.evaluate("JSON.parse(localStorage.getItem('mentication_nes_v2_app_state'))")
 for width in [320,390]:
  c=b.new_context(viewport={'width':width,'height':844},reduced_motion='reduce');page=c.new_page();page.on('pageerror',lambda e:errors.append(str(e)));page.goto(args.url+'/start');page.evaluate("localStorage.setItem('haven_onboarded','1')");launch(page);page.get_by_role('button',name='Browse all tasks',exact=True).click();page.get_by_role('button',name='Three steps',exact=True).click();expect(page.get_by_role('button',name='Three steps',exact=True)).to_have_attribute('aria-pressed','true');assert saved(page)['pathLength']=='regular';page.get_by_role('button',name='Cleaning',exact=False).click();page.get_by_role('button',name='Quick Wins',exact=False).click();page.get_by_role('button',name='Tidy my desk',exact=False).click();assert len(saved(page)['ladder'])==3
  first=saved(page)['ladder'][0]['title'];expect(page.get_by_role('heading',name=first,exact=True)).to_be_visible();assert page.locator('.nes-journey-tools').evaluate("el=>getComputedStyle(el).color")=='rgb(225, 232, 193)';assert page.evaluate('document.documentElement.scrollWidth<=innerWidth');page.screenshot(path=str(out/f'focus-{width}.png'),full_page=True)
  # Pause is native-modal: focus stays inside, Escape restores the real trigger.
  trigger=page.get_by_role('button',name='Pause',exact=True).first;trigger.click();dialog=page.get_by_role('dialog');expect(dialog).to_be_visible();expect(dialog.get_by_role('button',name='Resume Focus',exact=True)).to_be_focused();page.keyboard.press('Shift+Tab');assert page.evaluate("document.querySelector('dialog').contains(document.activeElement)");page.screenshot(path=str(out/f'pause-{width}.png'),full_page=True);page.keyboard.press('Escape');expect(dialog).to_have_count(0);expect(trigger).to_be_focused()
  # An edited easier action remains pending until explicitly marked done.
  page.get_by_role('button',name='Edit step',exact=True).click();page.get_by_label('Your small action',exact=True).fill('Synthetic smaller action: place one pen');page.get_by_role('button',name='Use this step',exact=True).click();expect(page.get_by_role('heading',name='Synthetic smaller action: place one pen',exact=True)).to_be_visible();assert saved(page)['ladder'][0]['status'] is None;page.get_by_role('button',name='Done ✓',exact=True).click();page.wait_for_timeout(450);page.get_by_role('button',name='Skip this step',exact=True).click();page.wait_for_timeout(450);page.get_by_role('button',name='Finish for now',exact=True).click()
  assert page.evaluate('scrollY')==0;result=page.get_by_role('region',name='My task and next step',exact=True);last=saved(page)['ladder'][2]['title'];expect(result.get_by_role('heading',name=last,exact=True)).to_be_visible();result.locator('summary').click();expect(result.get_by_text('Marked done',exact=True)).to_be_visible();expect(result.get_by_text('Skipped',exact=True)).to_be_visible();expect(result.get_by_role('listitem').filter(has_text='Synthetic smaller action: place one pen')).to_be_visible();page.screenshot(path=str(out/f'actual-task-ending-{width}.png'),full_page=True)
  # Resume before the final handoff keeps the current visit, then refresh returns to its actual task.
  result.get_by_role('button',name='Resume this step',exact=True).click();expect(page.get_by_role('heading',name=last,exact=True)).to_be_visible();page.reload();result=page.get_by_role('region',name='My task and next step',exact=True);expect(result.get_by_role('heading',name=last,exact=True)).to_be_visible();result.get_by_role('button',name='Resume this step',exact=True).click();page.get_by_role('button',name='Another way',exact=True).click();expect(page.get_by_role('dialog')).to_be_visible();page.keyboard.press('Escape');expect(page.get_by_role('heading',name=last,exact=True)).to_be_visible();page.get_by_role('button',name='Finish for now',exact=True).click()
  # A silent task-ending write cannot advance or erase progress.
  page.evaluate("() => {window.realSet=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){if(k==='mentication_nes_v2_app_state')return;window.realSet.call(this,k,v);};}");page.get_by_role('button',name='Continue to final rating',exact=True).click();expect(page.get_by_role('alert')).to_contain_text('Could not save your task ending');assert not saved(page)['submitted'];expect(result.get_by_role('heading',name=last,exact=True)).to_be_visible();page.evaluate('() => {Storage.prototype.setItem=window.realSet;}');page.get_by_role('button',name='Continue to final rating',exact=True).click();page.get_by_role('button',name='Skip and finish',exact=True).click();page.wait_for_url(args.url+'/',timeout=20000)
  records=page.evaluate("JSON.parse(localStorage.getItem('mentation.sessions.v1'))");assert records[0]['intervention_outcome']['completedSteps']==1 and records[0]['intervention_outcome']['skippedSteps']==1;assert 'Synthetic smaller' not in json.dumps(records);assert records[0]['intensity_end'] is None
  # The unfinished task stays returnable after its earlier visit has ended.
  launch(page);result=page.get_by_role('region',name='My task and next step',exact=True);expect(result.get_by_role('heading',name=last,exact=True)).to_be_visible();result.get_by_role('button',name='Resume this step',exact=True).click();assert saved(page)['attemptStartIndex']==2;assert saved(page)['ladder'][0]['status']=='done' and saved(page)['ladder'][1]['status']=='skipped';expect(page.get_by_role('button',name='Undo previous',exact=True)).to_be_disabled();page.get_by_role('button',name='Done ✓',exact=True).click();expect(page.get_by_text('No unmarked steps remain in this ladder. Its checkmarks describe only the steps you marked done.',exact=True)).to_be_visible();page.get_by_role('button',name='Continue to final rating',exact=True).click();page.get_by_role('button',name='Skip and finish',exact=True).click();page.wait_for_url(args.url+'/',timeout=20000);records=page.evaluate("JSON.parse(localStorage.getItem('mentation.sessions.v1'))");assert len(records)==2;assert records[0]['intervention_outcome']['completedSteps']==1 and records[0]['intervention_outcome']['skippedSteps']==0;assert records[0]['attempts'][0]['completed_percentage']==1;assert records[1]['attempts'][0]['completed_percentage']<1
  # Earlier history is immutable; actual saved task remains readable after Back/forward.
  launch(page);result=page.get_by_role('region',name='My task and next step',exact=True);expect(result.get_by_role('button',name='Resume this step',exact=True)).to_have_count(0);assert saved(page)['ladder'][0]['status']=='done';page.go_back();expect(page.get_by_role('button',name='Start Next Easiest Step',exact=True)).to_be_visible();page.go_forward();expect(page.get_by_role('region',name='My task and next step',exact=True)).to_be_visible();page.evaluate("document.documentElement.classList.add('large-text')");assert page.evaluate('document.documentElement.scrollWidth<=innerWidth');page.screenshot(path=str(out/f'saved-task-return-large-{width}.png'),full_page=True);c.close();print('PASS',width,'actual 3-step selection, edit/done/skip, readable alternative, modal focus/Escape, interruption/refresh, genuine return, saved-ending failure, new-visit-only history and Back/forward.')
 # Unreadable saved work survives mount/dismiss; replacement needs an actual new-task choice.
 c=b.new_context(viewport={'width':390,'height':844},reduced_motion='reduce');page=c.new_page();page.on('pageerror',lambda e:errors.append(str(e)));page.goto(args.url+'/start');page.evaluate("localStorage.setItem('haven_onboarded','1');localStorage.setItem('mentication_nes_v2_app_state','{broken')");launch(page);expect(page.get_by_role('alert').filter(has_text='The previous task could not be read.')).to_contain_text('It has not been overwritten.');assert page.evaluate("localStorage.getItem('mentication_nes_v2_app_state')")=='{broken';page.get_by_role('button',name='Dismiss',exact=True).click();assert page.evaluate("localStorage.getItem('mentication_nes_v2_app_state')")=='{broken';page.get_by_role('button',name='Tidy my desk',exact=True).click();assert saved(page)['task']=='Tidy my desk' and len(saved(page)['ladder'])==1;expect(page.get_by_role('alert')).to_have_count(0);c.close();print('PASS unreadable task preservation, dismiss without overwrite, deliberate new-task replacement.')
 c=b.new_context(viewport={'width':390,'height':844},reduced_motion='reduce');c.add_init_script("""window.nativeTaskAudioContexts=0;const Real=window.AudioContext||window.webkitAudioContext;if(Real){const QuietProbe=class extends Real{constructor(...args){if(new Error().stack.includes('NextEasiestStepExperience'))window.nativeTaskAudioContexts++;super(...args);}};window.AudioContext=QuietProbe;window.webkitAudioContext=QuietProbe;}""");page=c.new_page();page.on('pageerror',lambda e:errors.append(str(e)));page.goto(args.url+'/start');page.evaluate("localStorage.setItem('haven_onboarded','1')");page.goto(args.url+'/next-easiest-step');page.get_by_role('slider').fill('4');page.get_by_role('button',name='Start Next Easiest Step',exact=True).click();page.get_by_role('button',name='Tidy my desk',exact=True).click();page.screenshot(path=str(out/'one-step-focus-390.png'),full_page=True);page.get_by_role('button',name='Finish for now',exact=True).click();page.screenshot(path=str(out/'one-step-unmarked-ending-390.png'),full_page=True);page.get_by_role('button',name='Resume this step',exact=True).click();page.get_by_role('button',name='Done ✓',exact=True).click();expect(page.get_by_role('button',name='Continue to final rating',exact=True)).to_be_visible();assert page.evaluate('window.nativeTaskAudioContexts')==0;c.close();print('PASS original direct silent route does not start task click/success synthesis.')
 assert not errors,errors;b.close()
