"""Actual sequential shared check-ins and optional note screens on phones."""
import argparse,json,re
from pathlib import Path
from playwright.sync_api import sync_playwright,expect
p=argparse.ArgumentParser();p.add_argument('--url',default='http://127.0.0.1:5194');p.add_argument('--out',required=True);args=p.parse_args();out=Path(args.out);out.mkdir(parents=True,exist_ok=True)
results=[]
with sync_playwright() as pw:
 b=pw.chromium.launch(executable_path='/usr/bin/chromium',args=['--mute-audio'])
 for width in [320,390]:
  c=b.new_context(viewport={'width':width,'height':640},reduced_motion='reduce');a=c.new_page();errors=[];a.on('pageerror',lambda e:errors.append(str(e)))
  a.goto(args.url+'/start');a.evaluate("localStorage.setItem('haven_onboarded','1')")
  def snap(name):
   assert a.evaluate('document.documentElement.scrollWidth<=innerWidth'),name
   a.screenshot(path=str(out/f'{name}-{width}.png'),full_page=True)
  def launch(name):
   a.goto(args.url+'/library');a.get_by_placeholder('Search practices…').fill(name);a.get_by_role('button',name=re.compile('^'+re.escape(name))).first.click()
  launch('The Happy Bump');expect(a.get_by_role('heading',name='How is your mood right now?',exact=True)).to_be_visible();expect(a.get_by_role('combobox',name='Current distress',exact=True)).to_have_count(0);a.get_by_role('button',name='0',exact=True).click();snap('one-mood-question');a.get_by_role('button',name='Continue',exact=True).click();expect(a.get_by_role('heading',name='How distressed are you right now?',exact=True)).to_be_visible();expect(a.get_by_role('slider')).to_have_count(0);a.get_by_role('combobox',name='Current distress',exact=True).select_option('7');a.reload();expect(a.get_by_role('combobox',name='Current distress',exact=True)).to_have_value('7');assert a.evaluate('history.state.usr.intensity')==0;a.evaluate('history.back()');expect(a.get_by_role('heading',name='How is your mood right now?',exact=True)).to_be_visible();assert a.evaluate('history.state.usr.intensity')==0;a.get_by_role('button',name='Continue',exact=True).click();expect(a.get_by_role('combobox',name='Current distress',exact=True)).to_have_value('7');snap('separate-distress-keeps-zero-mood')
  launch('5-4-3-2-1 Grounding');a.get_by_role('button',name='0',exact=True).click();a.get_by_role('button',name='Start 5-4-3-2-1 Grounding',exact=True).click();expect(a.get_by_role('heading',name='Five things you can see',exact=True)).to_be_visible(timeout=25000);a.get_by_role('button',name='Next sense',exact=True).click();expect(a.get_by_role('heading',name='Four things you can feel',exact=True)).to_be_visible();a.get_by_role('button',name='Pause',exact=True).click();a.reload();expect(a.get_by_role('button',name='Play',exact=True)).to_be_visible();a.get_by_role('button',name='Finish grounding early',exact=True).click();expect(a.get_by_role('heading',name='How did grounding feel?',exact=True)).to_be_visible();expect(a.get_by_role('button',name='Made things worse',exact=True)).to_have_count(0);a.get_by_role('button',name='More unsettled',exact=True).click();assert a.get_by_role('button',name='Continue to final rating',exact=True).bounding_box()['y']<640;snap('presence-one-question');a.get_by_role('button',name='Rate helpfulness · optional',exact=True).click();expect(a.get_by_role('heading',name='Was this practice helpful?',exact=True)).to_be_visible();a.get_by_role('button',name='Made things worse',exact=True).click();a.reload();expect(a.get_by_role('heading',name='Was this practice helpful?',exact=True)).to_be_visible();expect(a.get_by_role('button',name='Made things worse',exact=True)).to_have_attribute('aria-pressed','true');a.evaluate('history.back()');expect(a.get_by_role('heading',name='How did grounding feel?',exact=True)).to_be_visible();expect(a.get_by_role('button',name='More unsettled',exact=True)).to_have_attribute('aria-pressed','true');a.get_by_role('button',name='Rate helpfulness · optional',exact=True).click();a.get_by_role('button',name='Continue to final rating',exact=True).click();expect(a.get_by_text('Not answered yet.',exact=True)).to_be_visible();a.get_by_role('button',name='0',exact=True).click();a.reload();expect(a.get_by_role('button',name='Confirm rating: 0',exact=True)).to_be_visible();snap('goal-rating-one-question')
  card=a.locator('details.journey-takeaway');card.locator('summary').click();dialog=card.locator('dialog');expect(dialog).to_be_visible();expect(dialog.get_by_role('heading',name='Which grounding detail would you return to?',exact=True)).to_be_visible();a.screenshot(path=str(out/f'note-first-question-{width}.png'));dialog.get_by_role('textbox').fill('Synthetic chosen cue: the blue cup');a.keyboard.press('Tab');assert dialog.evaluate('el=>el.getBoundingClientRect().top===0');a.screenshot(path=str(out/f'note-own-screen-{width}.png'));a.evaluate("()=>{window.originalWrite=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){if(k==='mentation.takeaways.v1')throw Error('test quota');return window.originalWrite.call(this,k,v)}}");dialog.get_by_role('button',name='Save on this device',exact=True).click();expect(dialog.get_by_role('alert')).to_contain_text('Could not save');expect(dialog.get_by_role('textbox')).to_have_value('Synthetic chosen cue: the blue cup');a.evaluate('()=>{Storage.prototype.setItem=window.originalWrite}');dialog.get_by_role('button',name='Save on this device',exact=True).click();assert len(a.evaluate("JSON.parse(localStorage.getItem('mentation.takeaways.v1'))"))==1;dialog.get_by_role('button',name='Back to practice',exact=True).click();expect(dialog).not_to_be_visible();expect(card.locator('summary')).to_be_focused();card.locator('summary').click();expect(dialog.get_by_role('textbox')).to_have_value('Synthetic chosen cue: the blue cup');a.evaluate('history.back()');expect(dialog).not_to_be_visible();a.get_by_role('button',name='Skip and finish',exact=True).click();a.wait_for_url(args.url+'/',timeout=25000);records=a.evaluate("JSON.parse(localStorage.getItem('mentation.sessions.v1'))");assert records[0]['intensity_end'] is None;assert records[0]['attempts'][0]['completed_percentage']<1;assert records[0]['intervention_outcome']['presence']=='more_unsettled';a.goto(args.url+'/return-points');expect(a.get_by_text('Synthetic chosen cue: the blue cup',exact=True)).to_be_visible();a.get_by_role('button',name='Delete this note',exact=True).click();a.reload();expect(a.get_by_text('Synthetic chosen cue: the blue cup',exact=True)).to_have_count(0)
  launch('Box Breathing');a.get_by_role('button',name='0',exact=True).click();a.get_by_role('button',name='Start Box Breathing',exact=True).click();expect(a.get_by_role('button',name='Pause',exact=True)).to_be_visible(timeout=25000);a.wait_for_function("()=>history.state?.usr?.reset_box?.step===1",timeout=30000);a.wait_for_timeout(1300);a.get_by_role('button',name='Pause',exact=True).click();position=a.evaluate('history.state.usr.reset_box');assert position['clockElapsed']>0;a.reload();expect(a.get_by_role('button',name='Play',exact=True)).to_be_visible(timeout=25000);returned=a.evaluate('history.state.usr.reset_box');assert returned['step']==position['step'] and returned['clockElapsed']==position['clockElapsed'];snap('box-real-clock-return-paused');a.get_by_role('button',name='Finish here',exact=True).click();expect(a.get_by_role('heading',name='Was Box Breathing helpful?',exact=True)).to_be_visible();assert a.get_by_role('button',name='Continue',exact=True).bounding_box()['y']<640;snap('box-one-optional-question');a.get_by_role('button',name='Felt worse',exact=True).click();a.reload();expect(a.get_by_role('button',name='Felt worse',exact=True)).to_have_attribute('aria-pressed','true');a.evaluate('history.back()');expect(a.get_by_role('button',name='Play',exact=True)).to_be_visible();a.evaluate('history.forward()');expect(a.get_by_role('button',name='Felt worse',exact=True)).to_have_attribute('aria-pressed','true');a.get_by_role('button',name='Skip helpfulness',exact=True).click();expect(a.get_by_text('Not answered yet.',exact=True)).to_be_visible();a.get_by_role('button',name='Skip and finish',exact=True).click();a.wait_for_url(args.url+'/',timeout=25000)
  assert not errors,errors;results.append({'width':width,'height':640,'moodDistressSeparate':True,'zeroPreserved':True,'backRefresh':True,'groundingFeedbackSeparate':True,'pausedActualClock':True,'noteOwnScreen':True,'saveFailureRecovery':True,'saveDelete':True,'honestPartialBlankEnd':True});(out/'results.json').write_text(json.dumps(results,indent=2));c.close();print('PASS shared one-question host',width,flush=True)
 b.close()
