"""Actual Change the Scene followup: separate questions and preserved eligibility."""
import argparse,json
from pathlib import Path
from playwright.sync_api import sync_playwright,expect
p=argparse.ArgumentParser();p.add_argument('--url',default='http://127.0.0.1:5196');p.add_argument('--out',required=True);args=p.parse_args();out=Path(args.out);out.mkdir(parents=True,exist_ok=True);report=[]
with sync_playwright() as pw:
 b=pw.chromium.launch(executable_path='/usr/bin/chromium')
 for width in [320,390]:
  c=b.new_context(viewport={'width':width,'height':640},reduced_motion='reduce');c.add_init_script("localStorage.setItem('haven_onboarded','1')");a=c.new_page();errors=[];a.on('pageerror',lambda e:errors.append(str(e)));a.goto(args.url+'/library')
  a.evaluate("data=>localStorage.setItem('mentation.sessions.v1',JSON.stringify([data]))",{'id':'synthetic-scene','created_date':'2026-10-07T08:00:00Z','pathway':['changeScene'],'intensity_end':0,'context_snapshot':{'direction':'lift','intensity':0,'location':'home'},'intervention_outcome':{'handoffToken':'synthetic-token'}})
  a.goto(args.url+'/scene-followup?session=synthetic-token&practice=dear2100');expect(a.get_by_role('heading',name='How distressed are you right now?')).to_be_visible();expect(a.get_by_role('slider')).to_have_count(0);a.get_by_role('combobox',name='Current distress').select_option('0');a.reload();expect(a.get_by_role('combobox',name='Current distress')).to_have_value('0');a.get_by_role('button',name='Continue',exact=True).click();expect(a.get_by_role('heading',name='Where are you now?')).to_be_visible();a.get_by_role('combobox',name='Current setting').select_option('home');a.get_by_role('button',name='Continue',exact=True).click();a.get_by_role('combobox',name='Time available now').select_option('20');a.reload();expect(a.get_by_role('combobox',name='Time available now')).to_have_value('20');a.evaluate('history.back()');expect(a.get_by_role('heading',name='Where are you now?')).to_be_visible();expect(a.get_by_role('combobox',name='Current setting')).to_have_value('home');a.evaluate('history.forward()');expect(a.get_by_role('combobox',name='Time available now')).to_have_value('20');a.get_by_role('button',name='Continue',exact=True).click();expect(a.get_by_role('heading',name='Would you like to consider a longer journey?')).to_be_visible();a.get_by_role('button',name='Check what fits',exact=True).click();expect(a.get_by_role('button',name='Open The Happy Bump',exact=True)).to_have_count(0);a.get_by_role('button',name='Back',exact=True).click();a.get_by_role('button',name='Yes, I would like to consider it',exact=True).click();a.get_by_role('button',name='Check what fits',exact=True).click();expect(a.get_by_role('button',name='Open The Happy Bump',exact=True)).to_be_visible();expect(a.get_by_role('button',name='Open Dear 2100',exact=True)).to_have_count(0);assert a.evaluate('history.state.scene_followup.mood')==0;assert a.evaluate('document.documentElement.scrollWidth<=innerWidth');a.screenshot(path=str(out/f'scene-followup-keeps-happy-gate-{width}.png'),full_page=True)
  assert not errors,errors;report.append({'width':width,'oneQuestion':True,'zeroPreserved':True,'refreshBackForward':True,'dearCannotBypassHappy':True,'optionalLongerConsent':True,'errors':errors});c.close();print('PASS Scene followup',width,flush=True)
 b.close()
(out/'results.json').write_text(json.dumps(report,indent=2))
