"""Cumulative mobile regressions. Synthetic fixtures; a running production preview."""
import os,re,json
from playwright.sync_api import sync_playwright,expect
BASE=os.environ.get('JOURNEY_URL','http://127.0.0.1:5191')
with sync_playwright() as p:
 b=p.chromium.launch(executable_path='/usr/bin/chromium');errors=[]
 def open_page(width=320):
  c=b.new_context(viewport={'width':width,'height':740},reduced_motion='reduce');a=c.new_page();a.on('pageerror',lambda e:errors.append(str(e)));a.goto(BASE+'/start');a.evaluate("localStorage.setItem('haven_onboarded','1')");return c,a
 # No rated history is needed to delete actual books, notes and temporary drafts.
 c,a=open_page();a.evaluate("localStorage.setItem('daybook','[{\"id\":\"synthetic-journal\"}]');localStorage.setItem('dear2100-book-v1','synthetic-book');sessionStorage.setItem('dear2100-future-walk-v1','synthetic-draft');localStorage.setItem('unrelated.product','keep')");a.goto(BASE+'/profile');a.get_by_role('button',name='Delete all my data',exact=True).click();a.evaluate('()=>{window.originalRemove=Storage.prototype.removeItem;Storage.prototype.removeItem=function(){};}');a.get_by_role('button',name='Yes, delete everything',exact=True).click();expect(a.get_by_text('Deletion did not finish.',exact=False)).to_be_visible();assert a.url.endswith('/profile');a.evaluate('()=>{Storage.prototype.removeItem=window.originalRemove;}');a.get_by_role('button',name='Yes, delete everything',exact=True).click();a.wait_for_url('**/welcome');assert a.evaluate("[localStorage.getItem('daybook'),localStorage.getItem('dear2100-book-v1'),sessionStorage.getItem('dear2100-future-walk-v1')]")==[None,None,None];assert a.evaluate("localStorage.getItem('unrelated.product')")=='keep';print('PASS empty-history delete, silent failure/retry, actual local/session removal');c.close()
 # Actual authored Library entry, unanswered state, target dimensions and keyboard.
 c,a=open_page();a.goto(BASE+'/library');a.get_by_placeholder('Search practices…').fill('cannot get started');expect(a.get_by_role('button',name=re.compile('Next Easiest Step'))).to_be_visible();a.get_by_placeholder('Search practices…').fill('Box Breathing');a.get_by_role('button',name=re.compile('^Box Breathing')).first.click();five=a.get_by_role('button',name='5',exact=True);expect(five).to_have_attribute('aria-pressed','false');sizes=a.get_by_role('button',name=re.compile('^(?:[0-9]|10)$')).evaluate_all('(xs)=>xs.map(x=>({w:x.getBoundingClientRect().width,h:x.getBoundingClientRect().height}))');assert len(sizes)==11 and all(x['w']>=44 and x['h']>=44 for x in sizes),sizes;five.focus();a.keyboard.press('Enter');expect(five).to_have_attribute('aria-pressed','true');assert a.evaluate('document.documentElement.scrollWidth<=innerWidth');other=c.new_page();other.goto(BASE+'/settings');other.evaluate("localStorage.setItem('haven.a11y.v2',JSON.stringify({reducedMotion:true,highContrast:true}))");expect(a.locator('html')).to_have_class(re.compile('high-contrast'));print('PASS practice discovery, unanswered rating, 44px targets, keyboard and cross-tab contrast');c.close()
 # Direct Back ignores outside history; internal Back survives refresh.
 c,a=open_page();a.goto(BASE+'/settings');assert a.evaluate('history.length')>1;a.get_by_role('button',name='Back',exact=True).click();a.wait_for_url(BASE+'/');a.goto(BASE+'/library');a.get_by_role('navigation').get_by_role('button',name='Settings',exact=True).click();a.wait_for_url('**/settings');a.reload();a.get_by_role('button',name='Back',exact=True).click();a.wait_for_url('**/library');a.get_by_role('navigation').get_by_role('button',name='Settings',exact=True).click();a.wait_for_url('**/settings');a.evaluate("document.documentElement.style.fontSize='150%'");a.wait_for_function('document.documentElement.scrollWidth<=innerWidth');a.get_by_role('button',name='Extra large',exact=True).click();tabs=a.get_by_role('navigation',name='Primary navigation');boxes=tabs.get_by_role('button').evaluate_all('(xs)=>xs.map(x=>({x:x.getBoundingClientRect().x,y:x.getBoundingClientRect().y,w:x.getBoundingClientRect().width,h:x.getBoundingClientRect().height}))');assert len(boxes)==6 and len(set(x['y'] for x in boxes))==2 and all(x['w']>=44 and x['h']>=44 for x in boxes),boxes;tabs.get_by_role('button',name='Library',exact=True).click();a.wait_for_url('**/library');a.get_by_role('button',name=re.compile('^Box Breathing')).first.click();a.get_by_role('button',name='5',exact=True).wait_for();assert a.evaluate('document.documentElement.scrollWidth<=innerWidth');print('PASS direct/internal Back, refresh, enlarged text and full-label two-row navigation');c.close()
 # A rejected restore stays reviewable and rolls earlier writes back.
 c,a=open_page();a.evaluate("localStorage.setItem('daybook','old-archive')");a.goto(BASE+'/settings');backup={'format':'mentication-backup','version':1,'createdAt':'2026-10-06T12:00:00Z','data':{'daybook':'new-archive','dear2100-book-v1':'{}'}};a.locator('input[type=file]').set_input_files({'name':'synthetic-backup.json','mimeType':'application/json','buffer':json.dumps(backup).encode()});a.evaluate("()=>{window.originalSet=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){if(k==='dear2100-book-v1')throw new Error('Synthetic quota');return window.originalSet.call(this,k,v)};}");a.get_by_role('button',name='Restore',exact=True).click();expect(a.get_by_text('Restore could not be saved.',exact=False)).to_be_visible();assert a.evaluate("localStorage.getItem('daybook')")=='old-archive';assert a.url.endswith('/settings');print('PASS restore rollback and retained review on quota error');c.close()
 # Genuine unanswered follow-up; saving error never invents a saved check-in.
 c,a=open_page();session={'id':'synthetic-happy','direction':'lift','completed_pathway':['happyBump'],'pathway':['happyBump'],'created_date':'2026-10-06T12:00:00Z','goal_baseline':{'direction':'lift','value':3,'confirmed':True},'context_snapshot':{'location':'home','timeMin':20}};a.evaluate("s=>history.replaceState({usr:{completedSession:s},idx:0,key:'synthetic'},'', '/lift-followup')",session);a.reload();expect(a.get_by_text('Choose a rating',exact=True)).to_be_visible();expect(a.get_by_role('button',name='5',exact=True)).to_have_attribute('aria-pressed','false');a.get_by_role('button',name='6',exact=True).click();a.get_by_role('slider',name='Distress now',exact=True).fill('2');a.evaluate("()=>{window.originalSet=Storage.prototype.setItem;Storage.prototype.setItem=function(){throw new Error('Synthetic quota')};}");a.get_by_role('button',name='Confirm my check-in',exact=True).click();expect(a.get_by_role('alert')).to_contain_text('This check-in was not saved');expect(a.get_by_role('button',name='Finish here',exact=True)).to_be_visible();print('PASS follow-up fresh ratings, truthful save error and available finish');c.close()
 # Actual Journal save failure preserves the current entry; retry survives refresh.
 c,a=open_page(390);a.goto(BASE+'/journal');a.get_by_role('button',name="Write Today's Entry",exact=True).click();a.get_by_role('button',name='Confirm Inner Climate',exact=True).click();a.get_by_role('button',name='Continue to Roots',exact=True).click();a.get_by_role('button',name='Continue to Anchor',exact=True).click();a.get_by_role('button',name='Compile Entry',exact=True).click();a.evaluate("window.originalSet=Storage.prototype.setItem;Storage.prototype.setItem=function(){};");a.get_by_role('button',name='Save',exact=True).click();expect(a.get_by_role('status')).to_contain_text('not saved');expect(a.get_by_role('button',name='Save',exact=True)).to_be_visible();assert a.evaluate("localStorage.getItem('daybook')") is None;a.evaluate('()=>{Storage.prototype.setItem=window.originalSet;}');a.get_by_role('button',name='Save',exact=True).click();expect(a.get_by_role('status')).to_contain_text('Entry saved');assert len(a.evaluate("JSON.parse(localStorage.getItem('daybook'))"))==1;a.reload();expect(a.get_by_role('button',name="Write Today's Entry",exact=True)).to_be_visible();print('PASS real Journal silent-save error, retained entry and successful retry/refresh');c.close()
 # Unreadable scene history offers retry rather than hanging or inventing a result.
 c,a=open_page();a.evaluate("localStorage.setItem('mentation.sessions.v1','broken')");a.goto(BASE+'/scene-followup?session=synthetic&practice=happyBump');expect(a.get_by_role('alert')).to_contain_text('could not be read');a.evaluate("localStorage.setItem('mentation.sessions.v1','[]')");a.get_by_role('button',name='Try reading again',exact=True).click();expect(a.get_by_text('This completed Change the Scene check-in is no longer available.',exact=True)).to_be_visible();print('PASS scene history read failure and truthful retry');c.close()
 assert not errors,errors;b.close()
