"""Final reward feedback read/retry/deletion on real shared history, no reward-rule changes."""
import argparse,json
from pathlib import Path
from playwright.sync_api import sync_playwright,expect
p=argparse.ArgumentParser();p.add_argument('--url',default='http://127.0.0.1:5191');p.add_argument('--out',required=True);args=p.parse_args();out=Path(args.out);out.mkdir(parents=True,exist_ok=True)
with sync_playwright() as pw:
 b=pw.chromium.launch(executable_path='/usr/bin/chromium');errors=[]
 for width in [320,390]:
  c=b.new_context(viewport={'width':width,'height':844},reduced_motion='reduce');a=c.new_page();a.on('pageerror',lambda e:errors.append(str(e)));a.goto(args.url+'/start');a.evaluate("localStorage.setItem('haven_onboarded','1');localStorage.setItem('mentation.sessions.v1','{broken')");a.goto(args.url+'/palace');expect(a.get_by_role('alert')).to_contain_text('could not be read');expect(a.get_by_text('Nothing is built yet.',exact=False)).to_have_count(0);expect(a.get_by_text('0 stones',exact=True)).to_have_count(0);assert a.evaluate("localStorage.getItem('mentation.sessions.v1')")=='{broken';a.screenshot(path=str(out/f'palace-honest-read-recovery-{width}.png'),full_page=True)
  record={'id':'synthetic-verified-history','created_date':'2026-10-06T12:00:00Z','pathway':['grounding54321V2'],'completed_pathway':['grounding54321V2'],'attempts':[{'intervention_id':'grounding54321V2','exit_reason':'completed','completed_percentage':1}]};a.evaluate("s=>localStorage.setItem('mentation.sessions.v1',JSON.stringify([s]))",record);a.get_by_role('button',name='Try reading practice history again').click();expect(a.get_by_text('2 stones',exact=True)).to_be_visible();expect(a.get_by_text('They do not measure how you feel',exact=False)).to_be_visible();a.evaluate("document.documentElement.classList.add('large-text')");assert a.evaluate('document.documentElement.scrollWidth<=innerWidth');a.screenshot(path=str(out/f'palace-actual-saved-visits-{width}.png'),full_page=True)
  other=c.new_page();other.goto(args.url+'/start');other.evaluate("localStorage.removeItem('mentation.sessions.v1')");expect(a.get_by_text('0 stones',exact=True)).to_be_visible();expect(a.get_by_text('Nothing is built yet.',exact=False)).to_be_visible();other.evaluate("localStorage.setItem('mentation.sessions.v1','{broken')");expect(a.get_by_role('alert')).to_be_visible();expect(a.get_by_text('0 stones',exact=True)).to_have_count(0);other.evaluate("localStorage.setItem('mentation.sessions.v1','[]')");expect(a.get_by_text('0 stones',exact=True)).to_be_visible();a.reload();expect(a.get_by_text('0 stones',exact=True)).to_be_visible();assert a.evaluate("localStorage.getItem('mentation.sessions.v1')")=='[]';c.close();print('PASS',width,'Palace corrupt-history preservation/no false clearing, read retry, actual original two-stone rules, accessible rendered feedback, live cross-tab removal/recovery and refresh without resurrection.')
 assert not errors,errors;b.close()
