"""Original full Thought or Fact review, teaching, faithful reflection and recovery."""
import argparse,json,re
from pathlib import Path
from playwright.sync_api import sync_playwright,expect
p=argparse.ArgumentParser();p.add_argument('--url',default='http://127.0.0.1:5191');p.add_argument('--out',required=True);args=p.parse_args();out=Path(args.out);out.mkdir(parents=True,exist_ok=True)
KEY='mentation.thought-or-fact.records.v1'
with sync_playwright() as pw:
 b=pw.chromium.launch(executable_path='/usr/bin/chromium');errors=[]
 def setup(width):
  c=b.new_context(viewport={'width':width,'height':844},reduced_motion='reduce');a=c.new_page();a.on('pageerror',lambda e:errors.append(str(e)));a.goto(args.url+'/start');a.evaluate("localStorage.setItem('haven_onboarded','1')");return c,a
 def click(a,name):
  if a.locator('.tof-stage').count():expect(a.locator('.tof-stage')).to_have_count(1)
  a.get_by_role('button',name=name,exact=True).click()
 def launch(a,thought):
  a.goto(args.url+'/library');a.get_by_placeholder('Search practices…').fill('Thought or Fact?');a.get_by_role('button',name=re.compile('^Thought or Fact')).first.click();click(a,'0');click(a,'Continue to your thought');a.get_by_role('textbox',name='The thought you want to examine',exact=True).fill(thought);click(a,'Continue')
 def block(a,key,mode='silent'):
  a.evaluate("([key,mode])=>{window.originalSet=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){if(k===key){if(mode==='throw')throw new Error('Synthetic quota');return;}return window.originalSet.call(this,k,v)};}",[key,mode])
 def unblock(a):a.evaluate('()=>{Storage.prototype.setItem=window.originalSet;}')
 def finish(a):
  click(a,'Finish');expect(a.get_by_text('Not answered yet.',exact=True)).to_be_visible();click(a,'Skip and finish');a.wait_for_url(args.url+'/',timeout=20000)
 for width in [320,390]:
  c,a=setup(width);thought='Synthetic thought: they will reject my proposal.';support='Synthetic evidence: the last proposal was declined.';against='Synthetic uncertainty: I have not heard back about this proposal.';perspective='Synthetic balanced perspective: one proposal was declined; this proposal is still undecided.'
  launch(a,thought);click(a,'0');click(a,'Continue');click(a,'Jumping to conclusions');expect(a.get_by_text('Treating a possible meaning as certain.',exact=False)).to_be_visible();a.get_by_role('button',name=re.compile('^Prediction')).click();expect(a.locator('.tof-stage')).to_have_count(1);expect(a.locator('q.tof-quote').last).to_have_text(thought);a.get_by_role('textbox',name='What makes it seem true?',exact=True).fill(support);a.get_by_role('textbox',name='What points another way?',exact=True).fill(against);a.get_by_text('How to look at this',exact=True).click();expect(a.get_by_text('An observation is something you could see, hear or check.',exact=False)).to_be_visible();a.screenshot(path=str(out/f'evidence-learning-{width}.png'),full_page=True);assert a.evaluate('document.documentElement.scrollWidth<=innerWidth')
  # The unfinished text is a draft, not silently counted as an added evidence card.
  draft=a.evaluate("JSON.parse(localStorage.getItem('mentation.flagship.active.v1')).data");assert draft['evidenceDrafts']['support']==support and draft['support']==[];a.reload();expect(a.get_by_role('textbox',name='What makes it seem true?',exact=True)).to_have_value(support);expect(a.get_by_role('textbox',name='What points another way?',exact=True)).to_have_value(against);click(a,'Another way');expect(a.get_by_role('dialog',name='Another way · Thought or Fact')).to_be_visible();a.keyboard.press('Escape');a.go_back();a.go_forward();expect(a.get_by_role('textbox',name='What makes it seem true?',exact=True)).to_have_value(support)
  click(a,'Continue');expect(a.get_by_role('heading',name='A draft to check.',exact=True)).to_be_focused();assert a.evaluate('scrollY')==0;expect(a.locator('.tof-stage')).to_have_count(1);expect(a.locator('.tof-fairer__body')).to_contain_text(support);click(a,'Make this mine');a.get_by_role('textbox',name='A more balanced thought',exact=True).fill(perspective);click(a,'Done');a.get_by_role('checkbox').check();click(a,'7');click(a,'Continue');a.get_by_role('button',name=re.compile('^Leave this here for now')).click();a.locator('label').filter(has_text='If this thought returns').get_by_role('textbox').fill('Synthetic cue: keep the facts and the unknown')
  block(a,KEY);click(a,'Save privately on this device');expect(a.get_by_role('alert')).to_contain_text('could not confirm');assert a.evaluate('k=>localStorage.getItem(k)',KEY) is None;a.screenshot(path=str(out/f'honest-save-recovery-{width}.png'),full_page=True);unblock(a);click(a,'Save privately on this device');expect(a.get_by_role('button',name='Saved on this device',exact=True)).to_be_disabled();record=a.evaluate('k=>JSON.parse(localStorage.getItem(k))[0]',KEY);assert record['ruling']==perspective and record['support']==[support] and record['evidenceAgainst']==[against] and record['certaintyBefore']==0 and record['certaintyAfter']==7
  other=c.new_page();other.goto(args.url+'/return-points');expect(other.get_by_text('Your confirmed perspective: '+perspective,exact=True)).to_be_visible();other.get_by_text('The details I kept',exact=True).click();expect(other.get_by_text(support,exact=True)).to_be_visible();other.get_by_role('searchbox',name='Find saved work',exact=True).fill('last proposal was declined');expect(other.locator('article')).to_have_count(1);other.get_by_role('searchbox',name='Find saved work',exact=True).fill('no matching words');expect(other.locator('article')).to_have_count(0);click(other,'Clear saved-work search')
  # Editing then explicitly saving updates one reflection, preserving identity/date.
  a.locator('label').filter(has_text='If this thought returns').get_by_role('textbox').fill('Synthetic edited cue');click(a,'Save privately on this device');records=a.evaluate('k=>JSON.parse(localStorage.getItem(k))',KEY);assert len(records)==1 and records[0]['id']==record['id'] and records[0]['createdAt']==record['createdAt'];expect(other.get_by_text('Your return phrase: Synthetic edited cue',exact=True)).to_be_visible();click(other,'Delete this perspective');expect(a.get_by_role('button',name='Save privately on this device',exact=True)).to_be_visible();a.reload();expect(a.get_by_role('button',name='Save privately on this device',exact=True)).to_be_visible();assert a.evaluate('k=>JSON.parse(localStorage.getItem(k))',KEY)==[];click(a,'Save privately on this device');assert len(a.evaluate('k=>JSON.parse(localStorage.getItem(k))',KEY))==1
  a.evaluate("document.documentElement.classList.add('large-text')");assert a.evaluate('document.documentElement.scrollWidth<=innerWidth');a.screenshot(path=str(out/f'actual-perspective-ending-{width}.png'),full_page=True);finish(a);history=a.evaluate("JSON.parse(localStorage.getItem('mentation.sessions.v1'))");assert 'Synthetic thought' not in json.dumps(history);a.goto(args.url+'/return-points');a.get_by_text('The details I kept',exact=True).click();a.screenshot(path=str(out/f'actual-perspective-return-{width}.png'),full_page=True);block(a,KEY,'throw');click(a,'Delete this perspective');expect(a.get_by_role('alert')).to_contain_text('Could not delete');expect(a.get_by_text('Your confirmed perspective: '+perspective,exact=True)).to_be_visible();unblock(a);click(a,'Delete this perspective');a.reload();expect(a.get_by_text('Your confirmed perspective: '+perspective,exact=True)).to_have_count(0);c.close();print('PASS',width,'full native thought/belief/sort/evidence/edit/confirmation/direction/save path; useful teaching and actual thought; unfinished evidence refresh/alternative/Back; silent save retry; same-ID edit; live search/deletion; large text; honest belief and blank goal; actual return.')
 # Real concern may stay unresolved; its own evidence remains useful without a fabricated perspective.
 c,a=setup(320);launch(a,'Synthetic thought: I missed the deadline.');click(a,'Continue');a.get_by_role('button',name=re.compile('^Fact')).click();a.get_by_role('textbox',name='What makes it seem true?',exact=True).fill('Synthetic detail: the stated deadline was yesterday.');click(a,'Continue');click(a,'Keep it unresolved');a.get_by_role('button',name=re.compile('^Leave this here for now')).click();a.evaluate("localStorage.setItem('mentation.thought-or-fact.records.v1','broken')");click(a,'Save privately on this device');expect(a.get_by_role('alert')).to_contain_text('could not confirm');assert a.evaluate('k=>localStorage.getItem(k)',KEY)=='broken';a.reload();expect(a.get_by_text('Left unresolved',exact=True)).to_be_visible();assert a.evaluate('k=>localStorage.getItem(k)',KEY)=='broken';a.evaluate("localStorage.setItem('mentation.thought-or-fact.records.v1',JSON.stringify([{id:'synthetic-legacy',thought:'Prior real saved reflection',legacy:'kept'}]))");block(a,KEY,'throw');click(a,'Save privately on this device');expect(a.get_by_role('alert')).to_be_visible();unblock(a);click(a,'Save privately on this device');records=a.evaluate('k=>JSON.parse(localStorage.getItem(k))',KEY);assert len(records)==2 and records[1]['legacy']=='kept' and records[0]['fairerView'] is None and records[0]['certaintyBefore'] is None and records[0]['certaintyAfter'] is None;finish(a);a.goto(args.url+'/return-points');expect(a.get_by_text('You chose to leave this unresolved.',exact=True)).to_be_visible();a.get_by_text('The details I kept',exact=True).click();expect(a.get_by_text('Synthetic detail: the stated deadline was yesterday.',exact=True)).to_be_visible();c.close();print('PASS genuine unresolved concern preserves entered evidence, blank belief answers, unreadable archive and legacy work; thrown save/refresh/retry, no invented confirmed perspective.')
 # The draft itself must not falsely claim durability when storage is blocked.
 c,a=setup(390);launch(a,'Synthetic draft thought');click(a,'Continue');a.get_by_role('button',name=re.compile('^Not sure')).click();block(a,'mentation.flagship.active.v1');a.get_by_role('textbox',name='What makes it seem true?',exact=True).fill('Synthetic unsaved draft');expect(a.get_by_role('status').filter(has_text='This draft could not be saved.')).to_be_visible();expect(a.get_by_role('textbox',name='What makes it seem true?',exact=True)).to_have_value('Synthetic unsaved draft');unblock(a);a.get_by_role('textbox',name='What makes it seem true?',exact=True).fill('Synthetic draft retry');expect(a.get_by_role('status').filter(has_text='This draft could not be saved.')).to_have_count(0);a.reload();expect(a.get_by_role('textbox',name='What makes it seem true?',exact=True)).to_have_value('Synthetic draft retry');c.close();print('PASS silent automatic-draft failure is honest, retains mounted text and persists the actual edited retry.')
 assert not errors,errors;b.close()
