"""Production Urge Surfing entry/practice/return, with real elapsed timers and synthetic notes."""
import argparse, json
from pathlib import Path
from playwright.sync_api import sync_playwright, expect
parser = argparse.ArgumentParser()
parser.add_argument('--url', default='http://127.0.0.1:5191')
parser.add_argument('--out', default='/tmp/urge-practice-review')
args = parser.parse_args()
out = Path(args.out)
out.mkdir(parents=True, exist_ok=True)
with sync_playwright() as p:
    b = p.chromium.launch(executable_path='/usr/bin/chromium')
    errors = []

    def create(width):
        c = b.new_context(viewport={'width': width, 'height': 844 if width == 390 else 640}, reduced_motion='reduce')
        a = c.new_page()
        a.on('pageerror', lambda e: errors.append(str(e)))
        a.goto(args.url + '/start')
        a.evaluate("localStorage.setItem('haven_onboarded','1')")
        return (c, a)

    def launch(a):
        a.goto(args.url + '/library')
        a.get_by_placeholder('Search practices…').fill('Urge Surfing')
        a.get_by_role('button', name='Short start (≤3 min)', exact=True).click()
        expect(a.get_by_text('30–60 sec practice · optional setup', exact=False)).to_be_visible()
        a.get_by_role('button', name='Urge Surfing').click()
        a.get_by_role('slider').fill('4')
        a.get_by_role('button', name='Start Urge Surfing', exact=True).click()
        expect(a.get_by_role('heading', name='Make a little space before acting.')).to_be_visible(timeout=15000)

    def stop(a):
        a.get_by_role('button', name='End early', exact=False).click()
        dialog = a.get_by_role('dialog', name='Leave the wave?')
        expect(dialog).to_be_visible()
        assert a.evaluate("document.activeElement.closest('dialog') !== null")
        a.keyboard.press('Tab')
        assert a.evaluate("document.activeElement.closest('dialog') !== null")
        dialog.get_by_role('button', name='End gently', exact=True).click()

    def finish(a):
        a.get_by_role('button', name='Continue to final check-in', exact=True).click()
        expect(a.get_by_role('button', name='Skip and finish', exact=True)).to_be_visible()
        a.reload()
        expect(a.get_by_role('button', name='Skip and finish', exact=True)).to_be_visible()
        a.get_by_role('button', name='Skip and finish', exact=True).click()
        a.wait_for_function("JSON.parse(localStorage.getItem('mentation.sessions.v1') || '[]').length > 0")
        return a.evaluate("JSON.parse(localStorage.getItem('mentation.sessions.v1'))[0]")
    c, a = create(320)
    launch(a)
    expect(a.get_by_role('heading', name='How strong is the urge?', exact=True)).not_to_be_visible()
    a.screenshot(path=str(out / 'urge-direct-start-320.png'), full_page=True)
    a.get_by_role('button', name='30 seconds', exact=True).click()
    a.get_by_role('button', name='Start with a detail around me', exact=True).click()
    expect(a.get_by_role('button', name='Pause practice', exact=True)).to_be_visible()
    a.wait_for_timeout(1400)
    a.get_by_role('button', name='Pause practice', exact=True).click()
    remaining = a.locator('.urge-lovable__practice-time strong').inner_text()
    snapshot = a.evaluate('history.state.urgeSurfRuntime')
    assert snapshot['initialIntensity'] is None
    assert snapshot['entryMode'] == 'external'
    assert 'anchorText' not in snapshot and 'bodyRegionKey' not in snapshot
    a.reload()
    expect(a.get_by_role('button', name='Resume practice', exact=True)).to_be_visible(timeout=15000)
    expect(a.locator('.urge-lovable__practice-time strong')).to_have_text(remaining)
    a.wait_for_timeout(1000)
    expect(a.locator('.urge-lovable__practice-time strong')).to_have_text(remaining)
    a.go_back()
    expect(a.get_by_role('button', name='Start Urge Surfing', exact=True)).to_be_visible()
    a.go_forward()
    expect(a.get_by_role('button', name='Resume practice', exact=True)).to_be_visible(timeout=15000)
    expect(a.locator('.urge-lovable__practice-time strong')).to_have_text(remaining)
    a.get_by_role('button', name='Another way', exact=True).click()
    dialog = a.get_by_role('dialog', name='Another way · Urge Surfing')
    expect(dialog).to_be_visible()
    dialog.get_by_role('button', name='Return to Urge Surfing', exact=True).click()
    expect(a.get_by_role('button', name='Resume practice', exact=True)).to_be_visible()
    a.get_by_role('button', name='End early', exact=False).click()
    a.keyboard.press('Escape')
    expect(a.get_by_role('dialog', name='Leave the wave?')).not_to_be_visible()
    expect(a.get_by_role('button', name='Resume practice', exact=True)).to_be_visible()
    a.get_by_role('button', name='Resume practice', exact=True).click()
    a.wait_for_timeout(500)
    stop(a)
    expect(a.get_by_text('Practice ended early', exact=True)).to_be_visible()
    expect(a.get_by_text('No final intensity rating was recorded.', exact=True)).to_be_visible()
    a.screenshot(path=str(out / 'urge-ended-320.png'), full_page=True)
    a.get_by_text('Urge check-in · optional', exact=True).click()
    expect(a.get_by_text('No rating chosen', exact=True)).to_be_visible()
    a.get_by_role('button', name='Confirm 5 out of 10', exact=True).click()
    expect(a.get_by_text('Your confirmed urge rating: 5 out of 10. No starting urge rating was recorded.', exact=True)).to_be_visible()
    a.get_by_role('button', name='Less room / more unsettled', exact=True).click()
    expect(a.get_by_role('heading', name='You noticed less room to choose.')).to_be_visible()
    a.get_by_text('Practice feedback and local record · optional', exact=True).click()
    a.get_by_role('button', name='Made things worse', exact=True).click()
    a.get_by_role('checkbox').check()
    a.reload()
    expect(a.get_by_role('heading', name='You noticed less room to choose.')).to_be_visible()
    a.locator('.urge-lovable__complete').get_by_text('Keep something for later · optional', exact=True).click()
    field = a.get_by_role('textbox')
    field.fill('Synthetic Urge action: put my phone down and ask Sam for support.')
    a.evaluate("() => { window.urgeOriginalSet=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){if(k==='mentation.takeaways.v1')return;window.urgeOriginalSet.call(this,k,v)}; }")
    a.get_by_role('button', name='Save on this device', exact=True).click()
    expect(a.get_by_role('alert')).to_contain_text('Could not save')
    expect(field).to_have_value('Synthetic Urge action: put my phone down and ask Sam for support.')
    a.evaluate('() => { Storage.prototype.setItem=window.urgeOriginalSet; }')
    a.get_by_role('button', name='Save on this device', exact=True).click()
    expect(a.get_by_role('status')).to_have_text('Saved on this device.')
    assert a.evaluate('document.documentElement.scrollWidth<=innerWidth')
    record = finish(a)
    attempt = next((x for x in record['attempts'] if x['intervention_id'] == 'urgeSurf'))
    assert attempt['exit_reason'] == 'exited' and 0 < attempt['completed_percentage'] < 1
    assert record['intensity_end'] is None
    assert record['intervention_outcome']['intensityBefore'] is None
    assert record['intervention_outcome']['intensityNow'] == 5
    assert record['intervention_outcome']['choiceOutcome'] == 'stronger'
    a.goto(args.url + '/return-points')
    expect(a.get_by_text('Synthetic Urge action: put my phone down and ask Sam for support.', exact=True)).to_be_visible()
    a.screenshot(path=str(out / 'urge-actual-saved-note-320.png'), full_page=True)
    a.get_by_role('button', name='Delete this note', exact=True).click()
    a.reload()
    expect(a.get_by_text('Synthetic Urge action: put my phone down and ask Sam for support.', exact=True)).not_to_be_visible()
    c.close()
    print('PASS direct start, early stop, exact paused refresh/resume, modal focus/Escape, independent ratings, retained failed-save note, true partial history, saved return/delete.', flush=True)
    c, a = create(390)
    launch(a)
    a.get_by_role('button', name='30 seconds', exact=True).click()
    a.get_by_role('button', name='Start with a detail around me', exact=True).click()
    a.wait_for_timeout(16000)
    a.screenshot(path=str(out / 'urge-original-wave-390.png'), full_page=True)
    expect(a.get_by_text('Practice complete', exact=True)).to_be_visible(timeout=20000)
    expect(a.get_by_role('heading', name='How strong is the urge?', exact=True)).not_to_be_visible()
    a.screenshot(path=str(out / 'urge-complete-without-new-forms-390.png'), full_page=True)
    record = finish(a)
    attempt = next((x for x in record['attempts'] if x['intervention_id'] == 'urgeSurf'))
    assert attempt['exit_reason'] == 'completed' and attempt['completed_percentage'] == 1
    assert not record.get('intervention_outcome')
    assert a.evaluate("JSON.parse(localStorage.getItem('mentation.takeaways.v1')||'[]').length") == 0
    c.close()
    print('PASS real elapsed wave completes, no fabricated ratings/outcome/note.', flush=True)
    c, a = create(390)
    launch(a)
    a.get_by_text('Add an urge rating or body anchor · optional', exact=True).click()
    expect(a.locator('.urge-lovable__orb-value strong')).to_have_text('—')
    a.get_by_role('button', name='Confirm 7 out of 10', exact=True).click()
    a.get_by_role('button', name='Choose my anchor', exact=True).click()
    a.get_by_role('button', name='Chest', exact=True).click()
    a.get_by_role('button', name='Tight', exact=True).click()
    a.get_by_role('button', name='Continue', exact=True).click()
    a.get_by_role('textbox').fill('Synthetic PRIVATE anchor')
    a.get_by_role('button', name='Start surfing', exact=True).click()
    a.get_by_role('button', name='Pause practice', exact=True).click()
    serialized = json.dumps(a.evaluate('history.state.urgeSurfRuntime'))
    assert 'PRIVATE' not in serialized and 'chest' not in serialized and ('tight' not in serialized)
    a.reload()
    expect(a.get_by_role('button', name='Resume practice', exact=True)).to_be_visible(timeout=15000)
    expect(a.get_by_text('Notice what is here, without needing to locate it', exact=True)).to_be_visible()
    stop(a)
    expect(a.get_by_role('heading', name='How strong is the urge?', exact=True)).to_be_visible()
    a.get_by_role('button', name='Confirm 7 out of 10 · unchanged', exact=True).click()
    a.get_by_role('button', name='No change', exact=True).click()
    a.get_by_role('button', name='Complete practice', exact=True).click()
    expect(a.get_by_role('heading', name='You noticed no change in choice.')).to_be_visible()
    expect(a.get_by_text('Urge intensity: 7 → 7. 0 points change.', exact=True)).to_be_visible()
    a.get_by_role('button', name='Ride it again', exact=True).click()
    expect(a.get_by_role('button', name='Pause practice', exact=True)).to_be_visible()
    a.get_by_role('button', name='Pause practice', exact=True).click()
    stop(a)
    a.get_by_role('button', name='I’d rather not say', exact=True).click()
    expect(a.get_by_text('No final intensity rating was recorded.', exact=True)).to_be_visible()
    c.close()
    print('PASS guided route, original questions/scales, no private draft in history, unchanged feedback, repeat clears end ratings.', flush=True)
    assert not errors, errors
    b.close()
